### ISSUE TITLE
Introduce pakyow

### ISSUE THREAD

**Issue by waghanza** [the-benchmarker/web-frameworks#1004]
+ Language : ruby
+ Repo : https://github.com/pakyow/pakyow
+ Author : @bryanp

**Comment by bryanp** [comment]
I looked at the other Ruby examples and put an app together:

* https://github.com/bryanp/benchmark-pakyow

A big difference between Pakyow and other Ruby frameworks is that Pakyow isn't compatible with Rack by default and ships with an app server based on [Async HTTP](https://github.com/socketry/async-http). You can load a compatibility layer to run Pakyow on something like Puma, but you'll incur a ~30% penalty in performance.

Booting the app in production looks like this:

```
bundle exec pakyow boot -e production
```

**Comment by waghanza** [comment]
@bryanp The idea is take what is the "default" choice for **production**, I mean the plethora of `ruby` **frameworks** could run on `puma`, `unicorn`, `passenger` ... but the idea is to run the on `puma` since it is the most use case (an also the default choice in `rails` :stuck_out_tongue:))

However, https://github.com/ohler55/agoo (we have `here`) is not **rake** compatible. For this framework, we then run with the `built-in` command. If there is `built-in` for https://github.com/pakyow/pakyow the idea is to use them, it is a more valuable comparison that trying to adapt them to **rack** :heart:
