### ISSUE TITLE
Missed update

### ISSUE THREAD

**Issue by waghanza** [the-benchmarker/web-frameworks#1080]
Hi @dependabot,

`restana` was published 3 days ago on npm registry => https://www.npmjs.com/package/restana

This app is referenced here => https://github.com/the-benchmarker/web-frameworks/blob/master/node/restana/package.json and the configuration https://github.com/the-benchmarker/web-frameworks/blob/master/.dependabot/config.yml#L298

Could you investigate ?

Regards,

**Comment by greysteil** [comment]
It looks like you got [this PR](https://github.com/the-benchmarker/web-frameworks/pull/1065) for the `restana` update. Were you expected anything else / am I missing anything?

**Comment by waghanza** [comment]
Hi @greysteil,

Seems I have closed the `PR`, but why ?
