### ISSUE TITLE
gin's URL is wrong http://gin-gonic.github.io/gin

### ISSUE THREAD

**Issue by dlintw** [the-benchmarker/web-frameworks#1090]
For example, the gin's URL is
https://github.com/gin-gonic/gin

not

http://github.com/gin-gonic/gin

**Comment by waghanza** [comment]
Hi @dlintw,

The `gin` URL is http here, and you requested for change.

However, either you click on `http` or `https` link, github will redirect you.

Any benefit for this community having `https` instead of `http` (this change the behavior for all frameworks) ?

Regards,

**Comment by dlintw** [comment]
http://gin-gonic.github.io/gin is wrong, it should be https://gin-gonic.com/ now

**Comment by waghanza** [comment]
ah ok
