### ISSUE TITLE
RTE - routing table extraordinaire

### ISSUE THREAD

**Issue by dlintw** [the-benchmarker/web-frameworks#1091]
+ Language : Golang
+ Repo : https://github.com/jwilner/rte
+ Author :  Joe Wilner jhwilner1@gmail.com

**Comment by waghanza** [comment]
Awesome, a `PR` will be :heart: (I'm here to help, if any question)

**Comment by waghanza** [comment]
Hi @jwilner,

Would you mind to add (or consent that we add) [rte](https://github.com/jwilner/rte) in `here` ?

This project compare performance based on 3 routes :

+ `GET` `/`, **SHOULD** return a successful status code and an empty string
+ `GET` `/user/:id`, **SHOULD** return a successful status code and the id
+ `POST` `/user`, **SHOULD** return a successful status code and an empty string

Regards,

**Comment by jwilner** [comment]
Hi @waghanza -- I went ahead and created a PR for you. Cheers.
