### ISSUE TITLE
Add 0http framework

### ISSUE THREAD

**Issue by jkyberneees** [the-benchmarker/web-frameworks#1098]
+ Language : Node
+ Repo : https://github.com/jkyberneees/0http
+ Author : Rolando Santamaria Maso (restana author)

app.js
```js
const cero = require('0http')
const { router, server } = cero()

router.on('GET', '/', (req, res) => {
  res.end()
})

router.on('GET', '/user/:id', (req, res, params) => {
  res.end(params.id)
})

router.on('POST', '/user', (req, res) => {
  res.end()
})

server.listen(3000)

```

package.json
```json
{
  "dependencies": {
    "0http": "1.0.0"
  }
}
```

Dockerfile
```Dockerfile
FROM node:11.11.0

RUN npm -g install pm2

WORKDIR /usr/src/app

COPY app.js package.json ./

RUN npm install

ENV NODE_ENV production

CMD pm2-runtime start app.js -i $(nproc)
```

**Comment by waghanza** [comment]
@jkyberneees is this a replacement of `restana` ?

**Comment by jkyberneees** [comment]
Hi @waghanza, I want this low level library a dependency for restana in the future. For now, please consider it a low level Nodejs HTTP server with routing capabilities. That is as fast as node can be ;)

**Comment by waghanza** [comment]
It's a like`turbo` then

**Comment by jkyberneees** [comment]
No, this is one is based on Node.js HTTP Server implementation. Unfortunately `turbo` is still not 100% compatible with the low level Node.js interfaces yet.

**Comment by jkyberneees** [comment]
Closing in favor of: https://github.com/the-benchmarker/web-frameworks/pull/1368
