### ISSUE TITLE
Introduce Buffalo

### ISSUE THREAD

**Issue by Jinfaa** [the-benchmarker/web-frameworks#1131]
+ Language : GO
+ Repo : https://github.com/gobuffalo/buffalo
+ Author : @markbates

**Comment by waghanza** [comment]
Hi @markbates,

Would you mind to add (or consent that we add) [buffalo](https://github.com/gobuffalo/buffalo) in `here` ?

This project compare performance based on 3 routes :

+ `GET` `/`, **SHOULD** return a successful status code and an empty string
+ `GET` `/user/:id`, **SHOULD** return a successful status code and the id
+ `POST` `/user`, **SHOULD** return a successful status code and an empty string

Regards,
