### ISSUE TITLE
Removing muxie ?

### ISSUE THREAD

**Issue by waghanza** [the-benchmarker/web-frameworks#1158]
Hi all,

Since we are debating about `iris`, should we also keep/remove `muxie` ?

https://github.com/the-benchmarker/web-frameworks/issues/1129

Regards,

**Comment by brunocassol** [comment]
Thanks for opening this issue.
I don't think there's much point in keeping muxie since it belongs to the same author of iris.
Also there's the possibility that other Go projects are reluctant to be listed alongside with muxie in the benchmarks.

regards
