### ISSUE TITLE
Introduce hyron

### ISSUE THREAD

**Issue by waghanza** [the-benchmarker/web-frameworks#1159]
+ Language : javascript
+ Repo : https://github.com/hyron-group/hyron
+ Author : @thangdjw

**Comment by Aderinom** [comment]
I'm pretty sure the hyron project is dead. 

Last commit was 4 Years ago, and the packet seems to be broken.

Idk about your policies but I assume this can probably be closed?

**Comment by waghanza** [comment]
Not sure we can say that according to the commit date, but let's ping @thangdjw for this.

**Comment by thangdjw** [comment]
yes, it is closed
