### ISSUE TITLE
Introduce javalin

### ISSUE THREAD

**Issue by waghanza** [the-benchmarker/web-frameworks#1162]
+ Language : java
+ Repo : https://github.com/tipsy/javalin
+ Author : @tipsy

**Comment by tipsy** [comment]
👋 

Why did you tag me? Need help setting it up?

**Comment by waghanza** [comment]
Just wanted to ping you to warn you 😉

Btw, if you want to contribute / implement `javalin` **here** I'll be :heart:

**Comment by tipsy** [comment]
I'm busy working on Javalin 3.0, so I think I'll have to sit this one out. Everything you need should be in the docs though, please ping me if you have any questions :)

**Comment by waghanza** [comment]
Sure, I'll try, even if my `java` skill stop at `jdk` 6 😆

**Comment by waghanza** [comment]
Hi @tipsy,

Would you mind to add (or consent that we add) [javalin](https://github.com/tipsy/javalin) in `here` ?

This project compare performance based on 3 routes :

+ `GET` `/`, **SHOULD** return a successful status code and an empty string
+ `GET` `/user/:id`, **SHOULD** return a successful status code and the id
+ `POST` `/user`, **SHOULD** return a successful status code and an empty string

Regards,

**Comment by tipsy** [comment]
```kotlin
Javalin.create().apply {
    get("/") { }
    get("/user/:id") { it.result(it.pathParam("id")) }
    post("/user") { }
}.start(port)
```

This server fulfills your requirements. I'm not sure if it's a very good performance test though.

There's not much for the router to do, and the path-param extraction is nano/micro second operation.

There should be no difference between a GET and a POST when it comes to performance,  (unless someone is doing something very strange).
