### ISSUE TITLE
Introduce grape

### ISSUE THREAD

**Issue by waghanza** [the-benchmarker/web-frameworks#1168]
+ Language : ruby
+ Repo : https://github.com/ruby-grape/grape
+ Author : @mbleigh

**Comment by waghanza** [comment]
Hi @mbleigh @dblock,

Would you mind to add (or consent that we add) [grape](https://github.com/ruby-grape/grape) in `here` ?

This project compare performance based on 3 routes :

+ `GET` `/`, **SHOULD** return a successful status code and an empt²y string
+ `GET` `/user/:id`, **SHOULD** return a successful status code and the id
+ `POST` `/user`, **SHOULD** return a successful status code and an empty string

Regards,

**Comment by dblock** [comment]
Please go for it.
