### ISSUE TITLE
Add Adonis (NodeJS)

### ISSUE THREAD

**Issue by kalicki** [the-benchmarker/web-frameworks#118]
https://github.com/adonisjs
ping to @thetutlage

**Comment by aichholzer** [comment]
Thank you for this @kalicki  -I will try to get this into our next release cycle. Also, you are most welcome to submit a PR if you already have experience with Adonis.

**Comment by aichholzer** [comment]
@thetutlage would you be interested in submitting a PR for this?

**Comment by waghanza** [comment]
consent given on `discord`

**Comment by judasane** [comment]
I hope someone can add it

**Comment by waghanza** [comment]
want to try ? @judasane

**Comment by waghanza** [comment]
Hi @mrrfly,

I closed https://github.com/the-benchmarker/web-frameworks/issues/5073 since this one is about `adonis`

Feel free to create an implementation for `adonis`
