### ISSUE TITLE
Introduce masonite

### ISSUE THREAD

**Issue by vaibhavmule** [the-benchmarker/web-frameworks#1238]
+ Language : python
+ Repo : https://github.com/MasoniteFramework/masonite
+ Author : @josephmancuso

**Comment by waghanza** [comment]
@vaibhavmule if you mind `PR` it'll be awesome

The implementation is very simple `here`

**Comment by vaibhavmule** [comment]
it does not have dockerfile, here is PR: https://github.com/the-benchmarker/web-frameworks/pull/1249
