### ISSUE TITLE
Introduce toro

### ISSUE THREAD

**Issue by waghanza** [the-benchmarker/web-frameworks#1259]
+ Language : crystal
+ Repo : https://github.com/soveran/toro
+ Author : @soveran

**Comment by waghanza** [comment]
Hi @soveran,

Would you mind to add (or consent that we add) [toro](https://github.com/soveran/toro) in `here` ?

This project compare performance based on 3 routes :

+ `GET` `/`, **SHOULD** return a successful status code and an empty string
+ `GET` `/user/:id`, **SHOULD** return a successful status code and the id
+ `POST` `/user`, **SHOULD** return a successful status code and an empty string

Regards,

**Comment by soveran** [comment]
@waghanza I consent that you add Toro, it would be great to have it here. I can't do it myself right now, but I could take care of it in early October. If someone else wants to go ahead, that would be great.
