### ISSUE TITLE
Introduce cr-melon

### ISSUE THREAD

**Issue by waghanza** [the-benchmarker/web-frameworks#1265]
+ Language : crystal
+ Repo : https://github.com/gdotdesign/cr-melon
+ Author : @gdotdesign

**Comment by waghanza** [comment]
Hi @gdotdesign,

Would you mind to add (or consent that we add) [cr-melon](https://github.com/gdotdesign/cr-melon) in `here` ?

This project compare performance based on 3 routes :

+ `GET` `/`, **SHOULD** return a successful status code and an empt²y string
+ `GET` `/user/:id`, **SHOULD** return a successful status code and the id
+ `POST` `/user`, **SHOULD** return a successful status code and an empty string

Regards,

**Comment by gdotdesign** [comment]
Hi @waghanza, sure you can add it if you like, although I'm not sure that it's up to date with the current Crystal version.

**Comment by waghanza** [comment]
@gdotdesign It seems to be up-to-date with th latest `crystal`

However, could `melon` take dynamic paths, I mean having the same method for
+ `/user/0`
+ `/user/1`
+ `/user/2`
+ ....
?

**Comment by gdotdesign** [comment]
@waghanza you are right, it does not support that.

**Comment by waghanza** [comment]
@gdotdesign I can not add `melon` `here` then

**Comment by gdotdesign** [comment]
@waghanza ok, it was an only experiment anyway :)
