### ISSUE TITLE
Swift 5.0 Kitura-NIO  

### ISSUE THREAD

**Issue by shial4** [the-benchmarker/web-frameworks#1279]
You already have a benchmark for Kitura. However, there is an option to lunch kitura under Swift-NIO. It is a totally different implementation. I am curious how would results look like under this environment. 

With Kitura, to run on top of Kitura-NIO (instead of Kitura-Net) all you need to do is set an environment variable called KITURA_NIO before building your Kitura application.

+ Language : Swift 5.0
+ Repo : https://github.com/IBM-Swift/Kitura-NIO
+ Author : IBM-Swift

**Comment by waghanza** [comment]
Interesting, two variants of `kitura`. What does this `swift-nio` offer ?

**Comment by shial4** [comment]
The core comprising of HTTPServer, ClientRequest/ClientResponse and TLS support have been implemented using SwiftNIO. Kitura-NIO uses NIOSSL for TLS support.

SwiftNIO is a cross-platform asynchronous event-driven network application framework for rapid development of maintainable high-performance protocol servers & clients.

For example swift vapor (3+) is built on top of it as well. That's why I want to see those numbers. How do they compare

**Comment by waghanza** [comment]
Hi @shial4,

Thanks for clarification. 

As I understand `Kitura-NIO` is therefore an `async` variant of `Kitura` 

Feel free to add a   `PR` :heart:
