### ISSUE TITLE
Add a PHP network engine Swoole

### ISSUE THREAD

**Issue by hhxsv5** [the-benchmarker/web-frameworks#1305]
+ Language : PHP
+ Repo : https://github.com/swoole/swoole-src
+ Author : @matyhtf

*Build a HTTP server*
```php
$http = new Swoole\Http\Server('127.0.0.1', 5200);
$http->on('request', function (Swoole\Http\Request $request, Swoole\Http\Response $response) {
    $response->end('Hello Swoole');
});
$http->start();
```

**Comment by waghanza** [comment]
any   `PR` is welcome :heart:

**Comment by waghanza** [comment]
@hhxsv5 @stdex `swoole` is awesome, but it's not a **framework** bu more an **engine** -> a replacement for **ngin/php-fpm**, as I understand.

It could be awesome to add some variant of php frameworks here. I mean **swoole** and **nginx/php-fpm** are 2 ways of doing the same thing. 

I propose to run php frameworks in 3 maneers :
+ php-fpm/nginx
+ php-pm
+ swoole

/cc @doanguyen

**Comment by Jurigag** [comment]
Swoole is even more - it provides other servers and clients as well. Also there are MVC frameworks based on Swoole.

**Comment by waghanza** [comment]
@Jurigag sure, but `swoole` can also be used in `symfony`, see https://github.com/the-benchmarker/web-frameworks/pull/1336

I didn't mean `swoole` is yet anoter `php-fpm/nginx` alternative, but the fact is `swoole` is **NOT** a framework, but something considered as a toolkit, like [stalette](https://www.starlette.io/) in `python` world -> can be use as a framework and a toolkit for other frameworks

PS : The fact is `swoole` does not contain any router, thus could **NOT** be included here alone

**Comment by Jurigag** [comment]
Yea i guess most likely use it with fastroute or consider using some swoole framework like easyswoole or swoft.

**Comment by waghanza** [comment]
Hi @Jurigag,

This subject is very interesting. As  `swoole` (but also `php-pm) could be `php-fpm/nginx` **alternatives**, the purpose here is to have :

1. fast-route, with 2 variants (`php-fpm/nginx` /  `swoole`) and why not another
2. swoft, with 1 variant
3. symfony, with 2 variants (`php-fpm/nginx` /  `swoole`) and why not another
...

**Comment by waghanza** [comment]
This is linked to https://github.com/the-benchmarker/web-frameworks/pull/1570
