### ISSUE TITLE
Introduce asgineer

### ISSUE THREAD

**Issue by waghanza** [the-benchmarker/web-frameworks#1337]
+ Language : python
+ Repo : https://github.com/almarklein/asgineer
+ Author : @almarklein

**Comment by waghanza** [comment]
Hi @almarklein,

Would you mind to add (or consent that we add) [asgineer](https://github.com/almarklein/asgineer) in `here` ?

This project compare performance based on 3 routes :

+ `GET` `/`, **SHOULD** return a successful status code and an empt²y string
+ `GET` `/user/:id`, **SHOULD** return a successful status code and the id
+ `POST` `/user`, **SHOULD** return a successful status code and an empty string

Regards,

**Comment by almarklein** [comment]
Hi @waghanza, thanks for the reminder. It's on my todo list. But you have my consent if it takes too long for me to do it :)
