### ISSUE TITLE
Introdue nardis

### ISSUE THREAD

**Issue by waghanza** [the-benchmarker/web-frameworks#1338]
+ Language : python
+ Repo : https://github.com/yoongkang/nardis
+ Author : @yoongkang

**Comment by yoongkang** [comment]
Hi, thanks for this, but honestly Nardis isn't ready for benchmarking / general use and hasn't been worked on for a long time.

**Comment by waghanza** [comment]
ok. I'll close, feel free to re-open (or ping me) when production-ready :heart:
