### ISSUE TITLE
Please add Elixir/Erlang

### ISSUE THREAD

**Issue by danielcasler** [the-benchmarker/web-frameworks#1353]
Please add Elxir/Erlang and Phoenix to the test set:

Elixir: https://elixir-lang.org
Phoenix: https://phoenixframework.org

**Comment by waghanza** [comment]
hi @danielcasler,

This framework are `here` but **disabled**.

The only reason is a `lack` of **elixir** skills 😀

Feel free to add those frameworks :heart:

**Comment by waghanza** [comment]
Hi @chrismccord,

Would you mind to add (or consent that we add) [phoenix](https://github.com/phoenixframework/phoenix) in `here` ?

This project compare performance based on 3 routes :

+ `GET` `/`, **SHOULD** return a successful status code and an empty string
+ `GET` `/user/:id`, **SHOULD** return a successful status code and the id
+ `POST` `/user`, **SHOULD** return a successful status code and an empty string

Regards,
