### ISSUE TITLE
Introduce swifter

### ISSUE THREAD

**Issue by waghanza** [the-benchmarker/web-frameworks#1378]
+ Language : swift
+ Repo : https://github.com/httpswift/swifter
+ Author : @glock45

**Comment by waghanza** [comment]
Hi @glock45 @julien-c @Vkt0r,

Are you OK to include `swifter` in this list ?

Regards,

**Comment by Vkt0r** [comment]
@waghanza IMHO I don't see any problem, let's wait to see if @glock45 or @julien-c have the same opinion. Thanks for the addittion by the way.

**Comment by julien-c** [comment]
Sure, let's do this 👍
