### ISSUE TITLE
Introduce luminus

### ISSUE THREAD

**Issue by waghanza** [the-benchmarker/web-frameworks#1391]
+ Language : clojure
+ Repo : https://github.com/luminus-framework/luminus-template
+ Author : @yogthos

**Comment by waghanza** [comment]
Hi @yogthos,

Are you OK to include `luminus` in this list ?

Regards,

**Comment by yogthos** [comment]
Yeah that sounds great.

**Comment by whiplash** [comment]
working on this. @waghanza there's a typo on the issue title. can you fix it?
