### ISSUE TITLE
Add Swoft which is based on PHP & Swoole

### ISSUE THREAD

**Issue by javidoweb** [the-benchmarker/web-frameworks#1502]
+ Language : php
+ Repo : https://github.com/swoft-cloud/swoft
+ Author :

**Comment by waghanza** [comment]
@javidoweb Thanks, any `PR` is welcome :heart: 

I'll also try to add variants :stuck_out_tongue: (comparing `swoole` as a platform on different frameworks) on https://github.com/the-benchmarker/web-frameworks/issues/1481)

Indeed, comparing any `swoole` based **framework** with php/fpm` / `nginx` is **NOT** relevant for me

**Comment by waghanza** [comment]
Hi @stelin @huangzhhui @inhere,

Are you OK to include `swoft` in this list ?

Regards,

**Comment by inhere** [comment]
Hi @waghanza 

O(∩_∩)O~, we will be very happy if we can show more people in this list to know us.

Thank you very much recommend!

**Comment by stelin** [comment]
@waghanza 
If Swoft can join this list, That is very good!

**Comment by huangzhhui** [comment]
👍🏻 I am OK to include Swoft in the list !

**Comment by javidoweb** [comment]
Thank you so much..
But look at this. Swoft even is slower than Laravel :|
i thought Swoole could be very faster

**Comment by inhere** [comment]
Hi @waghanza 

I do not believe this result :(
How did you run the test?
Can you run it again? 😄
