### ISSUE TITLE
Introduce BlackSheep

### ISSUE THREAD

**Issue by waghanza** [the-benchmarker/web-frameworks#1505]
+ Language : python
+ Repo : https://github.com/RobertoPrevato/BlackSheep
+ Author : @RobertoPrevato

**Comment by waghanza** [comment]
Hi @RobertoPrevato,

Are you OK that we add `blacksheep` on this list ?

Regards,

**Comment by RobertoPrevato** [comment]
Hi @waghanza,
Sorry for taking so much time to answer! In these days I've been very busy with other activities and I forgot to write you back.

Yes, please feel free to add my web framework. I am [reviewing the PR](https://github.com/the-benchmarker/web-frameworks/pull/1516/commits/77988ece4df6ab124a9c70e2011ebd51f8875c96), and my only doubt is that all methods are only returning an empty string currently, so I understand the benchmark code is not complete yet?

Thank You,
Roberto

**Comment by waghanza** [comment]
Hi @RobertoPrevato,

In fact, the rules are simple (3 endpoints) @see https://github.com/the-benchmarker/web-frameworks/issues/221#issue-328459520

The code is complete on `PR`, `CI` test if each framework implement those 3 endpoints

Regards,
