### ISSUE TITLE
Flask site update

### ISSUE THREAD

**Issue by ozkansen** [the-benchmarker/web-frameworks#1528]
Hi,

Python / Flask main site changed adress https://palletsprojects.com/p/flask/

Thanks

**Comment by waghanza** [comment]
@ozkansen Thanks, good catch

FYI : This information is located in https://github.com/the-benchmarker/web-frameworks/blob/master/python/flask/config.yaml#L2

**Comment by ozkansen** [comment]
Readme.md file in line 182 and 285
this link gives https error
| `python` (`3.7`) | [flask](https://flask.pocoo.org)

thanks @waghanza , i follow your work

**Comment by waghanza** [comment]
@ozkansen I forget to mention that, you have to run `bon/make config` for `README.md` to be updated (**SHOULD** not be committed)
