### ISSUE TITLE
Ask author consent for new frameworks

### ISSUE THREAD

**Issue by waghanza** [the-benchmarker/web-frameworks#1535]
Hi @the-benchmarker/web-frameworks,

I want to ask for explicit consent of frameworks author, or any community member (that has write access) before adding a framework here.

I think this could be very valuable feature for this project and could let us create a respectful community.

Regards,

**Comment by waghanza** [comment]
Of course, any author can bring his framework here, and any PR could be argued as an explicit consent to be listed here

**Comment by waghanza** [comment]
Hi @the-benchmarker/web-frameworks,

After ~6 months of experiments on this, I might change of my mind. Asking for consent could block **frameworks** _addition_ in `here`.

It might be more interesting to ping the author (not only on github) + wait for a certain amount of time before starting `PR`.

The fact is that ping the author could be inefficient :

+ the author  might not receive any notification  (because this feature is disable, for example)
+ waiting for consent (because any oss contributor has limited spare time) could take times

any ideas ?

**Comment by OvermindDL1** [comment]
I think pinging them and waiting a little time before proceeding is fine.  If the license allows it then continue if no response, otherwise follow whatever their response is.

**Comment by waghanza** [comment]
sure, last thing is to define that we consider as a _reasonable_ amount of time

I think that waiting for something like a week could be accurate

**Comment by OvermindDL1** [comment]
I'd have probably opted for a month, but yeah on further thought a week is probably better, so the PR doesn't seem to die due to age.
