### ISSUE TITLE
Add nanoexpress

### ISSUE THREAD

**Issue by waghanza** [the-benchmarker/web-frameworks#1588]
Hi @dalisoft,

Would you mind to add (or consent that we add) [nanoexpress](https://github.com/dalisoft/nanoexpress) in `here` ?

This project compare performance based on 3 routes :

+ `GET` `/`, **SHOULD** return a successful status code and an empty string
+ `GET` `/user/:id`, **SHOULD** return a successful status code and the id
+ `POST` `/user`, **SHOULD** return a successful status code and an empty string

Regards,

**Comment by dalisoft** [comment]
Hi @waghanza.
Wow, it's would be great.
I try to make PR for matching the requirements.

Again, thanks a lot

**Comment by dalisoft** [comment]
@waghanza Please see #1590
