### ISSUE TITLE
List Filtering or Sorting

### ISSUE THREAD

**Issue by EmperiorEric** [the-benchmarker/web-frameworks#1617]
Would be nice to either have separate tables for each language or an easy way to filter the table directly without having to copy it elsewhere.

It's probably common for people to be comfortable with a language and want to see the fastest framework option specific to a language. Its definitely the most common thing I check here as.

**Comment by waghanza** [comment]
Thanks @EmperiorEric . In deed, it will be nice to have a listing / sorting feature.

However, as I have to simple solution, I prefer to keep focus on stability (making result more accurate, not run on docker ...) and I'll create a blog for this.

No the only solution is to use the CLI

**Comment by waghanza** [comment]
I close this issue since the project https://github.com/the-benchmarker/frontend is made for that
