### ISSUE TITLE
Tasks before stabilization

### ISSUE THREAD

**Issue by waghanza** [the-benchmarker/web-frameworks#1618]
Hi,

As everyone knows, this project is **NOT** stable at all (results are badly computed, no filtering, no resource consumption ...)

This meta-issue will track features requires before we can consider this project as **stable** :
+ Test against **new generation** servers https://github.com/the-benchmarker/web-frameworks/pull/1570#issuecomment-547308791
+ Adding parallelism or concurrency when possible (or `SO_REUSEPORT`)
+ Running on cloud
+ Having a blog to display results
+ Ability to sort or filter => https://github.com/the-benchmarker/web-frameworks/issues/1617
+ Document default sort option => https://github.com/the-benchmarker/web-frameworks/issues/1419
+ Labelize each frameworks to avoid confusion  => https://github.com/the-benchmarker/web-frameworks/issues/1365
+ Display resources (RAM, CPU ...) usage : https://github.com/the-benchmarker/web-frameworks/issues/31
+ Display sieger information => https://github.com/the-benchmarker/web-frameworks/issues/349

Regards,

**Comment by doanguyen** [comment]
Hi, I'm a bit flexible in schedule now, so I can work on task #2: having a blog to display results, it may also related to task #6: Display resources (RAM, CPU ...) usage

**Comment by waghanza** [comment]
Yeah, it will be awesome

The idea is to have something that could fetch `GraphQL`. My original idea was to use https://gridsome.org/ on https://www.netlify.com/, but an idea / work is very welcome

**Comment by doanguyen** [comment]
If it must include GraphQL, then we also need a backend service, and if we store on netlify we also need a Pro account (afaik).
As for comparison, Techempower bundled every result on a single JSON file  https://www.techempower.com/benchmarks/results/round18/ph.json?m=1
It really depends on the resource we have.

**Comment by waghanza** [comment]
Absolutely, we are going to make a `graphql` implementation (hosted on heroku probably).

And for the front-end hosting, I thought netlify was free of charge. I'll need to investigate / initialize repositories.

Thanks for your help

**Comment by doanguyen** [comment]
Indeed netlify is free if we just choose for the frontend. So we can use it :D.

Another solution is that we can also use Github pages, which is also static site hosting and having the advantage of a cvs.

Anyway, I'm not sure where to find the schema of each db records to query.

**Comment by waghanza** [comment]
I'll start it (because I need for https://github.com/the-benchmarker/web-frameworks/pull/1774).

The idea is to have several repositories :

+ this one
+ backend
+ frontend <- `here` is the blog, I prefer to have something more like `vuejs` or `reactjs` (because it's fun to learn) rather than a static / flat file parse by `jekyll` or something. feel free to choose what **YOU** want to _learn_
