### ISSUE TITLE
Add iotjs-express

### ISSUE THREAD

**Issue by rzr** [the-benchmarker/web-frameworks#1643]
+ Language : javascript
+ Repo : https://github.com/SamsungInternet/iotjs-express
+ Author : Philippe Coval

It was made to support IoT.js runtime but is also compatible with Node.Js

https://github.com/rzr/webthing-iotjs/wiki/IotJs

**Comment by waghanza** [comment]
Hi @rzr,

This seems awesome. 

Any `PR` is welcome :heart:

**Comment by rzr** [comment]
thx, by the way please let me know when iotjs runtime can be added to your bench suite.

Regards
