### ISSUE TITLE
Upgrade crystal to 0.30 

### ISSUE THREAD

**Issue by bajro17** [the-benchmarker/web-frameworks#1648]
Because http lib is now 30% faster I guess its so important to upgrade it

**Comment by waghanza** [comment]
Hi @bajro17,

I'm waiting for [amber](https://github.com/amberframework/amber) to be ready for `0.30.0`

Regards,

**Comment by bajro17** [comment]
Amber is updated right now before few hours :)

**Comment by waghanza** [comment]
I see. I haven't any computer access right now, but feel free to PR. It will be a pleasure to review :heart:
