### ISSUE TITLE
Add atreugo

### ISSUE THREAD

**Issue by waghanza** [the-benchmarker/web-frameworks#1653]
Hi @savsgio,

Would you mind to add (or consent that we add) [atreugo](https://github.com/savsgio/atreugo) in `here` ?

This project compare performance based on 3 routes :

+ `GET` `/`, **SHOULD** return a successful status code and an empty string
+ `GET` `/user/:id`, **SHOULD** return a successful status code and the id
+ `POST` `/user`, **SHOULD** return a successful status code and an empty string

Regards,

**Comment by savsgio** [comment]
Hi @waghanza,

Oh yes of course. Great idea 😄 

I you want and you will add it, I would like to review the PR.

**Comment by waghanza** [comment]
Sure, it will be a pleasure to ask for your review

**Comment by waghanza** [comment]
@savsgio how can I use `go modules` with `atreugo` ?

**Comment by waghanza** [comment]
@savsgio my bad, I have to use `ENV GO111MODULE=on`

**Comment by savsgio** [comment]
Since Go 1.12 go modules are activated by default.
In Go 1.11 you must set `ENV GO111MODULE=on` if you want to use it

But in previous versions, you can't use it

**Comment by savsgio** [comment]
If you use Go 1.12 don't worry about it 😄

**Comment by waghanza** [comment]
strange, then, I'm using `1.12` but I need this environment variable @see #1670

**Comment by savsgio** [comment]
Run `go get` before build

**Comment by savsgio** [comment]
Thanks! 😄
