### ISSUE TITLE
Add chaos

### ISSUE THREAD

**Issue by waghanza** [the-benchmarker/web-frameworks#1667]
Hi @florianleibert,

Would you mind to add (or consent that we add) [chaos](https://github.com/mesosphere/chaos) in `here` ?

This project compare performance based on 3 routes :

+ `GET` `/`, **SHOULD** return a successful status code and an empty string
+ `GET` `/user/:id`, **SHOULD** return a successful status code and the id
+ `POST` `/user`, **SHOULD** return a successful status code and an empty string

Regards,

/cc @mfirry

**Comment by mfirry** [comment]
`chaos` looks very much an abandoned project.

**Comment by waghanza** [comment]
last commit was made this year. why do yo say it is abandoned ?

**Comment by mfirry** [comment]
yes but if you look closer it's a commit removing `Marathon` from a list of project currently using chaos. Have a look yourself https://github.com/mesosphere/chaos/commits/master. Plus it's using a rather old version of `sbt` and `scala`.

**Comment by waghanza** [comment]
Ok. Thanks, I close this issue then
