### ISSUE TITLE
Add air

### ISSUE THREAD

**Issue by waghanza** [the-benchmarker/web-frameworks#1683]
Hi @aofei,

Would you mind to add (or consent that we add) [air](https://github.com/aofei/air) in `here` ?

This project compare performance based on 3 routes :

+ `GET` `/`, **SHOULD** return a successful status code and an empty string
+ `GET` `/user/:id`, **SHOULD** return a successful status code and the id
+ `POST` `/user`, **SHOULD** return a successful status code and an empty string

Regards,

**Comment by aofei** [comment]
Not at all. I'll send a PR soon.
