### ISSUE TITLE
Please remove nanoexpress from list

### ISSUE THREAD

**Issue by dalisoft** [the-benchmarker/web-frameworks#1707]
Related: #1588 

Please remove nanoexpress from list as not anymore will be supported and will be used only privately

**Comment by waghanza** [comment]
Hi @dalisoft,

You want to remove nanoexpress from `here` since it will not be maintained ?

Feel free to `PR`, I'll merge it

**Comment by dalisoft** [comment]
Will be maintained, just not publicly released

**Comment by waghanza** [comment]
Ah ok, no problem.

Do you think it will be re-used publicly in the future ?

`sifrr` was not internally using `nanoexpress` ?

**Comment by dalisoft** [comment]
May be re used, but not sure. 

No, i used sifrr in nanoexpress, but in last version i removed sifrr from nanoexpress

**Comment by waghanza** [comment]
ah ok

**Comment by waghanza** [comment]
Hi @dalisoft ,

I see that https://github.com/dalisoft/nanoexpress is publicly available now.

Would you mind re-enable it `here` ?

Regards,

**Comment by dalisoft** [comment]
@waghanza If you happy, yes, can you revert deletion PR? Thanks.

I decided to close source because of some bad users, but later i see some of people love my project (even e-mailed to me), so i decided open code to public.

Can we add there 2 versions, standard and Pro version?

**Comment by dalisoft** [comment]
@waghanza Sorry for delay, i added two PR which both are Free for open-source pro projects while Pro version is not free for commercial projects.

See #1982 and #1983
