### ISSUE TITLE
Invalid Link - NanoExpress!

### ISSUE THREAD

**Issue by BaseMax** [the-benchmarker/web-frameworks#1723]
Hello,

https://nanoexpress.js.org/
There isn't a GitHub Pages site here.

Best,
Max Base

**Comment by waghanza** [comment]
Hi @BaseMax,

Indeed this project has been retired on the author asking #1707 

The entry will then be removed when I update results :stuck_out_tongue: (probably at the end of this month)

Regards,

**Comment by OvermindDL1** [comment]
That's still super questionable, why would a site like that just up and vanish?!  Did it have illegal content in it or something?  o.O

**Comment by BaseMax** [comment]
Hello,

https://web.archive.org/web/*/nanoexpress.js.org

> Wayback Machine doesn't have that page archived.
Want to search for all archived pages under nanoexpress.js.org?

Best,
Max
