### ISSUE TITLE
0http (Low Server)

### ISSUE THREAD

**Issue by jesusvilla** [the-benchmarker/web-frameworks#1726]
This framework is already registered but has another way of using it, when registering with uWebSockets.js. You can check it is your documentation [Low Server](https://github.com/jkyberneees/0http#low-server).

+ Language : node (12.7)
+ Repo : https://github.com/jkyberneees/0http
+ Author : Rolando Santamaria Maso <kyberneees@gmail.com>

**Comment by waghanza** [comment]
Hi @jesusvilla,

The author of `0http` (@jkyberneees) has already suggested this idea, see https://github.com/the-benchmarker/web-frameworks/pull/1570

This is a great feature to add to this **benchmark** suite, but quite complex to implement

I'm cleaning the code base to do so

Keep in touch :heart:

**Comment by jesusvilla** [comment]
Hi. 
But there are already frameworks in the ranking that use uWebSocket: [Sifrr-server](https://sifrr.github.io/sifrr/#/./packages/server/sifrr-server/) and [Nanoexpress](https://www.npmjs.com/package/nanoexpress) (the project no longer exists). Of course, it would be ideal for node to have variants: uWebSocket, node, turbo.

**Comment by waghanza** [comment]
Yep, this is a great addition before the next release
