### ISSUE TITLE
Remove rocket

### ISSUE THREAD

**Issue by waghanza** [the-benchmarker/web-frameworks#1749]
Hi @SergioBenitez,

I'll remove  `rocket` from this list. As `rocket` requires `rust` **nightly**, I have too much maintenance to do, to keep in this list.

I'll be glad to re-introduce `rocket` when it requires a **stable** version of `rust`.

BTW, thanks for this great framework.

Regards,

**Comment by OvermindDL1** [comment]
Nightly is common though, and rocket stable is coming out "soon"© since the latest Rust version has support for proc_macro's in stable now.  Removing it would just be more work at this point.

**Comment by waghanza** [comment]
On the contrary @OvermindDL1, not using a stable version adds more maintenance (because dockerfile differs than for other frameworks)

Btw, `rocket` will be soon compiling on stable `rust` and I'll remove the removal ☺️ then ) it's on my radar).

**Comment by OvermindDL1** [comment]
> (because dockerfile differs than for other frameworks)

Can just use nightly universally as well, stable works on nightly.  In the Rust world nightly doesn't mean "unstable", rather it means "untested", and this primarily includes features that are 'incomplete' in one form or another, the big big one of these for a long time were Procedural Macro's (just stabilized), and those were the reason that a *lot* of libraries (not just rocket, but in the general rust ecosystem) required nightly.  :-)

**Comment by waghanza** [comment]
> In the Rust world nightly doesn't mean "unstable", rather it means "untested"

Yep. I do not mean that `rust` **nightly** is not good, but more that I do not want to provide data get from _untested_ languages
