### ISSUE TITLE
Need for more details about the system!

### ISSUE THREAD

**Issue by BaseMax** [the-benchmarker/web-frameworks#1752]
Hello,

I'm Max, Thank you for your great repository.

But it needs to add more details about your system and CPU.
e.g: What's brand and model and 2.5GHz - 3.5GHz?

https://github.com/the-benchmarker/web-frameworks/blob/master/README.md
@waghanza @OvermindDL1 @tbrand

Best,
Max Base

**Comment by waghanza** [comment]
Hi @BaseMax, I'll add that on the README, but as this is not a **stable** project, it will change.

**Comment by waghanza** [comment]
Actually I'm running on a `i7-8850H` with **16GB** of RAM

**Comment by BaseMax** [comment]
> Actually I'm running on a `i7-8850H` with **16GB** of RAM

PC? 12 CPU Cores?

**Comment by BaseMax** [comment]
> Hi @BaseMax, I'll add that on the README, but as this is not a **stable** project, it will change.

Thank you for your attention. 👍 

Best,
Max

**Comment by waghanza** [comment]
Of course ...

Actually, it's on my workstation on a `local` **docker** because of its flexibility. However, it is planned to run on cloud (same size vms)
