### ISSUE TITLE
Dancer2

### ISSUE THREAD

**Issue by imyaman** [the-benchmarker/web-frameworks#1756]
+ Language : perl
+ Repo : https://github.com/PerlDancer/Dancer2
+ Author : Dancer Core Developers

**Comment by waghanza** [comment]
Thans @imyaman :tada: 

This will be awesome to have some `perl` framewoks **here**

----------------------------------

Hi @sukria @ambs @veryrusty @xsawyerx,

Would you mind to add (or consent that we add) [dancer2](https://github.com/PerlDancer/Dancer2) in `here` ?

This project compare performance based on 3 routes :

+ `GET` `/`, **SHOULD** return a successful status code and an empty string
+ `GET` `/user/:id`, **SHOULD** return a successful status code and the id
+ `POST` `/user`, **SHOULD** return a successful status code and an empty string

Regards,

**Comment by xsawyerx** [comment]
I would be happy to see Dancer2 here. I don't have the time to prepare the Dockerifle. I can write the code, though:

```perl
use Dancer2;

get '/'      => sub { '' };
get '/:id'   => sub { route_parameters->{'id'} };
post '/user' => sub { '' };

__PACKAGE__->to_app;
```

That's it.

Alternatively, you can define the `get` and `post` together:

```perl
any [ 'get', 'post' ] => sub { '' };
```

If you want to speed up stuff, the following optional modules are recommended:

* Class::XSAccessor
* Crypt::URandom
* HTTP::XSHeaders
* Math::Random::ISAAC::XS
* MooX::TypeTiny
* Scope::Upper
* Type::Tiny::XS
* URL::Encode::XS

(Not sure which are relevant for the above paths, but at the very least the faster type checks and HTTP headers.)

**Comment by waghanza** [comment]
Awesome @xsawyerx. I can see many options to write the code base.

Which of it do you recommend, to base as closest as it possible to a real world application ?

**Comment by veryrusty** [comment]
This is close enough to "real world":  https://gist.github.com/veryrusty/8a462c3a94df3880cf36366908b6f02d

Feel free to amend whats in that gist to suit.
