### ISSUE TITLE
FeathersJS

### ISSUE THREAD

**Issue by mdartic** [the-benchmarker/web-frameworks#1764]
+ Language : JavaScript
+ Repo : https://github.com/feathersjs/feathers
+ Author : @daffl ?

**Comment by waghanza** [comment]
Thanks @mdartic.

**Comment by waghanza** [comment]
Hi @daffl,

Would you mind to add (or consent that we add) [feathers](https://github.com/feathersjs/feathers) in `here` ?

This project compare performance based on 3 routes :

+ `GET` `/`, **SHOULD** return a successful status code and an empty string
+ `GET` `/user/:id`, **SHOULD** return a successful status code and the id
+ `POST` `/user`, **SHOULD** return a successful status code and an empty string

Regards,

**Comment by waghanza** [comment]
consent given by @daffl by `slack`

**Comment by waghanza** [comment]
@mdartic Any `PR` will be really appreciated :heart:

**Comment by mdartic** [comment]
Ok, I'll give a try ;-)

Stay tuned

**Comment by waghanza** [comment]
@mdartic want to give a try ?

**Comment by mdartic** [comment]
Yup, didn't take time to do it, but I put it on my Todo list !

**Comment by mdartic** [comment]
@waghanza I've tried to add FeathersJS, tell me if it's the good way to do it.
