### ISSUE TITLE
Introduce spiral

### ISSUE THREAD

**Issue by waghanza** [the-benchmarker/web-frameworks#1782]
Hi @wolfy-j,

Would you mind to add (or consent that we add) [spiral](https://github.com/spiral/framework) in `here` ?

This project compare performance based on 3 routes :

+ `GET` `/`, **SHOULD** return a successful status code and an empty string
+ `GET` `/user/:id`, **SHOULD** return a successful status code and the id
+ `POST` `/user`, **SHOULD** return a successful status code and an empty string

Regards,

**Comment by wolfy-j** [comment]
You have my consent. I'll take a look tomorrow on your test setup, seems like we can reuse most of TFB code in here.
