### ISSUE TITLE
Add CherryPy framework

### ISSUE THREAD

**Issue by murilobr** [the-benchmarker/web-frameworks#1802]
+ Language : python
+ Repo : https://github.com/cherrypy/cherrypy
+ Author :

**Comment by waghanza** [comment]
Hi @webknjaz,

Would you mind to add (or consent that we add) [cherrypy](https://github.com/cherrypy/cherrypy) in `here` ?

This project compare performance based on 3 routes :

+ `GET` `/`, **SHOULD** return a successful status code and an empty string
+ `GET` `/user/:id`, **SHOULD** return a successful status code and the id
+ `POST` `/user`, **SHOULD** return a successful status code and an empty string

Regards,

**Comment by murilobr** [comment]
I would like that you add.

**Comment by webknjaz** [comment]
@waghanza I don't mind. But I'm not an original author. I'm an active maintainer, though.

@murilobr feel free to ping me for review.

**Comment by waghanza** [comment]
@webknjaz Could you ping the original author (need to have consent, or at least a non opposition)

**Comment by webknjaz** [comment]
He is no longer active in the community. But you can try emailing him @ `remi {AT} cherrypy {DOT} org`.
FWIW there's not much code in the repo that has survived from those times. It's been over a decade.

**Comment by waghanza** [comment]
@webknjaz I understand. I just want not to add any friction in `cherrypy` **community** :heart:

**Comment by Lawouach** [comment]
Indeed. Rémi will see no issue here and has left the project years ago. No need to reach out I'd say :)

**Comment by Lawouach** [comment]
Please could you stop spamming the mailing list however. There is no need for it.

**Comment by waghanza** [comment]
Oops, sorry. The web interface said there was an error, sorry for this mis-adventure.

@Lawouach No objection that we add `cherrypy` here ?

**Comment by Lawouach** [comment]
No worries. Messages are pending review when it's your first message.

I have none but @webknjaz is better suited to answer as he is a current maintainer. I was a long time ago :)

**Comment by waghanza** [comment]
@webknjaz Thanks for approval

@murilobr Any `PR` will be :heart:

**Comment by murilobr** [comment]
@waghanza I will try to do something. No time those days, but I will try.
Thanks for your effort.

**Comment by murilobr** [comment]
@webknjaz could you please check this implementation?
https://github.com/murilobr/web-frameworks/tree/cherrypy

**Comment by waghanza** [comment]
Hi @murilobr,

Could you make a `PR` ? so as we can focus on what to fix

btw, thanks for participating

**Comment by webknjaz** [comment]
I'd prefer to work with a PR view as I would be able to comment on specific lines.

**Comment by webknjaz** [comment]
P.S. Why do you use gunicorn?

**Comment by murilobr** [comment]
> P.S. Why do you use gunicorn?

Because other implementations are using it.

I will create the PR.

**Comment by webknjaz** [comment]
> Because other implementations in this project are using it.

Is it required by some policy? I'm just trying to figure out what is it being benchmarked.

**Comment by murilobr** [comment]
> > Because other implementations in this project are using it.
> 
> Is it required by some policy? I'm just trying to figure out what is it being benchmarked.

No there isn't. I think that we just have to use the most performatic implementation and I just used gunicorn because the majority of the python projects in this are using it. If you want you can change or suggest a better implementation.

**Comment by webknjaz** [comment]
There's no such thing as better or worse. But it cheats the benchmark in a way.
