### ISSUE TITLE
Sort by average should be more accurate than 50%?

### ISSUE THREAD

**Issue by lizhichao** [the-benchmarker/web-frameworks#1815]
Sort by average should be more accurate than 50%?

**Comment by waghanza** [comment]
Why ? 
Honestly, I don't have any arguments for for or against. I prioritize https://github.com/the-benchmarker/web-frameworks/pull/1578 for now, and after I'll create a custom blog with sortable table

**Comment by lizhichao** [comment]
Well, I turned it off.

**Comment by OvermindDL1** [comment]
Average for responses should statistically be closer to 99th-percentiles or even more.  An application that only returns 50% of the responses fast but crashes on the other 50% or returns in multiple seconds is not a good framework.

**Comment by waghanza** [comment]
Actually, results are sorted by 50th (my choice but somehow random).

Anything is ok for me, I only can have one sorted param ☺️

**Comment by waghanza** [comment]
@OvermindDL1 With **50th** `percentile`, I have different values. 

| | 50th percentile | Average |
| --- | --- | --- |
| | [nickel](https://nickel-org.github.io) (**0.11**) | [nickel](https://nickel-org.github.io) (**0.11**) |
| | [iron](https://ironframework.io) (**0.6**) | [iron](https://ironframework.io) (**0.6**) |
| | [swifter](https://github.com/httpswift/swifter) (**1.4**) |  [rack-routing](https://github.com/georgeu2000/rack-routing) (**0.0**) |
| | [syro](https://github.com/soveran/syro) (**3.1**) |  [flame](https://github.com/AlexWayfer/flame) (**4.18**)  |
| | [cuba](https://cuba.is) (**3.9**) | [cuba](https://cuba.is) (**3.9**) |
| | [roda](https://roda.jeremyevans.net) (**3.24**) | [hanami](https://hanamirb.org) (**1.3**) |
| | [rack-routing](https://github.com/georgeu2000/rack-routing) (**0.0**) | [syro](https://github.com/soveran/syro) (**3.1**) |
| | [flame](https://github.com/AlexWayfer/flame) (**4.18**) |  [sinatra](https://sinatrarb.com) (**2.0**) |
| | [hanami](https://hanamirb.org) (**1.3**) | [roda](https://roda.jeremyevans.net) (**3.24**) |
| | [sinatra](https://sinatrarb.com) (**2.0**) |  [grape](https://ruby-grape.org) (**1.2**)  |

With seems to be more close to the results I found on a [i7 8850 H@(https://ark.intel.com/content/www/us/en/ark/products/134899/intel-core-i7-8850h-processor-9m-cache-up-to-4-30-ghz.html) that is more close to a server CPU

I approve this :tada:

**Comment by waghanza** [comment]
@lizhichao I you want to do the modification, I'll be honoured :heart: (I'm here for any question about `crystal` or my **draft** design)

**Comment by lizhichao** [comment]
If change
Or are you going to change it

**Comment by waghanza** [comment]
I'll do it :stuck_out_tongue:
