### ISSUE TITLE
Add Phalcon

### ISSUE THREAD

**Issue by sakthisaran65** [the-benchmarker/web-frameworks#1818]
+ Language : PHP
+ Repo : https://github.com/phalcon/cphalcon
+ Author : Phalcon

**Comment by waghanza** [comment]
Hi @andresgutierrez @niden @sjinks,

Would you mind to add (or consent that we add) [phalcon](https://github.com/phalcon/cphalcon) in `here` ?

This project compare performance based on 3 routes :

+ `GET` `/`, **SHOULD** return a successful status code and an empty string
+ `GET` `/user/:id`, **SHOULD** return a successful status code and the id
+ `POST` `/user`, **SHOULD** return a successful status code and an empty string

Regards,

**Comment by niden** [comment]
@waghanza We don't mind at all. Feel free to add Phalcon here. Right now however, we are extremely busy getting ready for v4 so we would not be able to help with this task. 

After the release we will be more than happy to help.

**Comment by waghanza** [comment]
Since `phalcon` is not setupable from `pecl` (see https://github.com/phalcon/cphalcon/issues/194), it will be hard to add `phalcon` in `here`

**Comment by ruudboon** [comment]
@waghanza Is docker only for development or are you using this in productions also?
Something like this should work in a container. (I've extented from the PHP container. If you builded is from scratch you need to replace the docker-php-ext-enable.
```
# Phalcon
RUN pecl install psr && docker-php-ext-enable psr --ini-name 10-docker-php-ext-psr.ini
RUN apt-get install \
        autoconf \
        g++ \
        libpcre3-dev \
        make \
    && curl -sS -o /tmp/phalcon.tar.gz https://codeload.github.com/phalcon/cphalcon/tar.gz/v4.0.0-rc.1 \
    && cd /tmp/ \
    && tar xvzf phalcon.tar.gz \
    && cd cphalcon-4.0.0-rc.1/build \
    && ./install \
    && rm -rf cphalcon-4.0.0-rc.1\
        4.0.x \
        /tmp/* \
        /var/tmp/* \
    && docker-php-ext-enable phalcon --ini-name 20-docker-php-ext-phalcon.ini
```

**Comment by waghanza** [comment]
@ruudboon `docker` is used for **development**, perhaps in **production** also (`kubernetes` or else) but in a far future.

Ah, I see `phalcon` could be compiled inside the container, may have a huge `Dockerfile` then
