### ISSUE TITLE
Introduce yew

### ISSUE THREAD

**Issue by waghanza** [the-benchmarker/web-frameworks#1819]
Hi @DenisKolodin @hgzimmerman @jstarry,

Would you mind to add (or consent that we add) [yew](https://github.com/yewstack/yew) in `here` ?

This project compare performance based on 3 routes :

+ `GET` `/`, **SHOULD** return a successful status code and an empty string
+ `GET` `/user/:id`, **SHOULD** return a successful status code and the id
+ `POST` `/user`, **SHOULD** return a successful status code and an empty string

Regards,

**Comment by OvermindDL1** [comment]
Yew isn't a web server, it's like React or Elm or so, but written in Rust and compiled to wasm (with all the speed that entails).

**Comment by waghanza** [comment]
> Yew isn't a web server, it's like React or Elm or so,

Yes, you're right, you have a router but a **frontend** one :stuck_out_tongue: and this is not for _this_ benchmark, probably one in the future

> pinging people won't always work 

Sure, if it does not work after a while, I try other way (mail or so)

**Comment by waghanza** [comment]
Sorry for the flood, `here`
