### ISSUE TITLE
Add Plezi (Ruby)

### ISSUE THREAD

**Issue by kalicki** [the-benchmarker/web-frameworks#189]
https://github.com/boazsegev/plezi

**Comment by waghanza** [comment]
Hi @boazsegev,

Would you mind to add (or consent that we add) [plezi](https://github.com//plezi) in `here` ?

This project compare performance based on 3 routes :

+ `GET` `/`, **SHOULD** return a successful status code and an empt²y string
+ `GET` `/user/:id`, **SHOULD** return a successful status code and the id
+ `POST` `/user`, **SHOULD** return a successful status code and an empty string

Regards,

**Comment by boazsegev** [comment]
Hi @waghanza ,

I got this branch going: https://github.com/boazsegev/web-frameworks

However, I manually updated the files because I didn't seem to understand the crystal tool... will that branch fit the bill, or do you need me to do something more?

Kindly,
   Bo.

**Comment by waghanza** [comment]
Awesome, you can send a `PR` (I'll review soon)

Please, take care of having a **production-ready** code, or at least something that can be send in **production**

Regards,

**Comment by boazsegev** [comment]
@waghanza ,

The code in the PR is similar to what I would use in production, except in productions I would have models that would connect to a database and I might have templates that would render the data for the client (if I wasn't outputting a simple JSON string).

Also, Plezi adds WebSocket support, which I didn't put into the example.
