### ISSUE TITLE
Add evio

### ISSUE THREAD

**Issue by waghanza** [the-benchmarker/web-frameworks#1913]
Hi @tidwall,

Would you mind to add (or consent that we add) [evio](https://github.com/tidwall/evio) in `here` ?

This project compare performance based on 3 routes :

+ `GET` `/`, **SHOULD** return a successful status code and an empty string
+ `GET` `/user/:id`, **SHOULD** return a successful status code and the id
+ `POST` `/user`, **SHOULD** return a successful status code and an empty string

Regards,

**Comment by tidwall** [comment]
Evio isn't a web framework. It's a lower level networking library and it requires a fair amount of scafolding to build an http interface around evio.

If you are looking to add a faster web framework for Go then I recommend looking at the fasthttp package.

**Comment by waghanza** [comment]
indeed, `evio` is **NOT** a web framework (in a classical way), but it could be a part of web stack

aslo, it is already compared in https://github.com/TechEmpower/FrameworkBenchmarks/tree/master/frameworks/Go/evio

I think it could be helpful to compare with other `go` more traditional frameworks

**Comment by tidwall** [comment]
Adding evio would be like adding libuv or libev, which are both lower-level networking libraries.

It's typical to build frameworks on top of evio, in my case I use it for custom redis and protobuf streaming.

The thing with evio and performance is that it's heavily dependent on the higher layer implementation. You can make it super fast if you carefully craft an HTTP handler on top of evio.

For example, Kelly Sommers claims 20,000,000 HTTP requests/second with evio.
https://twitter.com/kellabyte/status/996435329069465601

But that implementation might be such that it's using a very fat pipelined packets and SO_REUSEPORT on static requests.

Evio ranks pretty low on the FrameworkBenchmarks "plaintext" tab. So I looked at their implementation and they are pointing their HTTP requests to a multi-loop instance of evio. Which is not optimal for the use-case of "plaintext". They could be using one single-threaded loop. 

That being said I don't necessarily think it's useful for them to have it listed at all. 

Ultimately it's up to you if you want to add evio to your benchmarks. But I worry that it's could be a bit misleading or just not useful to developers looking for a truly dedicated web framework.

Just for the record, the [valyala/fasthttp](https://github.com/valyala/fasthttp) is pretty darn good and probably what most Go developers will need for performant HTTP.

**Comment by waghanza** [comment]
ok, I think it is useful to least it `here`, at least to show what you can do web coding in `go`

but if you don't want I can understand (and respect your point of view)

btw, you're right about it can be a misleading information, we have to flag it at `low-level` library, neither full-stack  no micro framework

is it there some famework using `evio` as a drop in replacement for `net/...` in `go` ?
