### ISSUE TITLE
Add falcore

### ISSUE THREAD

**Issue by waghanza** [the-benchmarker/web-frameworks#1914]
Hi @dgrijalva,

Would you mind to add (or consent that we add) [falcore](https://github.com/ngmoco/falcore) in `here` ?

This project compare performance based on 3 routes :

+ `GET` `/`, **SHOULD** return a successful status code and an empty string
+ `GET` `/user/:id`, **SHOULD** return a successful status code and the id
+ `POST` `/user`, **SHOULD** return a successful status code and an empty string

Regards,

**Comment by waghanza** [comment]
@dgrijalva @smw1218 do you consent on such a thing ?

**Comment by smw1218** [comment]
We don't think there are any users left of falcore since nearly all of its functionality is now in the standard library. We also haven't touched it in years. If you really want to add it I have no objections though.

**Comment by waghanza** [comment]
@smw1218 You're write, the latest commit was 6 years ago, so this might be unused nowadays.

`falcore` was in https://www.techempower.com/benchmarks that's why I thought to add it `here`, but this might not be accurate

Thanks for your point of view
