### ISSUE TITLE
Add web go

### ISSUE THREAD

**Issue by waghanza** [the-benchmarker/web-frameworks#1916]
Hi @bnkamalesh,

Would you mind to add (or consent that we add) [webgo](https://github.com/bnkamalesh/webgo) in `here` ?

This project compare performance based on 3 routes :

+ `GET` `/`, **SHOULD** return a successful status code and an empty string
+ `GET` `/user/:id`, **SHOULD** return a successful status code and the id
+ `POST` `/user`, **SHOULD** return a successful status code and an empty string

Regards,

**Comment by bnkamalesh** [comment]
@waghanza sure, no problem.

**Comment by waghanza** [comment]
@bnkamalesh 

> Edit: I assume you want me to create an app with those, APIs, right?

You could, but I do not ask you to do that

This question let me flag this issue, so as I (or any member) can do later :stuck_out_tongue: 

but if you do it'll be appreciated :heart: at least for review

**Comment by bnkamalesh** [comment]
Ah sure, well I just completed it. Took some time out of my lunch break :p 

please find the PR here: https://github.com/the-benchmarker/web-frameworks/pull/1937
