### ISSUE TITLE
Add hamlet 

### ISSUE THREAD

**Issue by waghanza** [the-benchmarker/web-frameworks#1920]
Hi @vasily-kartashov,

Would you mind to add (or consent that we add) [hamlet](https://github.com/hamlet-framework) in `here` ?

This project compare performance based on 3 routes :

+ `GET` `/`, **SHOULD** return a successful status code and an empty string
+ `GET` `/user/:id`, **SHOULD** return a successful status code and the id
+ `POST` `/user`, **SHOULD** return a successful status code and an empty string

Regards,

**Comment by vasily-kartashov** [comment]
Not at all, you have my consent, go ahead and add it.
