### ISSUE TITLE
Add sw-fw-less

### ISSUE THREAD

**Issue by waghanza** [the-benchmarker/web-frameworks#1924]
Hi @luoxiaojun1992,

Would you mind to add (or consent that we add) [sw-fw-less](https://github.com/luoxiaojun1992/sw-fw-less) in `here` ?

This project compare performance based on 3 routes :

+ `GET` `/`, **SHOULD** return a successful status code and an empty string
+ `GET` `/user/:id`, **SHOULD** return a successful status code and the id
+ `POST` `/user`, **SHOULD** return a successful status code and an empty string

Regards,

**Comment by luoxiaojun1992** [comment]
ok，I agree.
