### ISSUE TITLE
Add ubiquity

### ISSUE THREAD

**Issue by waghanza** [the-benchmarker/web-frameworks#1925]
Hi @jcheron,

Would you mind to add (or consent that we add) [ubiquity](https://github.com/phpMv/ubiquity) in `here` ?

This project compare performance based on 3 routes :

+ `GET` `/`, **SHOULD** return a successful status code and an empty string
+ `GET` `/user/:id`, **SHOULD** return a successful status code and the id
+ `POST` `/user`, **SHOULD** return a successful status code and an empty string

Regards,

**Comment by jcheron** [comment]
Hi @waghanza 
No problem.
Let me know if you need any help.

**Comment by jcheron** [comment]
It's ready to go.
But I would need a special nginX configuration:
```javascript
    location /{
          rewrite ^/(.*)$ /index.php?c=$1 last;
    }
```
How can I integrate that ?

**Comment by waghanza** [comment]
no worry, I'll take care of it :heart:

**Comment by jcheron** [comment]
Okay, thanks!
And another question....
Have you thought about the possibility of testing several versions of the same framework?
In addition to its `fpm/fastcgi` version, `Ubiquity` is available for **Swoole**, **Workerman**, **PHP-PM**... And the performances are not the same.

This is also the case for **Hamlet**, **Laravel**, **Lumen** (with there **Swoole** version)...

**Comment by waghanza** [comment]
yes in  https://github.com/the-benchmarker/web-frameworks/pull/1570, there is several use cases for that :
+ `javascript`
   + [node](https://nodejs.org)
   + [deno](https://deno.land)
   + [uwebsocket](https://github.com/uNetworking/uWebSockets)
   + [turbo](https://github.com/mafintosh/turbo-http)
+ `ruby`
   + [falcon](https://github.com/socketry/falcon)
   + [iodine](https://github.com/boazsegev/iodine)
+ `python`
   + [hypercorn](https://pgjones.gitlab.io/hypercorn)
   + [daphne](https://github.com/django/daphne)
   + [uwsgi](https://uwsgi-docs.readthedocs.io)

This is the next big step in the roadmap, and I'll release

**Comment by jcheron** [comment]
It's a good thing you thought of that.
The key is to set up a flexible system that allows to add platforms, without adding a new workload each time.
Dockerisation is very practical in this case.
