### ISSUE TITLE
Add workerman

### ISSUE THREAD

**Issue by waghanza** [the-benchmarker/web-frameworks#1926]
Hi @walkor,

Would you mind to add (or consent that we add) [workerman](https://github.com/walkor/Workerman) in `here` ?

This project compare performance based on 3 routes :

+ `GET` `/`, **SHOULD** return a successful status code and an empty string
+ `GET` `/user/:id`, **SHOULD** return a successful status code and the id
+ `POST` `/user`, **SHOULD** return a successful status code and an empty string

Regards,

**Comment by walkor** [comment]
Yes. No problem.
I have sent a pull request which may be miss something, I would appreciate it if you could help me improve it.

Thank you for your ask.
