### ISSUE TITLE
Add webware

### ISSUE THREAD

**Issue by waghanza** [the-benchmarker/web-frameworks#1930]
Hi @Cito,

Would you mind to add (or consent that we add) [webware](https://github.com/Cito/w4py) in `here` ?

This project compare performance based on 3 routes :

+ `GET` `/`, **SHOULD** return a successful status code and an empty string
+ `GET` `/user/:id`, **SHOULD** return a successful status code and the id
+ `POST` `/user`, **SHOULD** return a successful status code and an empty string

Regards,

**Comment by Cito** [comment]
Hi @wanghanza. I'm currently working on a a new WSGI based Webware version for Python 3 that will be released in 1-2 months, and the old AppServer based Webware for Python 2 will be retired. I made a note to add a benchmark once it's released. I think it does not make much sense to add the legacy Webware version.

**Comment by waghanza** [comment]
Ok. Thanks. I'll track the next release then
