### ISSUE TITLE
Add weppy

### ISSUE THREAD

**Issue by waghanza** [the-benchmarker/web-frameworks#1931]
Hi @gi0baro,

Would you mind to add (or consent that we add) [weppy](https://github.com/gi0baro/weppy) in `here` ?

This project compare performance based on 3 routes :

+ `GET` `/`, **SHOULD** return a successful status code and an empty string
+ `GET` `/user/:id`, **SHOULD** return a successful status code and the id
+ `POST` `/user`, **SHOULD** return a successful status code and an empty string

Regards,

**Comment by gi0baro** [comment]
@waghanza thank you for asking, you are welcome to add it :)

**Comment by waghanza** [comment]
@gi0baro feel free to ping  me when https://github.com/emmett-framework/emmett/pull/252 will be in the next release (potentially the `2.0`)

**Comment by gi0baro** [comment]
@waghanza I’ll push a PR as soon as I have a release published
