### ISSUE TITLE
Add klein

### ISSUE THREAD

**Issue by waghanza** [the-benchmarker/web-frameworks#1932]
Hi @glyph @wsanchez @hawkowl,

Would you mind to add (or consent that we add) [klein](https://github.com/twisted/klein) in `here` ?

This project compare performance based on 3 routes :

+ `GET` `/`, **SHOULD** return a successful status code and an empty string
+ `GET` `/user/:id`, **SHOULD** return a successful status code and the id
+ `POST` `/user`, **SHOULD** return a successful status code and an empty string

Regards,

**Comment by wsanchez** [comment]
I don't think I'll have cycles to look at it any time soon, but I certainly don't object to you doing so.
