### ISSUE TITLE
Add  pyramid

### ISSUE THREAD

**Issue by waghanza** [the-benchmarker/web-frameworks#1934]
Hi @mmerickel @stevepiercy @caseman @mcdonc,

Would you mind to add (or consent that we add) [pyramid](https://github.com/Pylons/pyramid) in `here` ?

This project compare performance based on 3 routes :

+ `GET` `/`, **SHOULD** return a successful status code and an empty string
+ `GET` `/user/:id`, **SHOULD** return a successful status code and the id
+ `POST` `/user`, **SHOULD** return a successful status code and an empty string

Regards,

**Comment by stevepiercy** [comment]
You do not need consent to proceed, but thank you for asking.

**Comment by waghanza** [comment]
Yeah, sure for opensource, but it could have advantage

+ if the framework will be deprecated
+ if anything is troubling the author
+ its a kind of respect
+ ...

btw, thanks for it :heart:
