### ISSUE TITLE
Add apidaora

### ISSUE THREAD

**Issue by waghanza** [the-benchmarker/web-frameworks#1936]
Hi @dutradda,

Would you mind to add (or consent that we add) [apidora](https://github.com/dutradda/apidaora) in `here` ?

This project compare performance based on 3 routes :

+ `GET` `/`, **SHOULD** return a successful status code and an empty string
+ `GET` `/user/:id`, **SHOULD** return a successful status code and the id
+ `POST` `/user`, **SHOULD** return a successful status code and an empty string

Regards,

**Comment by dutradda** [comment]
@waghanza Thanks for reminding of apidaora!

of course we can add apidora on the benchmarker.

I will try to do it on this week

**Comment by douglasfarinelli** [comment]
@dutradda https://github.com/the-benchmarker/web-frameworks/pull/1961
