### ISSUE TITLE
Add sailsjs

### ISSUE THREAD

**Issue by waghanza** [the-benchmarker/web-frameworks#1939]
Hi @mikermcneil @rachaelshaw @sgress454 @Zolmeister,

Would you mind to add (or consent that we add) [sailsjs](https://github.com/balderdashy/sails) in `here` ?

This project compare performance based on 3 routes :

+ `GET` `/`, **SHOULD** return a successful status code and an empty string
+ `GET` `/user/:id`, **SHOULD** return a successful status code and the id
+ `POST` `/user`, **SHOULD** return a successful status code and an empty string

Regards,

**Comment by Noitidart** [comment]
+1

**Comment by applitect1** [comment]
+1

**Comment by waghanza** [comment]
I've personally no time to add `sailjs` here , but I'll gladly review any `PR` :heart:

**Comment by mdartic** [comment]
@waghanza I think I can make a PR.

I'm waiting for your comment / commits on  #2379 and making a better one for sails.
