### ISSUE TITLE
Add mars

### ISSUE THREAD

**Issue by waghanza** [the-benchmarker/web-frameworks#1957]
Hi @roblillack,

Would you mind to add (or consent that we add) [mars](https://github.com/roblillack/mars) in `here` ?

This project compare performance based on 3 routes :

+ `GET` `/`, **SHOULD** return a successful status code and an empty string
+ `GET` `/user/:id`, **SHOULD** return a successful status code and the id
+ `POST` `/user`, **SHOULD** return a successful status code and an empty string

Regards,

**Comment by roblillack** [comment]
Hey @waghanza, I'll look into it.
