### ISSUE TITLE
Cache build dependencies across builds

### ISSUE THREAD

**Issue by david-m-s** [the-benchmarker/web-frameworks#2016]
This project uses many build frameworks (node, maven, etc) which get dependencies at container build time. The dependency downloading is wasteful since they do not change across builds. Looks like travis-ci has a mechanism to cache folders across builds which could be helpful: https://docs.travis-ci.com/user/caching/

**Comment by waghanza** [comment]
Yeah, exactly. Caching between builds is ideal.
Unfortunately, this type of caching (**docker** `layers`) are not cacheable, yet, on `travis-ci`

@see https://github.com/travis-ci/travis-ci/issues/5358

**Comment by waghanza** [comment]
@david-m-s If you find a solution, feel free to re-open
