### ISSUE TITLE
fasthttp router

### ISSUE THREAD

**Issue by createconnect** [the-benchmarker/web-frameworks#2040]
+ Language : Go
+ Repo : https://github.com/fasthttp/router
+ Author : Various, repo was fork and improve.

> This repo is based on fasthttprouter and maintained by official fasthttp ecosystem team. We trying to optimize it even more and check if it works well when we update something huge in fasthttp.

Minimalistic router and Atreugo router is based on it, I love to see if any faster or similar to Atreugo.

**Comment by waghanza** [comment]
Hi @createconnect,

Thanks for your contribution.

I want to ask first @savsgio or @julienschmidt (or any other maintainer) :stuck_out_tongue: 

If no opposition to add `router` `here`, a `PR` will be very welcome :heart: 

Regards,

**Comment by savsgio** [comment]
Oh! Please. It's a pleasure for me and the fasthttp team to the router be here.

**Comment by waghanza** [comment]
I do not have time to `PR`, so any is welcome

But I'll add to my todo list
