### ISSUE TITLE
gnet server framework in Go

### ISSUE THREAD

**Issue by createconnect** [the-benchmarker/web-frameworks#2046]
+ Language : Go
+ Repo : https://github.com/panjf2000/gnet
+ Author : @panjf2000

gnet is an event-driven networking framework that is fast and small. It makes direct epoll and kqueue syscalls rather than using the standard Go net package, and works in a similar manner as netty and libuv.

The goal of this project is to create a server framework for Go that performs on par with Redis and Haproxy for packet handling.

It also use Ants which utilize lower memory than Goroutines.
https://github.com/panjf2000/ants

**Comment by waghanza** [comment]
Hi @createconnect, 

I prefer not to add `gnet` here, at least not for the moment. In deed, `gnet` is not, what we can consider as a **framework** (at least on web point of view).

We are not yet mature enough to add such a software piece.

Regards,
