### ISSUE TITLE
Did the Express.js use multi cores.!?? seems no?

### ISSUE THREAD

**Issue by javidoweb** [the-benchmarker/web-frameworks#2086]
Greetings
I checked the express app.js code . it seems that express dosnt use multi cores in your benchmark. is that true? i think some of frameworks use just single core and single thread and others no.

**Comment by waghanza** [comment]
Hi @javidoweb,

`Javascript` based frameworks run on `pm2` which can use **multicore**.

 I prefer to use **multicore**  at the lowest level, **runtime** in case of `javascript`, **language** in case of `crystal` ...

Feel free to fix anything you think I've done wrong :heart:
