### ISSUE TITLE
Remove actix

### ISSUE THREAD

**Issue by waghanza** [the-benchmarker/web-frameworks#2093]
Hi @fafhrd91,

You informed me that you do not want that `actix` could be listed `here`.

Why ?

Regards,

**Comment by fafhrd91** [comment]
validity of the project is my concern. I'd prefer to remove actix from this benchmark

**Comment by waghanza** [comment]
Can you explain why this project is not valid ?

I have quit the same methodology as https://github.com/TechEmpower/FrameworkBenchmarks

**Comment by waghanza** [comment]
you experiences could be valuable `here` :heart: 

@the-benchmarker/web-frameworks wdyt ?
