### ISSUE TITLE
Update atreugo to 10

### ISSUE THREAD

**Issue by waghanza** [the-benchmarker/web-frameworks#2131]
Hi @dependabot,

A new major version of https://github.com/savsgio/atreugo was released on the 22th november of 2019
@see https://github.com/savsgio/atreugo/releases

@dependabot-preview misses it

Regards,

**Comment by feelepxyz** [comment]
@waghanza 👋 we've recently added logs to the dashboard for the last update check, could you check what's being reported there for this dependency? https://app.dependabot.com/

**Comment by waghanza** [comment]
@feelepxyz I have
~~~
updater | INFO <job_19867677> Latest version is 9.0.1
updater | INFO <job_19867677> No update needed for github.com/savsgio/atreugo/v9 9.0.1
updater | INFO <job_19867677> Finished job processing
~~~
I do not know anything in `go` **world** but `atreugo` needs to be updated with `github.com/savsgio/atreugo/v10`
