### ISSUE TITLE
[Request] Remove nanoexpress-pro from list

### ISSUE THREAD

**Issue by dalisoft** [the-benchmarker/web-frameworks#2155]
+ Language : Node.js
+ Repo : [Here](https://github.com/dalisoft/nanoexpress/tree/pro)
+ Author : @dalisoft

We do not need to benchmark PRO version as future versions will be fast.
Deleting library from public places will be better. As well as from [npm](https://www.npmjs.com/package/nanoexpress-pro) will be deleted soon (01 March 2020)

Reason: Sell license and [this](https://github.com/the-benchmarker/web-frameworks/issues/2143)
Related issue: #2143 and [this](https://github.com/dalisoft/nanoexpress/issues/69)

**Comment by waghanza** [comment]
> as future versions will be fast.

I don't understand

However, OK for deletion

**Comment by dalisoft** [comment]
I mean will be fast like now or little faster. 
When i move project to private repo, main issue will be how this repo can access to private repo. 
Also, there only open source servers listed. 

Thanks 😊
