### ISSUE TITLE
Light-4j Java framework

### ISSUE THREAD

**Issue by ariya-mms** [the-benchmarker/web-frameworks#2180]
+ Language : Java
+ Repo : https://github.com/networknt/light-4j
+ Author :

**Comment by waghanza** [comment]
Hi @stevehu,

Would you mind to add (or consent that we add) [light-4j](https://github.com/networknt/light-4j) in `here` ?

This project compare performance based on 3 routes :

+ `GET` `/`, **SHOULD** return a successful status code and an empty string
+ `GET` `/user/:id`, **SHOULD** return a successful status code and the id
+ `POST` `/user`, **SHOULD** return a successful status code and an empty string

Regards,

**Comment by stevehu** [comment]
@ariya-mms @waghanza I would be so happy to see that light-4j is included. I would like to contribute a light-4j implementation but couldn't find the specification that defines the rules for each implementation. 

Is TLS mandatory?
Is HTTP/2 mandatory?

Also, what are the criteria to evaluate the performance? throughput? latency? memory footprint? size of the docker image?

Could anyone point me to the right document? Thanks.

**Comment by waghanza** [comment]
Hi @stevehu,

Actually the idea is to have a thin implementation, having 3 routes, like described above.

No TLS nor HTTP2 involved.

The idea is to mesure performance, which is many factors, but not only `req/s` is used

**Comment by waghanza** [comment]
@stevehu any bandwith to add `light-4j` ?

**Comment by stevehu** [comment]
@waghanza @tsuilouis from our team is going to work on the project. He has other projects at the same time, so it might take a bit longer. Thanks.

**Comment by waghanza** [comment]
@tsuilouis @stevehu any time free ?

**Comment by waghanza** [comment]
PS : the `java` based **frameworks** are using `jvm` **8**

**Comment by stevehu** [comment]
@waghanza Sorry, there are so many projects going on at the same time and the team is over-stretched.

**Comment by tsuilouis** [comment]
Hi @waghanza @stevehu, thanks for the wait. I've made a pull request for this issue; please take a look when you have time.
