### ISSUE TITLE
What triggers an update of the results in the README ?

### ISSUE THREAD

**Issue by ducdetronquito** [the-benchmarker/web-frameworks#2193]
Hi @waghanza !

I am wondering what exactly triggers an update of the results in the README ?

For example, the commit a9e169b triggered an update 3 days ago, but not the 8 after that.

Ps: Ok, I admit, I am just eager to see the results of my framework :P

**Comment by waghanza** [comment]
Hi @ducdetronquito,

There is nothing automatic in that, yet ...

The thing is that `README` is update on demand :stuck_out_tongue: either by my initiative or by any asking by any author `here`.

When https://github.com/the-benchmarker/web-frameworks/issues/1618 will be closed (this project could be considered as **stable**), the `README` will be update automatically.

If my answer is not clear enough, feel free to re-open this issue :heart:

**Comment by waghanza** [comment]
I've add this information on `README` :stuck_out_tongue: 

However, @ducdetronquito, `phoon` will not appear on `results`

I have a `segfault` using
```sh
wrk --latency -d 5s -c 500 --timeout 8 -t 8 http://172.17.0.2:3000/user/0
```

**Comment by ducdetronquito** [comment]
Thank you for the quick feedback, I will dig into it !

I will keep my eyes on #1618 : If I can help in a way I will :)

Have a nice day !

**Comment by ducdetronquito** [comment]
Hey @waghanza , sorry to bother you again.

I tried to reproduce the segfault this afternoon without success.

Do you know where can I found the entire error raised during the benchmark ?

Thanks in advance !
