### ISSUE TITLE
Rename JavaScript to Node.js

### ISSUE THREAD

**Issue by danielcasler** [the-benchmarker/web-frameworks#2200]
Stating that JavaScript is the language for Node.js applications is incorrect. JavaScript as a language does not include any features to create an HTTP server. HTTP servers are created using Node.js.

An HTTP server is invoked using JavaScript but the HTTP server functionality itself is part of Node.js.

JavaScript servers should be renamed to Node.js. **There is no version 12.13 of JavaScript.**

Perhaps a more appropriate label for the language column should be **Language/Runtime**.

Sorry for the repetition, I wanted to be clear here.

**Comment by waghanza** [comment]
Hi,

I understand you concern. 

It appears, effectively to be a mess in the `javascript` part `here`.

I want to keep the name of any folder to reflect the **language** in use, but you're write : 
using `javascript (12.3)` is not the best way.

In https://github.com/the-benchmarker/web-frameworks/pull/1570, I'll separate `runtime` from `language`.

The purpose is to have 

| Language | Runtime |
|-------|--------------|
| javascript (`6`) | node.js (12.3) |
| javascript (`6`) | deno (12.3) |

That will be clearer no ?

**Comment by waghanza** [comment]
@danielcasler the most accurate version of `javascript` (with `node.js` runtime) is probably **ES2019**
@see https://node.green/#ES2019
