### ISSUE TITLE
Add cluster results for Node.js servers

### ISSUE THREAD

**Issue by danielcasler** [the-benchmarker/web-frameworks#2201]
All Node.js servers are being run as **a single process (single thread)**. Node.js supports clustering, see https://nodejs.org/dist/latest-v13.x/docs/api/cluster.html

The Golang servers for example all use goroutines by default and will utilize all available CPU cores. The Echo server tested on my workstation uses 16 CPU cores. The Hapi.js server uses only 1 CPU core and in my own testing, handles 20,000 requests per second using **wrk**. When the same Hapi server uses the cluster module on my workstation, the requests per second increases to 170,000. 

The Node.js vanilla HTTP server handles 44,000 request per second running a single process and with cluster, over 360,000 requests per second. A stdlib Golang HTTP server handles around 370,000 requests a second using 16 CPU cores. 

Comparing a single process (single cpu core) Node.js server to a server that maxes out CPU cores is simply **a lopsided comparison.** 

Take any Golang server and execute `runtime.GOMAXPROCS(1)` and watch how the Golang server performs. This will limit the server to one CPU core.

If you're deploying a Node.js server, it would be very illogical to deploy the server and restrict it to one CPU core. For maximum performance, you would use the cluster module.

I would like to see Node.js tests being done as **a single process** as well as using the same number of process equivalent to the CPU cores used by other servers such as Golang servers. If the Golang server uses 8 CPU cores in your testing environment, then the Node.js servers should use 8 processes. 

Thanks and I hope that makes sense.

**Comment by waghanza** [comment]
Hi @danielcasler,

I understand your concern. 

However, all CPU are used for the `javascript` **frameworks** on **node**.
@see https://github.com/the-benchmarker/web-frameworks/blob/master/javascript/Dockerfile#L25

The purpose `here` is to compare **frameworks** with the same characteristics, at least cores :stuck_out_tongue: 

Let me know, if you find an issue :heart:

**Comment by danielcasler** [comment]
Hi @waghanza I strongly disagree with you. You are comparing Go servers for example against Node.js frameworks, however, Go is using the maximum number of CPU cores by default and your Node.js servers are using a single CPU core. In no way are you comparing frameworks with similar characteristics. 

I would go so far as to say the benchmarks are misleading to users. If you want compare servers "with the same characteristics", then your Go servers should use a single CPU core. 

I wrote a Medium article on this and I can tell you that the way you are comparing Node.js vs Go for example is misleading, wrong and simply portrays Node.js servers as much slower than other servers that are maxing out CPU cores, all because you refuse to use the Node.js features to run a HTTP server at it's full potential.

**Comment by thupi** [comment]
I came here to figure out exactly if node was running in its default behaviour on a single core or were running multi-threaded. 

For future readers that might visit this issue: node does run on multiple cores in this benchmark. It uses `pm2` to mange the clustering of the node app :-)
