### ISSUE TITLE
Question about the status code in the rule

### ISSUE THREAD

**Issue by greenlaw110** [the-benchmarker/web-frameworks#221]
In the rules section it says:

* GET '/' return status code 200 with empty body
* GET '/user/:id' return status code 200 with the id
* POST '/user' return status code 200 with empty body

As per HTTP standard, empty body should have a 204 response, and POST success normally indicates a create success, thus it might be good to return 201 Created.

**Comment by tbrand** [comment]
Agree but it requires a lot of efforts to fix. lol

**Comment by OvermindDL1** [comment]
Rules are good, the more detailed the better.

Like not just saying things like GET and 204 with empty body or so, but even more detailed so that the implementations remain good comparisons, things like routing must be performed a certain way or validation must be done on x-and-x, etc...

**Comment by waghanza** [comment]
@tbrand @OvermindDL1 digging for any benchmarks, and how developers use it / implement it
it appears that on _most_ **case**, there is only **1** endpoint.

What do you think about that ?

I think it **COULD** be helpful to decrease our rule set to only one endpoint implementation, for example, it could be a `GET` to `/hello/:name` to ensure  `routing` and `param parsing`.

The advantage I see :

+ simpler to implement -> to increase community
+ can focus on standard -> HTTP header, `SO_REUSEPORT` ...
+ simplify benchmarker code
+ less time to run (or we can publish more ofter with **cloud** results)
