### ISSUE TITLE
Can you try using rust's Actix framework

### ISSUE THREAD

**Issue by amoghrandhar** [the-benchmarker/web-frameworks#2217]
**Actix Framework**: https://actix.rs/

As per [this benchmark](https://www.techempower.com/benchmarks/#section=data-r18) it's titled as the fastest web-server there.

**Comment by inlet3355** [comment]
Previously, the original owner requested to remove from the benchmark:
https://github.com/the-benchmarker/web-frameworks/issues/2093

Actix and Actix-web are now manage by new project leader, @JohnTitor

**Comment by waghanza** [comment]
Thanks for reaching us. If the `actix` community wants to re-activate it `here`, it'll be a pleasure to help :heart:

**Comment by waghanza** [comment]
I close this issue, please feel free to re-open if @JohnTitor or any `actix` community member want to add it `here`

**Comment by JohnTitor** [comment]
Hi all, sorry for the delay!
I received an email and I'm fine to re-add the actix project. If you want my help, just let me know!

**Comment by waghanza** [comment]
Sorry, I've received any notification for your comments ;-)

It will be a pleasure to re-add `actix` here, feel free to `PR` @JohnTitor 

The idea is to have a very basic impl for now :

+ GET /, SHOULD return a successful status code and an empty string
+ GET /user/:id, SHOULD return a successful status code and the id
+ POST /user, SHOULD return a successful status code and an empty string

**Comment by DestyNova** [comment]
Hi! I added a small PR for a basic Actix implementation. I don't know what steps are required for the Dockerfile -- can you advise if I need to do something special with that?
