### ISSUE TITLE
how about kore ? a web framework in c !

### ISSUE THREAD

**Issue by xieyuheng** [the-benchmarker/web-frameworks#224]
https://kore.io/

**Comment by waghanza** [comment]
awesome
@OvermindDL1 will be happy :+1: 

feel free to open a `PR`

**Comment by waghanza** [comment]
@xieyuheng why ?

**Comment by xieyuheng** [comment]
oh >_<
I do not think I know enough kore to do a PR
sorry to let you down

**Comment by waghanza** [comment]
not a problem ... submit an other tool is very useful

you bring the idea to add it, not necessary meaning that you **HAVE** to add it :stuck_out_tongue: 

Somebody will do it, probably @OvermindDL1

**Comment by OvermindDL1** [comment]
Heh, if I get time it would be interesting to do it, I've never seen kore before so I'm curious.  :-)

**Comment by waghanza** [comment]
@OvermindDL1 no hurry 😊

I'll try to use github features (labels, assignee ...) to be clearer / more transparent on our work

**Comment by aichholzer** [comment]
I will try to get Kore up and into the next cycle.

**Comment by waghanza** [comment]
@aichholzer @OvermindDL1 any time to get kore up ?

**Comment by waghanza** [comment]
fixed with #430
