### ISSUE TITLE
Question: Help on TechEmpower Benchmarks?

### ISSUE THREAD

**Issue by faustinoaq** [the-benchmarker/web-frameworks#225]
Hi @tbrand @OvermindDL1 

This benchmark looks very interesting, I'm wondering if you have any suggestion on TFB implementation for crystal tests [here](https://github.com/TechEmpower/FrameworkBenchmarks/tree/master/frameworks/Crystal), Do you think we can improve current results?

BTW, we already opened some issues about Crystal performance on https://github.com/amberframework/amber/issues/273 and https://github.com/TechEmpower/FrameworkBenchmarks/issues/2960

Any related comment is welcome :)

**Comment by OvermindDL1** [comment]
Immediately I see they seem to be sharing the socket across processes, which is what really needs to be done here.

**Comment by waghanza** [comment]
Hi @faustinoaq @drujensen,

I'm looking at https://travis-ci.org/TechEmpower/FrameworkBenchmarks, I can see that there are some tests only on https://travis-ci.org/TechEmpower/FrameworkBenchmarks/jobs/388046340

I'm trying to implement a test strategy for this project, mind I ask about yours ?

Regards,

**Comment by waghanza** [comment]
@lukeed any ideas to help **tfb** ?

https://github.com/tbrand/which_is_the_fastest/issues/238

**Comment by waghanza** [comment]
@faustinoaq I think https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/frameworks/Crystal/kemal/server-postgres.cr#L116 will fail as mentioned https://github.com/kemalcr/kemal/issues/459

**Comment by waghanza** [comment]
@faustinoaq I think when we reach `stability` (at the end of the year, I hope), we could help **tfb**, and vice versa
