### ISSUE TITLE
router.cr fibers

### ISSUE THREAD

**Issue by bajro17** [the-benchmarker/web-frameworks#2258]
+ Language : Crystal Lang
+ Repo : router.cr
+ Author : @tbrand 

Is it possible to use fibers to get on speed?

**Comment by waghanza** [comment]
@stakach perhaps we will have also a good answer

**Comment by stakach** [comment]
Not sure I completely understand the question. Measure the speed of fibers or use fibers to increase speed?

Fibers are definitely being used.
Measuring the speed of a single request would be the only way to measure the fiber speed, but that will not yield reliable results.

**Comment by waghanza** [comment]
@bajro17 I'll close this issue, feel free to reopen of needed
