### ISSUE TITLE
[Python] Add japronto

### ISSUE THREAD

**Issue by DoubleDi** [the-benchmarker/web-frameworks#2263]
Would love to see this python framework in the list.

+ Language : Python 3.8
+ Repo : https://github.com/squeaky-pl/japronto
+ Author : @squeaky-pl

**Comment by waghanza** [comment]
Hi @DoubleDi,

I have removed `japronto` since their is no new development on this framework.

Moreover, I don't think this framework is available for `python` **3.8** (correct me if I'm wrong)

I'm referring to https://github.com/the-benchmarker/web-frameworks/issues/1965

Regards,

**Comment by littleforce163** [comment]
Japronto supports python 3.8
