### ISSUE TITLE
Add Blade(+java)

### ISSUE THREAD

**Issue by mcauto** [the-benchmarker/web-frameworks#2271]
+ Language : Java
+ Repo : https://github.com/lets-blade/blade
+ Author : https://github.com/biezhi

It's a lightweight framework like Python's flask.

**Comment by waghanza** [comment]
Thanks @mcauto. It is always a pleasure to have new frameworks :heart: 

This project compare performance based on 3 routes :

+ `GET` `/`, **SHOULD** return a successful status code and an empty string
+ `GET` `/user/:id`, **SHOULD** return a successful status code and the id
+ `POST` `/user`, **SHOULD** return a successful status code and an empty string

If you want to `PR` this, be my guest, but please wait for a while to see if @biezhi is not opposed :tada:

**Comment by waghanza** [comment]
@mcauto if you want you can start :tada:

**Comment by whiplash** [comment]
Working on this.
