### ISSUE TITLE
Remove raze from here

### ISSUE THREAD

**Issue by waghanza** [the-benchmarker/web-frameworks#2299]
Hi,

https://github.com/samueleaton/raze seems to be unmaintained, and not working on `crystal` **0.33**

I advocate in favor of removing this frameworks from this list.

As a consequence, CI is not working

/cc @the-benchmarker/web-frameworks @samueleaton

Regards,

PS : Feel free to give your opinion, I'll act depending on it on 6 of march

**Comment by OvermindDL1** [comment]
If it's unmaintained then it shouldn't be used in any case so I'd opt for removing it.
