### ISSUE TITLE
Remove plezi

### ISSUE THREAD

**Issue by waghanza** [the-benchmarker/web-frameworks#2303]
Hi @boazsegev,

You notice me in https://github.com/the-benchmarker/web-frameworks/pull/2288#issuecomment-591081883 that you want to remove `plezi` from `here`

As you want :heart: 

BTW, thanks for your advices and you clear answers

Regards,

**Comment by boazsegev** [comment]
Hi @waghanza ,

Thank you for a wonderful project and for keeping me in the loop.

Yes, I believe Plezi is too much of a side project and will only clutter this repo (and it's also slowly being retired and replaced by C extensions in the iodine Ruby server).

Maybe in the future I'll return to add the facil.io C framework that powers iodine (or iodine itself). For now, I doubt they are used often enough to matter.

Kindly,
   Bo.

**Comment by waghanza** [comment]
It will always be a pleasure to have any frameworks, feel free to `PR` when you want to add facil.io :heart:
