### ISSUE TITLE
Fix spiral

### ISSUE THREAD

**Issue by waghanza** [the-benchmarker/web-frameworks#2309]
Hi,

`spiral` is failing
https://travis-ci.com/the-benchmarker/web-frameworks/jobs/291230634

@wolfy-j Do you mind taking a look ?

Regards,

**Comment by wolfy-j** [comment]
I see that benchmark script is failing as for few other frameworks. Are you sure it’s on framework end?

**Comment by waghanza** [comment]
Yep see the link above

`raze` also is failing, but an issue is opened for its case

Some frameworks has failed, but I am dealing with them separately

**Comment by waghanza** [comment]
The fact is **alpine** is use to compile and run, and then the `./spiral` binary is failing (inside the container)

**Comment by wolfy-j** [comment]
Oh, I might see the reason.

**Comment by 48d90782** [comment]
@waghanza @wolfy-j Turn off CGO for all builds. Will upload new binaries in a moment. Thanks for feedback.

**Comment by 48d90782** [comment]
@waghanza @wolfy-j Done, we're good to go. Binaries updated.

**Comment by waghanza** [comment]
@wolfy-j @48d90782 seems to be okay
https://travis-ci.com/the-benchmarker/web-frameworks/jobs/291230634
