### ISSUE TITLE
multiple benchmarking using different tools to compare the results

### ISSUE THREAD

**Issue by sakthisaran65** [the-benchmarker/web-frameworks#2346]
Please add wrk2 as a benchmark tool (so we can compare wrk vs wrk2)
https://github.com/giltene/wrk2

or any one in the below list
https://github.com/denji/awesome-http-benchmark

**Comment by waghanza** [comment]
Hi @sakthisaran65,

I would love to compare any of tool of the awesome link above.

However, please consider two things :
+ `wrk` is the most common used
+ it is out of a question to use multiple sieger to display the same results (at least one sieging at max throughput and one at constant throughput is OK)

Regards,
