### ISSUE TITLE
Frameworks

### ISSUE THREAD

**Issue by Kabingeran** [the-benchmarker/web-frameworks#2353]
Hi! Is it appropriate to compare the response speed of frameworks with different functionality? I think no.

**Comment by waghanza** [comment]
Hi @Kabingeran,

Could you please develop your opinion ? 

Regards,

**Comment by Kabingeran** [comment]
You are comparing frameworks with different functionality. Naturally, frameworks with more functionality will be slower. It seems to me that one cannot compare everything with everything. You can only compare frameworks with similar functionality. Maybe you need to make categories of frameworks. For example, yii, Symphony, Laravel, etc

**Comment by sakthisaran65** [comment]
Yes, I Accept.But what you have mentioned above is only for PHP. Between languages you are out of comparison to categorize, cause they all are different and unique in their own way.  When comes bench-marking, you should let it run all them together as one. I suggest average it by different test cases disregards of threading and concurrency.

**Comment by waghanza** [comment]
@Kabingeran 

> You are comparing frameworks with different functionality. 

We are **NOT** comparing, but doing some benchmark => measuring some indicators (actually performances ones)

> Maybe you need to make categories of frameworks. 

Sure, but I'm focused on other features, but it will come. Feel free to help :heart: Possibly, by categorizing each frameworks `here`

@sakthisaran65 not opposed ... I'm more focused on making a decentralized tool, I mean having various parts, mostly a (GraphQL) api to store/query the results and a frontend to display various graphical representations

**Comment by ITwrx** [comment]
Like @Kabingeran i think the frameworks should be divided up in to three or four categories based on rough feature set and/or framework focus: 
http servers, 
http servers with routing, (or combine the previous two categories), 
micro-frameworks,
and full featured frameworks.  

The results roughly break down along these lines anyway, but you have to know what all of these are to know that, which is less than ideal. 

We can see that the fastest are the http servers, then http servers with routing, then micro service/api focused micro-frameworks, then the whole hog/kitchen sink frameworks bring up the rear. :) 

There are frameworks that perform better than their category, but they don't get the ranking they deserve when surrounded by lighter weight alternatives. There may be some that perform worse than their category. It would be nice to see how they all perform in their appropriate "weight classes" by default.
