### ISSUE TITLE
PHP Framework：ThinkPHP

### ISSUE THREAD

**Issue by Haiwar** [the-benchmarker/web-frameworks#2377]
PHP Framework：ThinkPHP

**Comment by waghanza** [comment]
@Haiwar Could you provide any URL ?

**Comment by waghanza** [comment]
Hi @liu21st @yunwuxin @kinosang @vus520,

Would you mind to add (or consent that we add) [ThinkPHP](https://github.com/top-think/framework) in `here` ?

This project compare performance based on 3 routes :

+ `GET` `/`, **SHOULD** return a successful status code and an empty string
+ `GET` `/user/:id`, **SHOULD** return a successful status code and the id
+ `POST` `/user`, **SHOULD** return a successful status code and an empty string

Regards,

**Comment by Haiwar** [comment]
@waghanza yes，That's it. 😂thinks

**Comment by waghanza** [comment]
@Haiwar I prefer to wait to have consent before implementing this :stuck_out_tongue:

**Comment by Haiwar** [comment]
@waghanza ok😁

**Comment by waghanza** [comment]
@Haiwar feel free to go :heart:

**Comment by Haiwar** [comment]
> @Haiwar feel free to go ❤️

🤞🤞

**Comment by botsphp** [comment]
@waghanza   Of course, please feel free as you wish.

i hope it's not too late that i saw this email.
and i can create a demo project for you considering we're more familiar.

**Comment by vus520** [comment]
@waghanza 

Of course, please feel free as you wish.

i hope it's not too late that i saw this email.
and i can create a demo project for you considering we're more familiar
