### ISSUE TITLE
Swoole (php), Roadrunner (php)

### ISSUE THREAD

**Issue by Kabingeran** [the-benchmarker/web-frameworks#2392]
Please add the comparison Swoole (php) https://www.swoole.co.uk/, Roadrunner (php) https://roadrunner.dev/

**Comment by waghanza** [comment]
`phalcon` is already `here`. I am aware that `swoole` and `roadrunner` are new, so interesting to challenge ... but I privilege https://github.com/the-benchmarker/web-frameworks/pull/1570

The idea behind the above `PR` is to have, somewhat classical  **frameworks** (in `php`, **symfony**, **laravel**, ...), running on those engines. There is some solutions for that, for example https://www.swoole.co.uk/article/symfony-swoole in **symfony**, but it requires a lot of works ... feel free to open any `PR` that enable it :heart: 

However, there is `hyperf`, `swoft` ... for **swoole** and `spiral` for **roadrunner**

**Comment by waghanza** [comment]
Please open

**Comment by Kabingeran** [comment]
I did not close
