### ISSUE TITLE
Add rack-app

### ISSUE THREAD

**Issue by waghanza** [the-benchmarker/web-frameworks#2399]
Hi @thilonel @adamluzsi,

Would you mind to add (or consent that we add) [rack-app](https://github.com/rack-app/rack-app) in `here` ?

This project compare performance based on 3 routes :

+ `GET` `/`, **SHOULD** return a successful status code and an empty string
+ `GET` `/user/:id`, **SHOULD** return a successful status code and the id
+ `POST` `/user`, **SHOULD** return a successful status code and an empty string

Regards,

**Comment by adamluzsi** [comment]
Hi @waghanza , please feel free to add rack-app to your repo for to create a benchmark.
Be aware, that there is currently a regression in the framework that cause performance problems, and I plan to fix it.

**Comment by waghanza** [comment]
Ok thanks.

There is a bot `here` that keeps `ruby` **frameworks** up-to date :heart:
