### ISSUE TITLE
Fixing version in rust

### ISSUE THREAD

**Issue by waghanza** [the-benchmarker/web-frameworks#242]
Hi,

In `Cargo.toml` for `actix-web`, we have 
~~~toml
[dependencies]
tokio-io = "=0.1.5"
tokio-core = "=0.1.12"
actix = "0.5"
actix-web = "0.6"
~~~

However, I can see that the build process `cargo build --release` use `actix-web` **0.6.12**.

@fafhrd91 How can I fix versions ?

Regards,

**Comment by fafhrd91** [comment]
this is expected. `=0.1.12` means exact version, while `0.6` any `0.6.x` version. that exactly was my intention.

**Comment by waghanza** [comment]
ok, thanks

I prefer using `=0.6.12` instead (so web can display version in results)

**Comment by fafhrd91** [comment]
ok.

you can also use Cargo.lock, it locks all dependencies and always uses same versions

**Comment by waghanza** [comment]
Good idea, my first contribution to this **project** was to _remove_ `lock` files, but i's seems to be a bad solution ...

We need to find the most accurate way on how to display versions of each **frameworks** on result (I don't think `lock` files are **standards** on each languages)

**Comment by OvermindDL1** [comment]
> Good idea, my first contribution to this project was to remove lock files, but i's seems to be a bad solution ...

Removing lock files is very *very* bad for a lot of languages, including rust, elixir, etc...  Even the C++ project bakes-in the lock versioning via the huntergate module.

> I don't think lock files are standards on each languages

Heh, absolutely not yeah, even many languages have systems with different lock file formats (C++, node, etc...)...  ^.^;

**Comment by waghanza** [comment]
so, I think that in order to display version used in results (version of each frameworks) :
+ we **SHOULD** use fixed version (or at least version specification allowing only patch level `.z` update)
+ we **COULD** use `lock` files

**Comment by OvermindDL1** [comment]
Might be good to require a shell script for each framework that just returns the version information of everything it depends on, 1-line per dependency, version first followed by name or so?  That way a project could do something as simple as just `echo` the information out, or `grep`/`sed` information out of a lock file, or etc...

**Comment by OvermindDL1** [comment]
Or add a command to the relevant build systems, like for C++ you have to run cmake to get the version regardless (which is why a shell script to do that part would be useful).

**Comment by waghanza** [comment]
@OvermindDL1 I think of a `yaml` file referencing each frameworks and versions ;-)

Actually, we have to maintain 
+ Makefile
+ neph.yml
+ tools/src/benchmarker.cr
