### ISSUE TITLE
add Oat++ framework

### ISSUE THREAD

**Issue by abufaeys** [the-benchmarker/web-frameworks#2426]
please add  Oat++ framework
site : https://oatpp.io/

**Comment by lganzzzo** [comment]
Hey @abufaeys ,
Thanks for creating this issue!

Please note that it duplicates https://github.com/the-benchmarker/web-frameworks/issues/659 so feel free to follow the original issue.

Regards,
Leonid

**Comment by KaungZawHtet** [comment]
I don't know much about benchmarking api but here is some quick info I want to share when fiddling with oatpp. I hope this is useful in ur some cases. At least, u can calculate an approximation number on paper by this info.

 **c++ compiler option**: default
**My machine** : MacBook Pro (Retina, 15-inch, Late 2013)
**CPU** : 2 GHz Quad-Core Intel Core i7
**RAM** : 8 GB 1600 MHz DDR3

**The code (just hello world)** :

` 
#include "oatpp/web/server/HttpConnectionHandler.hpp"

#include "oatpp/network/server/Server.hpp"
#include "oatpp/network/server/SimpleTCPConnectionProvider.hpp"

/**
 * Custom Request Handler
 */
class Handler : public oatpp::web::server::HttpRequestHandler {
public:

    /**
     * Handle incoming request and return outgoing response.
     */
    std::shared_ptr<OutgoingResponse> handle(const std::shared_ptr<IncomingRequest>& request) override {
        return ResponseFactory::createResponse(Status::CODE_200, "Hello World!");
    }

};
void run() {

    /* Create Router for HTTP requests routing */
    auto router = oatpp::web::server::HttpRouter::createShared();

    /* Route GET - "/hello" requests to Handler */
    router->route("GET", "/helloworld", std::make_shared<Handler>());

    /* Create HTTP connection handler with router */
    auto connectionHandler = oatpp::web::server::HttpConnectionHandler::createShared(router);

    /* Create TCP connection provider */
    auto connectionProvider = oatpp::network::server::SimpleTCPConnectionProvider::createShared(8000 /* port */);

    /* Create server which takes provided TCP connections and passes them to HTTP connection handler */
    oatpp::network::server::Server server(connectionProvider, connectionHandler);

    /* Priny info about server port */
    OATPP_LOGI("MyApp", "Server running on port %s", connectionProvider->getProperty("port").getData());

    /* Run server */
    server.run();
}

int main() {

    /* Init oatpp Environment */
    oatpp::base::Environment::init();

    /* Run App */
    run();

    /* Destroy oatpp Environment */
    oatpp::base::Environment::destroy();

    return 0;

}
`

**64 connections** :
**cmd** : ` wrk -t8 -c64 -d15s http://127.0.0.1:8000/helloworld`
**result** : 
`
Running 15s test @ http://127.0.0.1:8000/helloworld
  8 threads and 64 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   798.49us    0.95ms  27.35ms   97.44%
    Req/Sec    10.96k     1.53k   14.01k    86.58%
  1309182 requests in 15.01s, 119.86MB read
Requests/sec:  87195.78
Transfer/sec:      7.98MB
`

**256 connections** :
**cmd** : `wrk -t8 -c256 -d15s http://127.0.0.1:8000/helloworld`
**result**: 
`
Running 15s test @ http://127.0.0.1:8000/helloworld
  8 threads and 256 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     3.31ms    4.74ms 167.07ms   99.21%
    Req/Sec    10.42k     1.46k   26.38k    88.49%
  1244184 requests in 15.07s, 113.91MB read
  Socket errors: connect 0, read 121, write 0, timeout 0
Requests/sec:  82537.73
Transfer/sec:      7.56MB
`

**512 connections** :
**cmd** : `wrk -t8 -c512 -d15s http://127.0.0.1:8000/helloworld`
**result**:
`
Running 15s test @ http://127.0.0.1:8000/helloworld
  8 threads and 512 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     5.39ms    1.95ms  76.52ms   84.70%
    Req/Sec    10.74k     1.21k   13.78k    85.08%
  1283500 requests in 15.03s, 117.51MB read
  Socket errors: connect 0, read 484, write 0, timeout 0
Requests/sec:  85401.65
Transfer/sec:      7.82MB
`
