### ISSUE TITLE
Add hyper

### ISSUE THREAD

**Issue by cctse** [the-benchmarker/web-frameworks#2430]
+ Language : python
+ Repo : https://github.com/vibora-io/vibora
+ Author :

+ Language : rust
+ Repo :https://github.com/hyperium/hyper
+ Author :

I'm also curious why benchmark on [techempower](https://github.com/TechEmpower/FrameworkBenchmarks) is so different

**Comment by waghanza** [comment]
Hi @cctse ,

Thanks for you idea :tada: 

However, It could be better to separate those subjects :

+ Introducing https://github.com/vibora-io/vibora 
   + Simple answer : no
   + Long answer
      + It was removed https://github.com/the-benchmarker/web-frameworks/issues/1744
      + It will be a pleasure to re-introduce when it will be ready
 + Introducing https://github.com/hyperium/hyper
    + OK
    + I'm not going to add it personally, since I'm workin on https://github.com/the-benchmarker/web-frameworks/pull/2411
    + Feel free to add :heart:

**Comment by cctse** [comment]
@waghanza  I'm sorry for my  laziness.This is a great work, thank you.  Vibora haven't change for 2 years, It could have been abandoned.

**Comment by waghanza** [comment]
@cctse nop, `vibora` is not abandoned :stuck_out_tongue: I'm sure @frnkvieira will add it when complete ... still have to wait tho

Feel free to add `hyper` :heart:

**Comment by saahithyan** [comment]
if possible could someone add `actix-core` of `rust` and `h20` of `C`.
These are the at the top [techempower](https://www.techempower.com/benchmarks/)

**Comment by waghanza** [comment]
Hi @saahithyan ,

I'm not sure this kind of implementation (https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/frameworks/Rust/actix/src/main_platform.rs) is what we are trying to achieve `here`, at least not **yet**.


Btw, let's discuss this an other issue, if you mind

**Comment by whiplash** [comment]
From hyper [README](https://github.com/hyperium/hyper/blob/master/README.md#low-level)

> If you are looking for a convenient HTTP server, then you may wish to consider warp.

I guess this can be closed. 

I'll have a look at [warp](https://github.com/seanmonstar/warp) though.

**Comment by waghanza** [comment]
Thanks @whiplash :tada: 

You're right,  `hyper` **SHOULD NOT** be `here` (out of the scope)
