### ISSUE TITLE
What is the command of wrk? 

### ISSUE THREAD

**Issue by sy-records** [the-benchmarker/web-frameworks#2435]
Hello，@waghanza
Can you tell me what `wrk` command is used in this project?
Is that right?
```bash
wrk -H Connection: keep-alive -d 5s -c 8 --timeout 8 -t 8 http://127.0.0.1:3000
```

**Comment by waghanza** [comment]
Hi @sy-records ,

The command in use is

~~~sh
wrk --duration 15s --connections 64 --timeout 8 --threads 8  --latency http://127.0.0.1:3000
~~~

However, please not that :

+ A `lua` script could be used (when URL is a `POST`)
+ Concurrency is dynamic
+ Please note that I use the same methodology as **techempower**
   + 5-second primer at 8 client-concurrency to verify that the server is in fact running. 
   + Run a 15-second warmup at 256 client-concurrency to allow lazy-initialization
   + Run a 15-second captured test for each of the concurrency levels 
      + 64
      + 256
      + 512
      + 1024
      + 2048

I close this issue, feel free to re-open if you have more questions :heart:

**Comment by sy-records** [comment]
thanks.
