### ISSUE TITLE
Add Iris Go

### ISSUE THREAD

**Issue by leonardomirandaDev** [the-benchmarker/web-frameworks#2442]
+ Language : Go
+ Repo : https://github.com/kataras/iris
+ Author : kataras

**Comment by waghanza** [comment]
Hi @leonardomirandaDev,

Thanks for your proposal. However, there is an history track about `iris`
@see https://github.com/the-benchmarker/web-frameworks/issues/1129 and https://github.com/the-benchmarker/web-frameworks/issues/1158

I will **NOT** re-introduce `iris` here, the decision has been taken as a community :heart: 

There is also https://github.com/the-benchmarker/web-frameworks/issues/1138

**Comment by leonardomirandaDev** [comment]
Thanks for answering me. I didn't know these problems.
