### ISSUE TITLE
Performance results publish in static HTML page

### ISSUE THREAD

**Issue by proyb6** [the-benchmarker/web-frameworks#2443]
Putting entire web framework's numbers on Readme page too frequently is hard to read.

What do you think if publishing on static page and add additional column ```Non-2xx or 3xx responses``` could work?

**Comment by waghanza** [comment]
sure @proyb6, having a long `README` is hard to read

but I have other plans to enhance readability -> having a dedicated website to display this

@ohler55 is working on a `GraphQL` api, so we can also create a dedicated website (with `vue`)

**Comment by proyb6** [comment]
If I may add my thought require no frontend framework, just Grid CSS and Flexbox along with pure JavaScript would do or non-JS

**Comment by waghanza** [comment]
I think building something more  complex could be useful. We've started https://github.com/the-benchmarker/frontend

Feel free to give a ha be :heart: I'm personally focus on https://github.com/the-benchmarker/web-frameworks/pull/2411
