### ISSUE TITLE
Introduce shivneri

### ISSUE THREAD

**Issue by waghanza** [the-benchmarker/web-frameworks#2463]
Hi @ujjwalguptaofficial,

Would you mind to add (or consent that we add) [shivneri](https://github.com/ujjwalguptaofficial/shivneri) in `here` ?

This project compare performance based on 3 routes :

+ `GET` `/`, **SHOULD** return a successful status code and an empty string
+ `GET` `/user/:id`, **SHOULD** return a successful status code and the id
+ `POST` `/user`, **SHOULD** return a successful status code and an empty string

Regards,

**Comment by ujjwalguptaofficial** [comment]
@waghanza yes you can add, that would be great :).

Should i send a PR ?

**Comment by ujjwalguptaofficial** [comment]
Here is PR - https://github.com/the-benchmarker/web-frameworks/pull/2464
