### ISSUE TITLE
Add Siler+Swoole

### ISSUE THREAD

**Issue by RicardoSette** [the-benchmarker/web-frameworks#2492]
Hi @waghanza,

add Siler+Swoole in tests

+ Language : PHP
+ Repo : https://github.com/leocavalcante/siler
+ Author : @leocavalcante
+ Fork : https://github.com/RicardoSette/web-frameworks/tree/master/php/siler-swoole

**Comment by waghanza** [comment]
@RicardoSette @leocavalcante fel free to contribute 

This project compare performance based on 3 routes :

+ `GET` `/`, **SHOULD** return a successful status code and an empty string
+ `GET` `/user/:id`, **SHOULD** return a successful status code and the id
+ `POST` `/user`, **SHOULD** return a successful status code and an empty string

**Comment by RicardoSette** [comment]
Hi @waghanza, 

Here #2598
