### ISSUE TITLE
Add ice

### ISSUE THREAD

**Issue by waghanza** [the-benchmarker/web-frameworks#2504]
Hi @mruz ,

Would you mind to add (or consent that we add) [ice](https://www.iceframework.org/
) in `here` ?

This project compare performance based on 3 routes :

+ `GET` `/`, **SHOULD** return a successful status code and an empty string
+ `GET` `/user/:id`, **SHOULD** return a successful status code and the id
+ `POST` `/user`, **SHOULD** return a successful status code and an empty string

Regards,

**Comment by mruz** [comment]
Sure, I'll prepare a PR.
