### ISSUE TITLE
Add tango

### ISSUE THREAD

**Issue by waghanza** [the-benchmarker/web-frameworks#2506]
Hi @lunny ,

Would you mind to add (or consent that we add) [tango](https://gitea.com/lunny/tango
) in `here` ?

This project compare performance based on 3 routes :

+ `GET` `/`, **SHOULD** return a successful status code and an empty string
+ `GET` `/user/:id`, **SHOULD** return a successful status code and the id
+ `POST` `/user`, **SHOULD** return a successful status code and an empty string

Regards,

**Comment by lunny** [comment]
@waghanza Please feel free to add a performance compare about [tango](https://gitea.com/lunny/tango`. Thanks!
