### ISSUE TITLE
Add jobby

### ISSUE THREAD

**Issue by waghanza** [the-benchmarker/web-frameworks#2507]
Hi @jknack ,

Would you mind to add (or consent that we add) [jooby](https://github.com/jooby-project/jooby) in `here` ?

This project compare performance based on 3 routes :

+ `GET` `/`, **SHOULD** return a successful status code and an empty string
+ `GET` `/user/:id`, **SHOULD** return a successful status code and the id
+ `POST` `/user`, **SHOULD** return a successful status code and an empty string

Regards,

**Comment by jknack** [comment]
Sure, happy to see jooby is included.

**Comment by waghanza** [comment]
Should I make a `PR` ? Or do you want to take care of it ?

**Comment by jknack** [comment]
Will do. Thanks
