### ISSUE TITLE
Migrate as an org

### ISSUE THREAD

**Issue by waghanza** [the-benchmarker/web-frameworks#252]
Hi @tbrand,

Some services (which are in the marketplace) are more usable (due to github permissions) to use / enable on some group project.

For example, using https://dependabot.com (to manage dependency) **COULD** only be done either on my fork or on a group project.

Do you mind if I create a group in order to migrate this project ?

It will be very helpful for **maintainers**.

Regards,

**Comment by tbrand** [comment]
OK, I accept the migration.

**Comment by waghanza** [comment]
Then we have to find a name

For me, the **main** idea behind that `performance` battle :stuck_out_tongue_closed_eyes: is some king of promotion, so name could be about that

**Comment by tbrand** [comment]
Specifically?

**Comment by waghanza** [comment]
late take some time to think about that ;-)

at least I would have some ideas in 2 days ;-)

@OvermindDL1 any ideas ?

**Comment by tbrand** [comment]
How about `which-is`/`the-fastest`? lol

**Comment by OvermindDL1** [comment]
Hah, I like @tbrand's suggestion, leaves it open for more repo's with more tests later too.  ^.^

**Comment by waghanza** [comment]
So why not a more **generalistic** word like `agon`, then it could be `agon`/`backend`

https://en.wikipedia.org/wiki/Agon

**Comment by waghanza** [comment]
@tbrand @OvermindDL1 why not 
[agon](https://en.wikipedia.org/wiki/Agon)/[actium](https://en.wikipedia.org/wiki/Battle_of_Actium)
for this repository, but with a focus on performance for **backend** apps (web)

leaves open for other benchmarks with a focus on performance for **fontend** apps (`node` things ...) or why not asking @lukeed and @aichholzer to join this adventure :heart:

**Comment by tbrand** [comment]
@waghanza Sorry I can't agree the name.
For me, who don't have enolugh vocabulary, dont' understand what it means without googling.
`which_is_the_fastest` is verfy simple, understandable and catchy for every users on Github.
Even we drop the name of `which_is_the_fastest`, it have to be `simple, understandable and catchy` at least.

**Comment by waghanza** [comment]
@tbrand `which_is_the_fastest` is surely understandable, by whom have some technical skills
what I mean is that :

+ `fastest` **IS** subjective (depending on use case) -> a telecommunication app and a web app are not considered **fastest** the same way
+ `is` **COULD** be restraining for some people, according that anyone has enough knowledge to say that he has **the** solution

In short :
+ agon mean battle in ancient greek
+ actium as the name of decisive battle between greek and roman, https://en.wikipedia.org/wiki/Battle_of_Actium

**Comment by tbrand** [comment]
I don't say we have to keep the name(`which_is_the_fastest`) but I just disagree with the suggestion.
So pointing out the wrongs of the name mean nothing here. (I would like to put `which is the fastest` on somewhere since I attached it personally. 😃)

How about naming org as `which_is_the_fastest`? Repository names are whatever you want.
Like `which_is_the_fastest/web_server`.

**Comment by OvermindDL1** [comment]
You might also want a `which_is_the_highest_throughput` or `which_is_the_most_concurrent` or something, that's why I like the `which_is` personally.

**Comment by tbrand** [comment]
Uh huh.

**Comment by waghanza** [comment]
like your shared ideas and the `concern` about non-executive word

I personally find `which` is a little bit too restraining for me

**Comment by tbrand** [comment]
That's already taken.

**Comment by waghanza** [comment]
I see, `which` **and** `concern` are already taken, yo have to be imaginative

**Comment by tbrand** [comment]
I already took `which-is` and `which-is-the-fastest` org since they are candidates. `which` is not taken by me anyway.

@OvermindDL1 Specifically?

**Comment by OvermindDL1** [comment]
> @OvermindDL1 Specifically?

Hmm?  About what?

**Comment by aichholzer** [comment]
I have this organisation https://github.com/TheBenchmarker
Would be happy to grant you guys access to it so you can use it for this project. Trying to keep it nice and generic.

**Comment by tbrand** [comment]
`strugglerr` is not directory meaning the org I think. Then what is the repos will be?
We'll let people know what we are doing at there by org and repo name.
You might guess what I was doing on this repository `which_is_the_fastest` right?

**Comment by waghanza** [comment]
@tbrand in fact the idea behind creating an org, is also to create a **community**

The  name `struggler-io` (to match a domain name stugglerr.io) will be to describe a **community** struggling for performance :stuck_out_tongue:

**Comment by aichholzer** [comment]
I fail to understand how `TheBenchmarker` can be uncomfortable. This project is about benchmarking something, in this case HTTP frameworks. I do not think this project has anything to do with performance struggles.

Why would I look at benchmarks if I am having problems with my performance?
And using your words; `create a community` -Yes, a community around creating good and trustworthy benchmarks.

Anyway...

**Comment by waghanza** [comment]
@aichholzer My suggestion was not about `benchmarker`, but about using `the` => for me `the` is too implying a supperior knowledge (very diffucult to be clear, so I hope you'd understand)
I like following the `amber` philosophy => https://github.com/amberframework/amber/blob/master/.github/AMBER_PHILOSOPHY.md 

I follow your second point. The project is **NOT** about solving any performance issue ;-)

Yes, the decision will be long to take, but it's for the best :stuck_out_tongue:

**Comment by aichholzer** [comment]
To me `The` implies a reference, like the person who does benchmarks. When you are sick you go to `The doctor`, when your car is broken you go to `The mechanic`... When you need to get solid information about a benchmark, you go to `The benchmarker`.

Anyway, my two cents... Checking out.

**Comment by waghanza** [comment]
@aichholzer Personally, when I get sick, I go ot `a` **doctor** (at least any doctor available) :stuck_out_tongue:

**Comment by paulcsmith** [comment]
I think the repo name of “which_is_the_fastest” is super clear and effective. I think keeping it as-is is a great idea. For the org name, I’m not sure but I think TheBenchmarker makes a lot of sense

Sure “The” implies it’s the only one but I think people know that’s just a name and isn’t really the only benchmarker :)

**Comment by waghanza** [comment]
@aichholzer ok for the name of the group

We have then to choose the projet name

I suggest using a name related to `backend`

**Comment by waghanza** [comment]
Sure. 

@tbrand The purpose of migration is to enable external service 

btw, it can be the same on personal repos (but will less services)

**Comment by aichholzer** [comment]
Did you guys want to use my org `TheBenchmarker`?
-I will make you all part of it.

**Comment by waghanza** [comment]
@aichholzer For me it is OK to choose a project name like `TheBenchmarker/backend` :heart: (as I am more skilled in **backend** things). I will be hapier :tada: if you can collaborate as you seems to be more skills in **server-side frontend**.

@tbrand  Is it OK for you ?

**Comment by waghanza** [comment]
@aichholzer sorry for the mis-understanding, I just show a majority of `javascript` app on your [repos](https://github.com/aichholzer?tab=repositories)

**Comment by aichholzer** [comment]
I get paid to write Node.js software, hence the mostly JS repos.
And no need to be sorry.

**Comment by waghanza** [comment]
@aichholzer interesting ... can I make a short cut by saying `rayo` will be used in **production** in your company ?

**Comment by aichholzer** [comment]
`Rayo` is already used in production at a couple of companies. ;)
⚡️

**Comment by tbrand** [comment]
Hi all! Thanks for the many suggestions and discussions!!

Finally I decided to migrate this repo into `which-is` org. And the name of this repo gonna be `the-fastest` at first. (It would be changed)
The reason is that it is the only way to keep the effective name and it also has flexibility for the future.

I'll close the issue.
If you have other comments, please open new issues or ping me on gitter.

Regards.

**Comment by tbrand** [comment]
@waghanza deny to my proposal on Gitter. Please continue the discussion.

**Comment by waghanza** [comment]
@tbrand sure

for me this decision will be long and puprose is **promotion** ...

I think there is 2 main ideas here :
+ enabling multiple service to help **maintaining** @tbrand giving me the right to enable such service could be a short term solution
+ migrating as an org in order not to depend on **1** person for some stuff + promoting

Summarizing our discussion, we agree about migrating to org `TheBenchmarker`.
The next step is too choose the project name (according to what use case we want to deal about)

**Comment by tbrand** [comment]
Did we? I've never agreed the org name. (Thanks for the proposal anyway.)
Who did agree and when?

**Comment by waghanza** [comment]
@tbrand I've noticed it, but the way **we** will succeed it to let a majority of developers decide.

Are you agree ?

**Comment by tbrand** [comment]
It it's snake case, I'll accept.

**Comment by tbrand** [comment]
Oh no snake cases since it cannot contain underbars. I've took `the-benchmarker`.

**Comment by waghanza** [comment]
@tbrand I do not understand, your concern is about the letter design ?

**Comment by tbrand** [comment]
Yup

**Comment by tbrand** [comment]
I just prefer `the-benchmarker/which-is-the-fastest` to `TheBenchmarker/WhichIsTheFastest` since former is readable for me.

**Comment by waghanza** [comment]
@tbrand  is this a problem of **keyboard** `layout`, or something like that ?

honestly, it equal for me (camel case, snake case), I just prefer to have **several** developers.

if @aichholzer @OvermindDL1 @paulcsmith are OK for this naming convention, it's ok for me :heart:

**Comment by tbrand** [comment]
I mean readability.

**Comment by waghanza** [comment]
multiple persons **COULD** read differently ;-) 

even in developers communities 
+ **haskell** use `capital` for word separation
+ **ruby** use `underscore`
+ **you** prefer dashes

it's a mather of personal feeling :stuck_out_tongue:

**Comment by tbrand** [comment]
I would like to keep the dash style at least.

**Comment by tbrand** [comment]
If it's equal for you, could you respect the dash style?

**Comment by waghanza** [comment]
yeah sure

@aichholzer  what do you think ?

**Comment by tbrand** [comment]
Who will be the contributors of the org?

**Comment by aichholzer** [comment]
I have no say in this matter, I was merely trying to help.
By reading the last comments; clearly the priority is not in what you are trying to achieve (as a community or a service) but rather getting caught up in the (ridiculous) details, such as `camelCase` or `dashed` or neither.

As an anecdote: A few years ago `io.js` was forked as an alternative project to `node.js` because `Joyent` had a different idea/vision of where to take the project and where the priorities where... They too got lost in the irrelevant details.

Best of luck moving forward.

**Comment by waghanza** [comment]
at least @waghanza, @tbrand  and @OvermindDL1 

if @aichholzer  want to join (or use want to join @aichholzer :stuck_out_tongue: ) it will be great :+1:

**Comment by tbrand** [comment]
lol. You are right. I was out of the way.

**Comment by waghanza** [comment]
@tbrand I deliberately delayed this 😉

As well are testing only web tool (http ones), I suggest we use a name with `http` or `web` inside

`the-benchmarker`/`http-performance`

So as it clearly shows that this project aims to compare performance, ans it let us option to create other projects for sql tools.

What do you think ?

PS : It is my last change, I promise 😆

**Comment by waghanza** [comment]
@aichholzer Let's wau
