### ISSUE TITLE
Upgrade scala to 2.13

### ISSUE THREAD

**Issue by waghanza** [the-benchmarker/web-frameworks#2557]
Hi @mfirry,

Would you mind helping this project to use **2.13** for both `http4s` and `akka` ?

Regards,

**Comment by mfirry** [comment]
Sure. I'll also upgrade sbt to the latest version. Ok?

**Comment by waghanza** [comment]
Sure, I have honestly to completely rely on you ... I have no `scala` skills, I'm more on `ruby` side :heart:
