### ISSUE TITLE
Where the results come from?

### ISSUE THREAD

**Issue by kazzkiq** [the-benchmarker/web-frameworks#2565]
First of all, thanks for this awesome project!

In the README it says the results are extracted from a DigitalOcean VPS. But there is no additional info regarding the droplet type (amount of RAM, num of CPU cores, etc).

It would be interesting to share which droplet config was used to get those results so we (users) can have a baseline (for better or for worse) to compare these results with our own servers.

**Comment by waghanza** [comment]
Hi @kazzkiq,

Welcome

> First of all, thanks for this awesome project!

I'm glad you enjoy it :heart: 

> In the README it says the results are extracted from a DigitalOcean VPS.

Nop. Not a this stage. I'm on #2411 to made this possible, but I can not give you any ETA, it is a very long run ... as for now the results are considered as **developer preview**. I mean that the results are collected from a `local` **docker**, I mean I run ~150 containers on my workstation (it takes about 15 hours).

Of course, when on **production**, after #2411, I will display some technical details on `README`.

In fact using `droplets` will be the very first infra in use. I plan to run on `kubenetes` and even `baremetal` to have more meaningful results for a majority

**Comment by kazzkiq** [comment]
That's awesome!

I had no idea there was so much time involved in running the benchmarks. 15 hours seems a lot and I thanks once again for this work that bring so much useful information to us. Looking forward to #2411!

Do you think it is possible to share your workstation specs with us just to we can get an idea of the hardware those results come from? (i7? which SO? How much RAM? Number of cores? etc).

I believe it would be really useful to have this info while #2411 is in the works.

**Comment by waghanza** [comment]
You're right, I'll share it his on readme

**Comment by waghanza** [comment]
Unfortunately, I can produce any result. Their is still a **blocking** _issue_ https://github.com/the-benchmarker/web-frameworks/issues/2575, but working on it.

Stay in touch :tada:

**Comment by waghanza** [comment]
@kazzkiq results has been updated
