### ISSUE TITLE
Switch CI

### ISSUE THREAD

**Issue by waghanza** [the-benchmarker/web-frameworks#2608]
Hi,

We actually use `travis-ci`.

There is two disadvantages :
+ Duration (about 3 hours with ~150 frameworks)
+ False positives (network failures ...)
+ Complex configuration

I think it is time to test CIs :
+ `circle-ci`
+ `semaphore-ci`

**Comment by appleboy** [comment]
How about Github Actions or Drone CI?

**Comment by waghanza** [comment]
Not opposed ... I don't know them :stuck_out_tongue: 

In fact, I I need is to setup a 2 level depth CI :

1. List all frameworks
2. Run tests for each of them

I've successfully created something I like with https://the-benchmarker.semaphoreci.com/workflows/e4bf3e35-ba55-4c9f-a356-89a2e151b3a3, but if this configuration could be done with other tools, I could switch

**Comment by waghanza** [comment]
I've contact `cirrus-ci` => https://github.com/cirruslabs/cirrus-ci-docs/issues/633

The 2 cents about `CI` are :
+ Having a bootstrap job (compile tools, create configs ...)
+ Sharing files between tasks

Neither multi-OS is required, nor dynamic matrix are required, but having them is :+1:
