### ISSUE TITLE
Homogenize logging feature

### ISSUE THREAD

**Issue by waghanza** [the-benchmarker/web-frameworks#2622]
Hi,

Some framework are made to disable logging. 

To ensure fairness (at least maximum we can do), we need to have a **production-level** logging level.

For example, `lucky` is configured to handle `info` logs.

Regards,

**Comment by Blacksmoke16** [comment]
Reiterating my thoughts from #2915:

I can see the point of wanting to provide benchmarks that would match what a user would see when they go to use it.  However my concern is it would bias the results towards frameworks that have less logging in the first place.  The only sensible & fair solution is to disable logging across the board.

[TechEmpower](https://www.techempower.com/benchmarks/)'s guidelines take this stance:

> All test implementations must disable all disk logging. For many reasons, we expect all tests will run without writing logs to disk. Most importantly, the volume of requests is sufficiently high to fill up disks even with only a single line written to disk per request. Please disable all forms of disk logging. We recommend but do not require disabling console logging as well.

Given they say **We recommend but do not require disabling console logging as well**, I can't imagine any framework not doing that.

> For example, `lucky` is configured to handle `info` logs.

That might explain why it's the 4th slowest framework in the list 😉.

**Comment by waghanza** [comment]
To summarize, usually on **production** app, we **SHOULD NOT** disable logging.

However, your main point @Blacksmoke16 is that logging **SHOULD** be disabled `here`, because logging consist in disk operations are in tank the results.

So,
+ in one hand, we have the idea to run as-production
+ in the other hand, we have the idea that we can not use **logging** as production (it mess-up results)

After reflexion, @Blacksmoke16, I think we **SHOULD** disable **logging**. However, we **SHOULD** adds this information clearly.

Disable logging should in all frameworks. @Blacksmoke16, could you open a `PR` to disable it on all `crystal` frameworks ? I'll take care of the other. The idea is to disable logging for all, in order not to be "unfair"
