### ISSUE TITLE
Spiral is corrupted

### ISSUE THREAD

**Issue by waghanza** [the-benchmarker/web-frameworks#2645]
Hi @wolfy-j,

`spiral` is failing at https://travis-ci.com/github/the-benchmarker/web-frameworks/jobs/328176018#L340

We are using **alpine** 

Full `dockerfile` is :

```dockerfile
FROM php:7.4-fpm-alpine
RUN apk add git zlib-dev libzip-dev build-base autoconf nginx openrc 
RUN docker-php-ext-install zip opcache
WORKDIR /usr/src/app
COPY . ./
RUN curl -sSL https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
RUN composer install --no-dev --prefer-dist --classmap-authoritative
RUN composer dumpautoload -o
RUN vendor/bin/spiral get
RUN php app.php configure
CMD ./spiral serve
```

The source code is in https://github.com/the-benchmarker/web-frameworks/tree/master/php/spiral

Regards,

**Comment by 48d90782** [comment]
@waghanza Done. The problem was in the release tag 2.4.16 -> v2.4.16.
