### ISSUE TITLE
Introduce goyave

### ISSUE THREAD

**Issue by waghanza** [the-benchmarker/web-frameworks#2647]
Hi @System-Glitch,

Would you mind to add (or consent that we add) [goyave](https://github.com/System-Glitch/goyave) in `here` ?

This project compare performance based on 3 routes :

+ `GET` `/`, **SHOULD** return a successful status code and an empty string
+ `GET` `/user/:id`, **SHOULD** return a successful status code and the id
+ `POST` `/user`, **SHOULD** return a successful status code and an empty string

Regards,

**Comment by System-Glitch** [comment]
Hi, you can add it!
