### ISSUE TITLE
Introduce Urlpath

### ISSUE THREAD

**Issue by proyb6** [the-benchmarker/web-frameworks#2676]
I see this has an interesting approach to router.

Language: Go
Author: ucarion
Repo: https://github.com/ucarion/urlpath

**Comment by waghanza** [comment]
Hi @ucarion,

Would you mind to add (or consent that we add) [urlpath](https://github.com/ucarion/urlpath) in `here` ?

This project compare performance based on 3 routes :

+ `GET` `/`, **SHOULD** return a successful status code and an empty string
+ `GET` `/user/:id`, **SHOULD** return a successful status code and the id
+ `POST` `/user`, **SHOULD** return a successful status code and an empty string

Regards,

**Comment by appleboy** [comment]
This is not a web framework. It only supports parse the URL path.

**Comment by waghanza** [comment]
indeed, it's not a full-feature router

comparing this could be interesting, but not at this stage @proyb6 

Thanks @appleboy
