### ISSUE TITLE
Add fastsitephp

### ISSUE THREAD

**Issue by waghanza** [the-benchmarker/web-frameworks#2680]
Hi @ConradSollitt,

Would you mind to add (or consent that we add) [fastsitephp](https://github.com/fastsitephp/fastsitephp) in `here` ?

This project compare performance based on 3 routes :

+ `GET` `/`, **SHOULD** return a successful status code and an empty string
+ `GET` `/user/:id`, **SHOULD** return a successful status code and the id
+ `POST` `/user`, **SHOULD** return a successful status code and an empty string

Regards,

**Comment by ConradSollitt** [comment]
Hi @waghanza 

Thanks for finding FastSitePHP and contacting me!

This would be great, I was actually planning on opening an issue in the future to help add it.

I can likely help with full setup and help testing next week (possibly this Friday as well). I would be really curious how FastSitePHP stacks up as I've done extensive testing with `ab` Apache Benchmark and `autocannon` and have been able to achieve requests per second similar to nodejs with express and python with Flask.

I haven't read the full docs and just glanced at the other frameworks are setup, yaml config, and how the Dockerfile works.

The setup for FastSitePHP could probably use the below code. Feel free to add it if you like or I can submit a pull request once I read the docs some more. I've developed and tested the `public/index.php` file locally and it works. I've included comments in the PHP code is that it's helpful for developers to follow how it works.

**File: [composer.json]**
~~~json
{
    "require": {
        "fastsitephp/fastsitephp": "^1.2"
    }
}
~~~

~~~yaml
framework:
  website: fastsitephp.com
  github: fastsitephp/fastsitephp
  version: 1.2
~~~

**File: [public/index.php]**
~~~php
<?php

// -----------------------------------------------
// Load Dependencies (additional PHP files) 
// -----------------------------------------------

// Setup a PHP Autoloader
// This allows classes to be dynamically loaded and is included when
// install dependencies through the PHP Package Manager Composer.
//
// require __DIR__ . '/../vendor/autoload.php';

// Or for a minimal site when using FastSitePHP only the following 2 files
// need to be included.
//
// Using location based on install from:
//     composer require fastsitephp/fastsitephp
//
// This also assumes that this file is located under a [public]
// directory (or directory with another name and same dir structure)
//
require __DIR__ . '/../vendor/fastsitephp/fastsitephp/src/Application.php';
require __DIR__ . '/../vendor/fastsitephp/fastsitephp/src/Route.php';

// -----------------------------------------------
// Create the setup the Application Object with
// Error Handling and UTC for the Timezone
// -----------------------------------------------

$app = new \FastSitePHP\Application();
$app->setup('UTC');

// -----------------------------------------------
// Define Routes
// -----------------------------------------------

$app->get('/', function() {
    return '';
});

$app->get('/user/:id', function($id) {
    return $id;
});

$app->post('/user', function() {
    return '';
});

// -------------------------
// Run the application
// -------------------------

$app->run();
~~~
