### ISSUE TITLE
Tornado misleading benchmarks

### ISSUE THREAD

**Issue by Aeron** [the-benchmarker/web-frameworks#2682]
Hi, @waghanza,

Would you mind clarifying why Tornado is currently benchmarking in a blocking mode while it intended to perform mostly in a non-blocking manner? Was it intentional or utterly a typo/mistake?

Also, it can utilize the power of `uvloop`, as `aiohttp` does, and almost any `asyncio`-based solution could.

Moreover, it has no use of `gunicorn` overhead, but it’s a question for another topic.

**Comment by waghanza** [comment]
Hi @Aeron,

Thanks for pointing this fact. 

The intention, and the purpose, of this benchmark is to have some **production-grade** implementations.

Clearly, I'm not an expert, of any framework `here` (in fact, somes :stuck_out_tongue:) feel free to contribute to homogenize frameworks to be **production-grade**

Regards,

**Comment by Aeron** [comment]
Ok, I see. Thanks for the clarification. I’ll do my best to spare some time and contribute properly.
