### ISSUE TITLE
CI is not helpful

### ISSUE THREAD

**Issue by waghanza** [the-benchmarker/web-frameworks#271]
Hi,

Test on CI are passing even when some rules are not met.

We need to use **assertions**

Regards,

**Comment by waghanza** [comment]
@OvermindDL1 what headers has to be sent in a standard HTTP request ?

**Comment by OvermindDL1** [comment]
What version of HTTP?

Everything in this repo could easily be following HTTP/1.0 as no 'advanced' features virtualhosts are required, thus as far as I recall and of the RFC's I have up currently:

### HTTP/1.0

`GET / HTTP/1.0` is the most simple perfectly valid request.  HTTP/1.0 requires no headers.

However, a `Date` header is highly recommended, but is not hard Required (although a later RFC 'suggests' making it required in 'some' situations, however that is still not all and it is in the post HTTP/1.1 world).

However, a `Content-Length` or `Transfer-Encoding` header must be included if there is non-empty data returned.

Technically a server is required to send a `Connection: Close` as well if it does not support persistent connections, however I cannot think of any webserver, even the ones that I know of in this repo, that wouldn't support that.

### HTTP/1.1

This expands on HTTP/1.0 by requiring a `Host` header, other than that it has the same hard requirements as HTTP/1.0

### HTTP/2.0

This gets in to a whole new world of things...  >.>

**Comment by waghanza** [comment]
ok. I'll add some test to validate this (`HTTP/1.1` for now)
