### ISSUE TITLE
web, micro, socket framework, etc and non-framework?

### ISSUE THREAD

**Issue by martinzee** [the-benchmarker/web-frameworks#2731]
Some of the non-framework or framework in the ranking are *web framework*?
To see what I mean, I have compiled a partial list if those should be keep to minimize your resources and less confusion for the readers.

## Remove?

nanoexpress pro and nano express are same author, does not make sense?

kitura and kitura-nio can be removed, they are no longer active.

*toro*
Tree oriented routing

*router.cr*
Minimum High Performance Middleware for Crystal Web Server.

*Httpbeast*
A highly performant, multi-threaded HTTP 1.1 server written in Nim.

*workerman*
PHP socket framework

*Orion*
A Crystal router

*0http*
Cero friction HTTP requests router. The need for speed!

*http4s*
Typeful, functional, streaming HTTP for Scala.

*iotas-express*
Basic reimplementation of Express.js for IoT.js or Node

*Polkadot*
The tiny HTTP server that gets out of your way!

*Hyper*
Hyperf is a high-performance, highly flexible PHP CLI framework

*AIOHTTP*
Asynchronous HTTP Client/Server for asyncio and Python.

**Comment by waghanza** [comment]
Hi @martinzee,

You started a good point here. Every framework are not on the same fashion `here`, I mean some are :
+ `micro`, without any included library / other components
+ `full stack`, with other components (**ORM** for example)
+ `router`, only the router component

Instead of removing some, better categorize them :heart: 

Regards,

**Comment by waghanza** [comment]
Beside, I'll be glad you start a `PR` adding anything in `config.yaml` to categorize each **frameworks**  `here`.

I know, categorizing ~150 **frameworks** is a big task, but feel free to start, we will complete / help (just do not use a **master** `branch`)
