### ISSUE TITLE
Two framework from the same author

### ISSUE THREAD

**Issue by waghanza** [the-benchmarker/web-frameworks#2734]
Hi @martinzee,

In https://github.com/the-benchmarker/web-frameworks/issues/2731, you say :

> nanoexpress pro and nano express are same author, does not make sense?

Why do you think this do not make any sense ?

Regards,

**Comment by dalisoft** [comment]
If you think it’s not good idea, then remove nanoexpress-pro as it’s licensed under gpl-3.0 and does not allow use for anyone on commercial project

**Comment by waghanza** [comment]
Personnally, I'm not against ❤️ 

Just asking @martinzee why this matter

**Comment by dalisoft** [comment]
No response from @martinzee, maybe we close issue? Or we'll wail?
