### ISSUE TITLE
cache bust routes

### ISSUE THREAD

**Issue by stakach** [the-benchmarker/web-frameworks#2841]
@waghanza for testing the route param request can you make all the requests unique?
i.e. `/user/:id` send a different `id` with each request

This would bust caches that might otherwise hide real world performance

**Comment by waghanza** [comment]
Hi @stakach,

If I understand correctly, you say that some framework in `here` could bust cache name route (`/user/:id`) and the mess-up results.

I thought this technique was for static files.

Regards,

**Comment by stakach** [comment]
Makes sense for static files, these are some obvious examples

https://github.com/kemalcr/kemal/blob/master/src/kemal/route_handler.cr#L8
https://github.com/grip-framework/grip/blob/master/src/grip/router/http.cr#L45

**Comment by waghanza** [comment]
Ah, I see. Some framework internally caches some routes.

For you this caching make results unfair, since other frameworks does not perform caching

I'm not sure this has to be a decision made `here`. In my humble opinion, this behaviour is a design choice for the framework.

I understand what you point, but I don't understand how can this point hide real world performance

**Comment by stakach** [comment]
A service with thousands of requests a second is unlikely to have less than 1024 database entries across all tables (which is all the cache is supporting)

I assume people looking at benchmarks for guidance would be looking for an indication of what performs well at this scale. So the benchmark is misleading as in the real world the cache would be missed most of the time.

The caches referenced above are also used to cache static routes, so in a high use environment, even static routes would perform poorly.

This benchmark is meant to measure `routing times` but these caches avoid that measurement and are only effective on benchmarks

**Comment by waghanza** [comment]
I see your point @stakach. You say that having any `caching` layer (`built-in` or external) could mess-up result, in term of increase routing time. You are right.

However, implement a **cache** policy represent a cost (disk access or in-memory database access or whatsoever). Having this feature is a design decision taken by the framework. As I say, their is a cost.

I think that this cost will be reflected at some point (when other measures will come, like the consumption ...).

The idea behind this project is to show some measure (and **NOT** only the `routing time`, but in the future) so as to any decide can have insight to choose any stack.

In my humble opinion, having a random number (when call `/user/:id` => to bypass the caching feature) does not represent a real word use case. I mean that the purpose of any stack is to manage repetition (I mean that 1 route used by 1000 user could more reflect the usage in real life)

What do you think ?
