### ISSUE TITLE
[Dart] Add start

### ISSUE THREAD

**Issue by waghanza** [the-benchmarker/web-frameworks#2860]
Hi @lvivski,

Would you mind to add (or consent that we add) [start](https://github.com/lvivski/start) in `here` ?

This project compare performance based on 3 routes :

+ `GET` `/`, **SHOULD** return a successful status code and an empty string
+ `GET` `/user/:id`, **SHOULD** return a successful status code and the id
+ `POST` `/user`, **SHOULD** return a successful status code and an empty string

Regards,

**Comment by lvivski** [comment]
Wow, this is a interesting comparison. Feel free to add Start here. Looking forward to see the results :)
