### ISSUE TITLE
[Dart] Add angel

### ISSUE THREAD

**Issue by waghanza** [the-benchmarker/web-frameworks#2864]
Hi @thosakwe,

Would you mind to add (or consent that we add) [angel](https://github.com/angel-dart/angel) in `here` ?

This project compare performance based on 3 routes :

+ `GET` `/`, **SHOULD** return a successful status code and an empty string
+ `GET` `/user/:id`, **SHOULD** return a successful status code and the id
+ `POST` `/user`, **SHOULD** return a successful status code and an empty string

Regards,

**Comment by starquake** [comment]
Angel is no longer maintained. Do you really still want this?

**Comment by thosakwe** [comment]
+1. As the creator of Angel, I recommend closing this.

**Comment by waghanza** [comment]
Hey @thosakwe,

Thanks for the ping. 

`Angel` was removed from here, forget to close this one.

Regards,
