### ISSUE TITLE
[Nim] Add nerve

### ISSUE THREAD

**Issue by waghanza** [the-benchmarker/web-frameworks#2866]
Hi @nepeckman,

Would you mind to add (or consent that we add) [nerve](https://github.com/nepeckman/nerve-rpc) in `here` ?

This project compare performance based on 3 routes :

+ `GET` `/`, **SHOULD** return a successful status code and an empty string
+ `GET` `/user/:id`, **SHOULD** return a successful status code and the id
+ `POST` `/user`, **SHOULD** return a successful status code and an empty string

Regards,

**Comment by nepeckman** [comment]
Hey @waghanza!

I would definitely be open to adding nerve to the project, but I'm not sure it fits in with what you're trying to do. As a point of clarification, nerve is a JSON RPC framework that works over HTTP. The client sends over method and parameter information via an HTTP POST, and the sever does the dispatch. I say all of this to explain that nerve wouldn't respond to the REST routes in your post, but would respond to a JSON RPC request.

If you are still interested in a working example, let me know and I can add that. If not, no worries :)

**Comment by waghanza** [comment]
I think I was misguided by the example in https://github.com/nepeckman/nerve-rpc#hello-world (I was late and I was not very careful :stuck_out_tongue:).

You are right an RPC server is not the main target `here`, we are more focusing on `HTTP` servers
