### ISSUE TITLE
[F#] Add frank

### ISSUE THREAD

**Issue by waghanza** [the-benchmarker/web-frameworks#2869]
Hi @panesofglass,

Would you mind to add (or consent that we add) [frank](https://github.com/frank-fs/frank) in `here` ?

This project compare performance based on 3 routes :

+ `GET` `/`, **SHOULD** return a successful status code and an empty string
+ `GET` `/user/:id`, **SHOULD** return a successful status code and the id
+ `POST` `/user`, **SHOULD** return a successful status code and an empty string

Regards,

**Comment by panesofglass** [comment]
I'd be delighted to add it. I'll submit a PR tonight. Thank you!

**Comment by panesofglass** [comment]
@waghanza you should also reach out to @dustinmoris for [Giraffe](https://github.com/giraffe-fsharp/Giraffe), @Krzysztof-Cieslak for [Saturn](https://saturnframework.org/), and @pimbrouwers for [Falco](https://github.com/pimbrouwers/Falco) to fill out the F# space.

**Comment by pimbrouwers** [comment]
I'm happy to do a PR for this. I'm fairly familiar with these tests, but is there a requirements doc I can follow.

**Comment by panesofglass** [comment]
@pimbrouwers looks like it is simply three handlers. You should be able to follow the Suave example.

**Comment by pimbrouwers** [comment]
My apologies. I thought these were the tech empower benchmarks. 

This should be dead simple. I'll PR tomorrow morning.

**Comment by panesofglass** [comment]
@pimbrouwers I may just include a sample for each in my PR. I don’t think this would be challenging. Saturn may be slightly tougher, but I doubt it.

**Comment by panesofglass** [comment]
@granicz or @Tarmil, want to take a crack at adding a WebSharper option?

**Comment by panesofglass** [comment]
@granicz and @Tarmil, I included a sample in my PR #2874

**Comment by waghanza** [comment]
To keep code consistent, between **F#** frameworks, I want to use a formatter. What do you think of https://github.com/fsprojects/fantomas-tools  ?

**Comment by panesofglass** [comment]
That's fantastic!

**Comment by panesofglass** [comment]
I added fantomas and re-formatted the files using the defaults.

**Comment by waghanza** [comment]
Not at all. https://restyled.io will take care ok (on thext release)

**Comment by panesofglass** [comment]
@waghanza, should I roll back the previous change, then?

**Comment by waghanza** [comment]
nop, thanks for your work. I'll handle it :heart:
