### ISSUE TITLE
[feature] Historic results

### ISSUE THREAD

**Issue by bnkamalesh** [the-benchmarker/web-frameworks#2875]
Since the results are stored in a database, and there's already plan for introducing a dedicated backend with GraphQL for fetching results (https://github.com/the-benchmarker/web-frameworks/issues/1618). It would be awesome if we could show the historic changes of a framework. i.e. benchmark changes from version to version.

**Comment by waghanza** [comment]
Totally up-to this. 

However, we have to be focused (mostly because I am the only core developer as for now.

I think, it could be better if I create some project to separate concern and clarify the roadmap / ideas we gather.
