### ISSUE TITLE
[PHP] Add bearframework

### ISSUE THREAD

**Issue by waghanza** [the-benchmarker/web-frameworks#2883]
Hi @ivopetkov,

Would you mind to add (or consent that we add) [bearframework](https://github.com/bearframework/bearframework) in `here` ?

This project compare performance based on 3 routes :

+ `GET` `/`, **SHOULD** return a successful status code and an empty string
+ `GET` `/user/:id`, **SHOULD** return a successful status code and the id
+ `POST` `/user`, **SHOULD** return a successful status code and an empty string

Regards,

**Comment by dominikzogg** [comment]
https://github.com/the-benchmarker/web-frameworks/pull/3116
