### ISSUE TITLE
[V] Add vex

### ISSUE THREAD

**Issue by waghanza** [the-benchmarker/web-frameworks#2893]
Hi @nedpals,

Would you mind to add (or consent that we add) [vex](https://github.com/nedpals/vex) in `here` ?

This project compare performance based on 3 routes :

+ `GET` `/`, **SHOULD** return a successful status code and an empty string
+ `GET` `/user/:id`, **SHOULD** return a successful status code and the id
+ `POST` `/user`, **SHOULD** return a successful status code and an empty string

Regards,

**Comment by enghitalo** [comment]
I think this issue should be closed. The vex was discontinued.

**Comment by waghanza** [comment]
Cc @nedpalq
