### ISSUE TITLE
[V] Add vape

### ISSUE THREAD

**Issue by waghanza** [the-benchmarker/web-frameworks#2894]
Hi @exastencil,

Would you mind to add (or consent that we add) [vape](https://github.com/exastencil/vape) in `here` ?

This project compare performance based on 3 routes :

+ `GET` `/`, **SHOULD** return a successful status code and an empty string
+ `GET` `/user/:id`, **SHOULD** return a successful status code and the id
+ `POST` `/user`, **SHOULD** return a successful status code and an empty string

Regards,

**Comment by exastencil** [comment]
Sure. I don't mind that you add it. Otherwise, I'll have a look to see how to do it when I get a free moment.

**Comment by exastencil** [comment]
There's a PR at #2902 . Since V isn't entirely stable yet, I'm not sure if things will run with the build used in that Docker container. There was an issue with function signatures when passed as arguments which was resolved somewhere in V 0.1.27. So a newer V may be needed.

**Comment by waghanza** [comment]
Probably better to use a raw containers, and compile `v` from source (**master**) then, but I can not reasonably merge it into master
