### ISSUE TITLE
Add cyclone (python)

### ISSUE THREAD

**Issue by waghanza** [the-benchmarker/web-frameworks#290]
https://github.com/fiorix/cyclone

**Comment by greed2411** [comment]
`Cyclone runs on Python 2.5, 2.6 and 2.7` you sure you want to proceed even after that?

**Comment by waghanza** [comment]
:tada: Good catch ! ! !

We could close ;-)

**Comment by waghanza** [comment]
@greed2411 need to follow the `state of art` :stuck_out_tongue_winking_eye: 
`python3` seems to be discussed here => https://github.com/fiorix/cyclone/issues/177
and even of `python3` **fork** was created here => https://github.com/ygl-rg/cyclone3
