### ISSUE TITLE
Why actix (rust) and drogon (c++) results are low?

### ISSUE THREAD

**Issue by testaccchris** [the-benchmarker/web-frameworks#2912]
In the techempower framework benchmark, clearly drogon and actix stomps all other framework. It is making sense cause in term of language, both are faster than Go,JS,Java,PHP. How come in this benchmark, both are ranked lower than the other?

**Comment by waghanza** [comment]
Hi @testaccchris,

There is several reason leading to that results :
+ **TFB** use different version
`master` for `drogon` (we are on `beta13`)
https://github.com/TechEmpower/FrameworkBenchmarks/blob/988f052c8170da661c49dd51d1f33d500a871031/frameworks/C%2B%2B/drogon/drogon.dockerfile#L44
+ **TFB** use compilation option (we use none)
https://github.com/TechEmpower/FrameworkBenchmarks/blob/988f052c8170da661c49dd51d1f33d500a871031/frameworks/C%2B%2B/drogon/drogon.dockerfile#L39
+ **TFB** use https://azure.microsoft.com (we a yet on local docker, cloud will come, see https://github.com/the-benchmarker/web-frameworks/pull/2593)

Regards,

PS : I close this issue for task management, but feel free to re-open, if my answer is not clear
