### ISSUE TITLE
[C++] Add nawa

### ISSUE THREAD

**Issue by waghanza** [the-benchmarker/web-frameworks#2925]
Hi @jatofg,

Would you mind to add (or consent that we add) [nawa](https://github.com/jatofg/nawa) in `here` ?

This project compare performance based on 3 routes :

+ `GET` `/`, **SHOULD** return a successful status code and an empty string
+ `GET` `/user/:id`, **SHOULD** return a successful status code and the id
+ `POST` `/user`, **SHOULD** return a successful status code and an empty string

Regards,

**Comment by jatofg** [comment]
Sure, no problem. I'll have a look at it if I find some free time in the next days.
