### ISSUE TITLE
Frameworks update

### ISSUE THREAD

**Issue by waghanza** [the-benchmarker/web-frameworks#2948]
Hi,

We have (on 13th of June 2020), 24 languages. This issue track 

|  Language | Supported        | Issue(s) |
| --------------|----------------------|---------|
| C              | :no_entry_sign: |           |
| C++          | :no_entry_sign: |           |
| C#            | :no_entry_sign: | https://github.com/renovatebot/renovate/issues/6487 |
| Clojure     |   :ok:                  |           |
| Crystal     | :no_entry_sign: |           |
| Dart         |   :ok:                   |           |
| Elixir        | :no_entry_sign:  |           |
| F#           |  :no_entry_sign: | https://github.com/renovatebot/renovate/issues/6487   |
| Go           |       :ok:               |           |
| Haskell    | :no_entry_sign:   |           |
| Java        |     :ok:                  |           |
| Javascript  |    :ok:                |           |
| Julia        |     :no_entry_sign:    | https://github.com/renovatebot/renovate/issues/6508 |
| Kotlin       |   :no_entry_sign:     |           |
| Nim          |    :no_entry_sign:              |           |
| Perl          |  :no_entry_sign:      |           |
| PHP         |   :ok:                 |           |
| Pony        |    :ok:            |           |
| Ruby        |     :ok:              |           |
| Rust         |    :ok:         |           |
| Scala       |      :ok:              |           |
| Swift         |     :ok:               |           |
| V              |      :no_entry_sign:    |           |

/cc @rarkins

Regards,

**Comment by rarkins** [comment]
Feature requests with requirements and examples for each missing one would be great

**Comment by waghanza** [comment]
Sure, this is the purpose of having this `here` :heart:

As we have many languages, I can provide examples ...
