### ISSUE TITLE
[Python] Add Tonberry

### ISSUE THREAD

**Issue by waghanza** [the-benchmarker/web-frameworks#2949]
Hi @Ayehavgunne,

Would you mind to add (or consent that we add) [Tonberry](https://github.com/Ayehavgunne/Tonberry) in `here` ?

This project compare performance based on 3 routes :

+ `GET` `/`, **SHOULD** return a successful status code and an empty string
+ `GET` `/user/:id`, **SHOULD** return a successful status code and the id
+ `POST` `/user`, **SHOULD** return a successful status code and an empty string

Regards,

Thanks @florimondmanca for mention it in https://github.com/florimondmanca/awesome-asgi

**Comment by Ayehavgunne** [comment]
Sure. That sounds great! You can add it unless I get around to it first. 😃
