### ISSUE TITLE
Add httpbeast

### ISSUE THREAD

**Issue by dom96** [the-benchmarker/web-frameworks#295]
https://github.com/TechEmpower/FrameworkBenchmarks/tree/master/frameworks/Nim/httpbeast

**Comment by waghanza** [comment]
@dom96 does `httpbeast`  support routing ?

**Comment by dom96** [comment]
Depends how sophisticated the routing has to be. It is pretty barebones though.

**Comment by waghanza** [comment]
@dom96 the routes are pretty simple like described on #211

**Comment by dom96** [comment]
Is doing some string handling acceptable? ``request.path.startsWith("/user/"): let id = request.path[6 .. ^1]``

**Comment by waghanza** [comment]
@dom96 why not ^^^

Pour purpose is to compare performances, so no matter what impl

**Comment by OvermindDL1** [comment]
> why not ^^^

You didn't accept that identical testing in the C++ version though, hence why it was converted to the slower regex path matcher.  ;-)

**Comment by waghanza** [comment]
For me parsing URL with a regexp is good (I have juste noticed that regexp un `evhtp` impl is too open).

What we want (for me) is routing, no matter what technic is used (regexp, or elle). However, this step **SHOULD** to be done as a dispatcher -> I mean handling http req to route to a spécifications code (not handling all urls in one function)

PS : @OvermindDL1 `evhtp` is enabled, but we have to restrict route

**Comment by dom96** [comment]
More restrictive? What do you mean?

You can use regex for it too if you want, but I find that a little silly.

**Comment by waghanza** [comment]
I come from `ruby` world,  and it does not blow my eyes when I read a route 
```rails
get '/user/[\d]+, ....
```

But perhaps there is a smarter way to do (having one place where is defined callback in use and params), feel free to share ^^

**Comment by OvermindDL1** [comment]
> @OvermindDL1 could you list the routing interface ?
> In the case of evhtp , routing has to be used only to check /user/%d on GET

It has exact matching (exact string match, which most frameworks support), it has prefix matching (like how the elixir and many other frameworks primarily route on), it has regex matching (which frameworks like elixir do not support at all and you have to build it yourself), it has custom matching (supply your own matching and routing handler) that I know of off hand, and I think I'm missing one.  In general the order supplied above is the efficiency that they run at (although the custom matching might be better or worse depending on what you do).  Full full key processing and validation checking you use the regex matcher (which is what the evhtp benchmark is doing now).

> `get '/user/[\d]+, ....`

That's essentially what evhtp is doing currently (although not `\d` I think as that wass not part of the readme requirements at the time, is it now?).

**Comment by dom96** [comment]
> I come from ruby world, and it does not blow my eyes when I read a route

My suggestion is surely not that much harder to read. The advantage is that it should be many times faster than resorting to Regex.

**Comment by waghanza** [comment]
@OvermindDL1 it's quite the case https://github.com/tbrand/which_is_the_fastest/blob/master/cpp/evhtp/main.cpp#L41 but there is not restriction
How about prefix matching ? Could you show me a example

@dom96 does routing could be done something like one one line ?

**Comment by waghanza** [comment]
@OvermindDL1 do you have time to implement **custom matching**

if it's the fastest way to have routing, so why not having this in this project

**Comment by OvermindDL1** [comment]
This is where I did it with a combination prefix matcher and customer parser:
https://github.com/tbrand/which_is_the_fastest/blob/24b8f660bd2cbe1bfa80da391c4ac3d9ed264dd7/cpp/evhtp/main.cpp

Specifically this line:
https://github.com/tbrand/which_is_the_fastest/blob/24b8f660bd2cbe1bfa80da391c4ac3d9ed264dd7/cpp/evhtp/main.cpp#L24

```
const char *p = req->uri->path->full + 6; // 6 being the length of "/user/"
```

Being the line he objected to as it was not a built-in parser/matcher, where the regex does (it stores the matched segment into argument storage inefficiently and all just as he wanted).

**Comment by OvermindDL1** [comment]
> @OvermindDL1 I think a mis-understand match "/user/:blah" is more talkative to me, so it might be my confusion stuck_out_tongue

What that does is the same as the regex, just a different syntax form of it that is more efficient as it does less work but also means the data is not in any expected form (have to validate it yourself and can't change the matcher based on the data type unlike how you can do with regex or a custom matcher).

**Comment by dom96** [comment]
> @dom96 does routing could be done something like one one line ?

I don't want to bloat httpbeast with routing. Plus the code I gave you is only two lines, it's really not that much.

**Comment by waghanza** [comment]
@OvermindDL1 personally, I prefer the https://github.com/tbrand/which_is_the_fastest/blob/24b8f660bd2cbe1bfa80da391c4ac3d9ed264dd7/cpp/evhtp/main.cpp impl

@dom96 convinced, please be my guest on `PR`

**Comment by waghanza** [comment]
@tbrand Is there any warnings about that ?

**Comment by dom96** [comment]
I'll make a PR if @tbrand gives the OK :)

**Comment by waghanza** [comment]
@tbrand ok ?

@dom96 I'm OK for your `PR` ;-) (and **jester** fix if you have time)

**Comment by tbrand** [comment]
Can we say that the below code **has a feature of routing**?
```nim
if request.path.startsWith("/user/"):
  let id = request.path[6 .. ^1]
```

@dom96 You said

> Extremely fast HTTP responses in Nim.

Yeah that's sound great! But the feature does not match to the concept of this repo.
May be @waghanza will create other repos that will bench other features. I hope the httpbeast could be included in it.

**Comment by waghanza** [comment]
@tbrand For me `httpbeast` has routing feature (even if I personally found this not elegant comparing to `ruby` or `crystal`, but it's a matter of taste)

for me it's OK to include `httpbeast` in this repo

**Comment by tbrand** [comment]
@waghanza How?

> For me httpbeast has routing feature 

This way?
https://github.com/the-benchmarker/web-frameworks/issues/295#issuecomment-428428206

**Comment by waghanza** [comment]
@tbrand Yep

I totally agree that this writing way **COULD** be strange for some devs, but this code match routes :

+ /user/0
+ /user/1
+ /user/2

but not /users/1. 

For me it is a `routing` feature in the way that a `route` is handled by a portion of code

**Comment by waghanza** [comment]
@tbrand also **httpbeast** is on **tfb** https://github.com/TechEmpower/FrameworkBenchmarks/tree/master/frameworks/Nim
probably it **COULD** be considered as a `framework` with the features we expect here

**Comment by tbrand** [comment]
Hmm I don't think so. If we accept it, it means every languages level implementation can be accepted. (e.g. Crystal, Ruby, ...)
But if you wish, you could add it.

**Comment by waghanza** [comment]
you do not seems convinced ...

@OvermindDL1 what do you think ? (I do not want to take decisions unilaterally)

@dom96 for me a **important** point is : how we do not get out-of-sync ?

**Comment by dom96** [comment]
> every languages level implementation

What does that mean? Does it mean "every HTTP server implementation without a router?"

To be fair, your repo is called "web frameworks" so I can understand if you don't want HttpBeast in here. But IMO you should set the bar higher. Routing is relatively trivial.

> for me an important point is : how we do not get out-of-sync ?

What do you mean "out-of-sync"?

**Comment by waghanza** [comment]
@dom96 I mean having outdated implementations of each frameworks

**Comment by dom96** [comment]
It shouldn't be a big deal since you've pinned the versions.

**Comment by waghanza** [comment]
@dom96 If I can remind you, it will be better. I mean if codebase has to be updated, I prefer that its you (or an other `nim` **dev**) to take this task

**Comment by OvermindDL1** [comment]
> @OvermindDL1 what do you think ? (I do not want to take decisions unilaterally)

Seems fine to me to include it, what is being tested here isn't even the languages but rather how efficient their socket and string processing capabilities are considering how little time is spent in each language proper.  If you really wanted to do testing of the frameworks then you'd need to test a lot more, concurrency, websockets, etc... etc...  All that is being tested here is socket handling and some simple string processing.

**Comment by waghanza** [comment]
of course @OvermindDL1, a `proper` way to have a **full-feature** **benchmark** is to define a **complete** set of specs

I can handle work on implementations, but have no time to define a **complete** set of specs, if you are interested, feel free to write specs, I'll handle the coding part ;-)

@dom96 for me it's OK, you can open a `PR`

**Comment by dom96** [comment]
Okay, may take me a bit. Busy with a house move right now :)

**Comment by waghanza** [comment]
@dom96 ping ^^

**Comment by dom96** [comment]
heh, I still have no time for this, sorry. Happy to review PRs if you want to implement httpbeast benchmarks yourself

**Comment by waghanza** [comment]
I'll try

**Comment by waghanza** [comment]
@dom96 any time to make a `PR` ?

**Comment by waghanza** [comment]
@dom96 The parsing way is not realy important, the most important here is to have one parsing reflecting the **real-word** usage

**Comment by dom96** [comment]
Yeah, sorry, again, I'm happy to review any PRs. It should be fairly simple for you to implement this since you know exactly what you'd like out of the benchmark.
