### ISSUE TITLE
[Crystal] Add runcobo

### ISSUE THREAD

**Issue by waghanza** [the-benchmarker/web-frameworks#2958]
Hi @shootingfly,

Would you mind to add (or consent that we add) [runcobo](https://github.com/runcobo/runcobo) in `here` ?

This project compare performance based on 3 routes :

+ `GET` `/`, **SHOULD** return a successful status code and an empty string
+ `GET` `/user/:id`, **SHOULD** return a successful status code and the id
+ `POST` `/user`, **SHOULD** return a successful status code and an empty string

Regards,

**Comment by shootingfly** [comment]
@waghanza No, please.

**Comment by waghanza** [comment]
Ok, no pb. May I know why ?

**Comment by shootingfly** [comment]
@waghanza My bad english. I don't mind. I am happy to to see you add runcobo here.

**Comment by waghanza** [comment]
Ah ok. You don't mind :ok_hand:
