### ISSUE TITLE
Remove nanoexpress

### ISSUE THREAD

**Issue by dalisoft** [the-benchmarker/web-frameworks#2968]
Hi @waghanza 

Thanks for promoting and benchmarking nanoexpress.
Thanks to this project i got 100+ stars and now i excited to announce

**Now PRO version is FREE and licensed under Apache-2.0 license**

So, please can you remove **nanoexpress** itself, not PRO and default version is now deprecated

See [here](https://github.com/nanoexpress/nanoexpress/issues/108) if you want more information what is changed

**Comment by waghanza** [comment]
Hi @dalisoft,

Sure, I'll remove `nanoexpress`. 

I find tho weird to have a `-pro` version of something inexistent, I mean having only `nanoexpress-pro` without `nanoexpress`.

Have you considered replacing `nanoexpress` by `nanoexpress-pro` ?

Regards,

**Comment by dalisoft** [comment]
Thanks @waghanza 

Currently instant moving from nanoexpress to nanoexpress-pro confuses a lot of people (i sure 2K+ peoples), so i first deprecate fully nanoexpress on GitHub and on npm.
Then step by step move nanoexpress-pro repository code to nanoexpress and deprecate nanoexpress-pro and move npm to nanoexpress

**Comment by dalisoft** [comment]
Now default **nanoexpress** version stops getting any updates and **nanoexpress-pro** replaces **nanoexpress** as **nanoexpress-pro** got Apache-2.0 license (before was GPL-3.0) and required commercial license for commercial projects, now does not requires any commercial license

**Comment by dalisoft** [comment]
> I find tho weird to have a -pro version of something inexistent, I mean having only nanoexpress-pro without nanoexpress.

Yes, what moving step-by-step is good idea.
Maybe you can just name is **nanoexpress**, but use **nanoexpress-pro**

**Comment by waghanza** [comment]
> Maybe you can just name is nanoexpress, but use nanoexpress-pro

Nop... I think its better to follow **YOUR** schedule
