### ISSUE TITLE
[C#] Add Simplify.Web

### ISSUE THREAD

**Issue by waghanza** [the-benchmarker/web-frameworks#2973]
Hi @i4004,

Would you mind to add (or consent that we add) [Simplify.Web](https://github.com/SimplifyNet/Simplify.Web) in `here` ?

This project compare performance based on 3 routes :

+ `GET` `/`, **SHOULD** return a successful status code and an empty string
+ `GET` `/user/:id`, **SHOULD** return a successful status code and the id
+ `POST` `/user`, **SHOULD** return a successful status code and an empty string

Regards,

**Comment by i4004** [comment]
Hi! @waghanza , sure, it would be nice!
 _It would be better, if you do that, because right now I don't have time to figure out how to do that._

**Comment by pimbrouwers** [comment]
Sorry. I'm not familiar with this package either.
