### ISSUE TITLE
[Java] Add struts

### ISSUE THREAD

**Issue by waghanza** [the-benchmarker/web-frameworks#2976]
Hi @lukaszlenart @JCgH4164838Gh792C124B5

Would you mind to add (or consent that we add) [struts](https://struts.apache.org/) in `here` ?

This project compare performance based on 3 routes :

+ `GET` `/`, **SHOULD** return a successful status code and an empty string
+ `GET` `/user/:id`, **SHOULD** return a successful status code and the id
+ `POST` `/user`, **SHOULD** return a successful status code and an empty string

Regards,

**Comment by lukaszlenart** [comment]
Should this be a JSON based solution?

**Comment by waghanza** [comment]
Nop. We are using text plain, to avoid using librairies that can influence results.

**Comment by lukaszlenart** [comment]
`GET /user/:id` is just an echo service? I mean `GET /user/1` will return `HTTP 200` and `1`?

**Comment by waghanza** [comment]
absolutely

**Comment by JCgH4164838Gh792C124B5** [comment]
Hi @waghanza and @lukaszlenart.

Thanks for the notification concerning this topic.

I believe @lukaszlenart is best positioned to respond to your original question concerning Struts and the web-frameworks benchmark (at the top of the issue).  :sweat_smile:

There is certainly a growing list of Web frameworks according to the README, and it is interesting to see some "raw throughput numbers" for the same synthetic benchmark.

Out of curiousity about the benchmark, was the choice of the HTTP request structure:
    `GET /user/:id`
over a standard query string structure like:
    `GET /user?id=:id`
a deliberate choice, and if so why ?

Maybe it has something to do with wanting to force dynamic request paths vs. a single path with parameters ?

**Comment by waghanza** [comment]
Hi @JCgH4164838Gh792C124B5,

> , and it is interesting to see some "raw throughput numbers" for the same synthetic benchmark.

Yes. It will come. It's easy to get this data, but for the moment, I think we have to focus on one thing, at least until we have defined the UI needed / useful.

> a deliberate choice, and if so why ?

Yes. `GET /user/:id` seems to be more used for **real-world** apps (I believe using `/user/:id` over `/user?id=:id` is more used since more cacheable, at least this is the case for me)

**Comment by lukaszlenart** [comment]
Prepared #3005 but didn't test it locally, I mean it works but I didn't perform benchmarking. Not sure if the `config.yaml` is correct.
