### ISSUE TITLE
Docker and Alpine

### ISSUE THREAD

**Issue by proyb6** [the-benchmarker/web-frameworks#2987]
Currently, the benchmark's Dockerfile uses alpine, assume it makes sense to switch to Ubuntu as it's widely used in production?

**Comment by waghanza** [comment]
Sure, all containers use `alpine` (and, spoiler, the next version use `fedora`). The think is we can use `X` or `Y` distributions for any.

However, :
+ their could be compilation issues
+ package names could not have the same name for each providers (next version)
+ ...

The motivation behind this decision is that it `alpine` is **recommanded** for `docker`, and could be considered as a **best-practice**
@see https://news.ycombinator.com/item?id=11000827

However, some languages could **NOT** use `alpine`, for example `swift`
