### ISSUE TITLE
[Clojure] Add Yada

### ISSUE THREAD

**Issue by panesofglass** [the-benchmarker/web-frameworks#3012]
@malcolmsparks would you mind adding (or helping me add) an entry for [yada](https://github.com/juxt/yada)?

**Comment by panesofglass** [comment]
@malcolmsparks I'm new to clojure, and I couldn't determine how to build just a simple yada server from scratch. Edge seems to want me to add a bunch of things to the root of this project, which I'm pretty sure would not be welcome. Any suggestions are welcome.

**Comment by whiplash** [comment]
Can't work on this any sooner than September. Pinging @danielcompton as well.

**Comment by waghanza** [comment]
@danielcompton No need to be sorry :heart: We will leave this issue open, if @malcolmsparks is not explicitly opposed to add https://github.com/juxt/yada `here`

**Comment by panesofglass** [comment]
As I continue to learn more, I'll try to add in a contribution.
