### ISSUE TITLE
bin/neph exception

### ISSUE THREAD

**Issue by i4004** [the-benchmarker/web-frameworks#3028]
Hello! When running `bin/neph [job1]` command with any framework i got exception:

```bash
$ bin/neph csharp.simplify.web
Neph is running (0.2.12) 0%||||||||||||||||||||||||||||||||||||||||||||||||||
-- // --
Neph is running (0.2.12) 0%||||||||||||||||||||||||||||||||||||||||||||||||||
csharp.simplify.web [0/1] ⠠ running (66%) > ../../bin/client --language csharp --framework simplify.web -r GET:/ -r GET:/user/0 -r POST:/user -h `cat ip.txt` -c 144  -c 576  -c 1152
[Error] 'csharp.simplify.web' failed with status code (256)
[Error]  -- STDOUT(.neph/csharp.simplify.web/log/log.out) --
 ---> 8845550065cf
Step 11/12 : ENV COMPlus_TieredCompilation 1
 ---> Using cache
 ---> cce7ae2d8ff0
Step 12/12 : CMD dotnet /usr/src/app/out/web.dll
 ---> Using cache
 ---> 29eee1ecb279
Successfully built 29eee1ecb279
Successfully tagged csharp.simplify.web:latest
Start @ 144
[Error]  -- STDERR(.neph/csharp.simplify.web/log/log.err) --
Unhandled exception: Empty enumerable (Enumerable::EmptyError)
  from ../../../../../usr/share/crystal/src/gc/boehm.cr:110:5 in 'run'
  from ../../tools/src/client.cr:116:1 in '__crystal_main'
  from ../../../../../usr/share/crystal/src/crystal/main.cr:105:5 in 'main'
  from __libc_start_main
  from _start
  from ???
```

Environment:
* WSL 2 Ubuntu 20.04
* Latest Crystal, Docker, Wrk, PostgreSQL

**Comment by waghanza** [comment]
@i4004 you mean you are on windows ? sorry I do not know WSL

**Comment by i4004** [comment]
Yes I am on windows, and using WSL 2, which is like virtual machine for linux.

I am using docker-desktop for windows (it has built-in WSL 2 support) which translates communication with docker from inside WSL to docker on windows.

**Comment by waghanza** [comment]
I'm not sure what going on then ...

I can not support `docker-desktop`. Can you use `docker-machine` ?

-------------
The commands will be more complex (after `docker-machine` setup)
```
docker-machine rm default --force
shards build
bin/make config --driver docker-machine
docker-machine create default
eval $(docker-machine env default) 
export DATABASE_URL=postgresql://postgres@localhost/benchmark
dropdb -U postgres benchmark
createdb -U postgres benchmark
psql -U postgres -d benchmark < .ci/dump.sql
bin/neph csharp.simplify.web --seq 
bin/db to_readme
```
-------------

`docker-machine` and `docker-desktop` are **NOT** the same, and can not support both as of today

**Comment by i4004** [comment]
FYI, so, this is what i discovered:

> I cannot ping my containers🔗
> Docker Desktop for Windows can’t route traffic to Linux containers. However, you can ping the Windows containers.

> I want to connect to a container from Windows
> Port forwarding works for localhost; --publish, -p, or -P all work. Ports exposed from Linux are forwarded to the host.

So, this does work:

```bash
docker run -p 5000:3000 -d csharp.simplify.web
wrk http://127.0.0.1:5000
```

i wil try to launch `web-frameworks` in one of the linux containers (based on some linux base images), not in the WSL itself, to eliminate all issues, cause containers CAN connect to each other.
