### ISSUE TITLE
[PHP] Add http-router

### ISSUE THREAD

**Issue by waghanza** [the-benchmarker/web-frameworks#3061]
Hi @fenric @peter279k,

Would you mind to add (or consent that we add) [http-router](https://github.com/sunrise-php/http-router) in `here` ?

This project compare performance based on 3 routes :

+ `GET` `/`, **SHOULD** return a successful status code and an empty string
+ `GET` `/user/:id`, **SHOULD** return a successful status code and the id
+ `POST` `/user`, **SHOULD** return a successful status code and an empty string

Regards,

**Comment by fenric** [comment]
Hello @waghanza!

Please see the following PR: https://github.com/the-benchmarker/web-frameworks/pull/3065

It's Okay?
