### ISSUE TITLE
Add crow (C++)

### ISSUE THREAD

**Issue by waghanza** [the-benchmarker/web-frameworks#307]
Hi,

It will be interesting to add [Crow](https://github.com/ipkn/crow)

Regards,

**Comment by aichholzer** [comment]
Big fan of crow right here. Looking forward to seeing those results.

**Comment by waghanza** [comment]
@aichholzer @OvermindDL1 any time for a `PR` ?

**Comment by waghanza** [comment]
Hi @ipkn,

Would you mind to add (or consent that we add) [crow](https://github.com/ipkn/crow) in `here` ?

This project compare performance based on 3 routes :

+ `GET` `/`, **SHOULD** return a successful status code and an empt²y string
+ `GET` `/user/:id`, **SHOULD** return a successful status code and the id
+ `POST` `/user`, **SHOULD** return a successful status code and an empty string

Regards,
