### ISSUE TITLE
 [F#] Use CreateDefaultBuilder instead of WebHostBuilder

### ISSUE THREAD

**Issue by waghanza** [the-benchmarker/web-frameworks#3076]
Hi,

Following #3075, I can that  that `WebHostBuilder` is used in

+ [ ] Falco
+ [ ] Giraffe
+ [ ] WebSharper

https://github.com/the-benchmarker/web-frameworks/search?q=WebHostBuilder&unscoped_q=WebHostBuilder

It could be awesome to use this implementation on all `F#` **frameworks**

Regards,

**Comment by panesofglass** [comment]
Agreed. I’ll try to knock this out soon.
