### ISSUE TITLE
[Node.js] Add turbo-http mixed with polka

### ISSUE THREAD

**Issue by qti3e** [the-benchmarker/web-frameworks#308]
It's about `2x` faster than using `polka` with node's http module.
```js
const polka = require('polka');
const turbo = require('turbo-http');
const server = turbo.createServer();

polka({ server })
  .get('/', (req, res) => {
    res.end('');
  })
  .get('/user/:id', (req, res) => {
    res.end(req.params.id);
  })
  .post('/user', (req, res) => {
    res.end('');
  })
  .listen(3000);
```
Also it can be much faster (on my machine it's about `6x` faster than express (without cluster))  if we do something like this:
```js
const cluster = require("cluster");

if (cluster.isMaster) {
  for (let i = 0; i < 8; ++i) {
    cluster.fork();
  }
} else {
const polka = require('polka');
const turbo = require('turbo-http');
const server = turbo.createServer();

polka({ server })
  .get('/', (req, res) => {
    res.end('');
  })
  .get('/user/:id', (req, res) => {
    res.end(req.params.id);
  })
  .post('/user', (req, res) => {
    res.end('');
  })
  .listen(3000);
}
```

**Comment by aichholzer** [comment]
@qti3e -You can nicely wrap this with [@rayo/storm](https://github.com/GetRayo/rayo.js/tree/master/packages/storm) which will do all the correct clustering for you. It will even give you a cluster monitor interface. ;)

**Comment by waghanza** [comment]
it will be interesting to have a `node` **micro-ben hmark** to select which way is more performant :
- pm2
- @rayo/storm
- turbo-http
-  ...

as I try to do here => https://github.com/the-benchmarker/web-frameworks/issues/292

**Comment by aichholzer** [comment]
@qti3e -Did you want to submit a PR for this? -I will review and merge it in once it comes through.
Thank you.

**Comment by qti3e** [comment]
@aichholzer I'll do it : )
But besides making a new directory in `/node`, what files I'm supposed to modify to register the new test?

**Comment by waghanza** [comment]
@qti3e all `app.js` on sub-folder in `node` directory (one subfolder per framework)

**Comment by aichholzer** [comment]
Closing this as the issue has been moved to [this ](https://github.com/the-benchmarker/web-frameworks/pull/329) PR.
