### ISSUE TITLE
[Java] jetty-runner is deprecated ?

### ISSUE THREAD

**Issue by waghanza** [the-benchmarker/web-frameworks#3088]
Hi,

When running `struts2`, I have
```java
WARNING: jetty-runner is deprecated.
         See Jetty Documentation for startup options
         https://www.eclipse.org/jetty/documentation/
```

This affects :
+ [x] struts2
+ [ ] spring-framework

More details on https://www.eclipse.org/jetty/documentation/current/what-jetty-version.html

/cc @lukaszlenart 

Regards,

**Comment by lukaszlenart** [comment]
I have solution ready but also I would like to introduce this change https://github.com/apache/struts/pull/422 to use a plain output instead doing tricks with JSPs ;-)

Btw. I was inspired by you to implement that small test example, so kudos!!!

**Comment by waghanza** [comment]
Feel free to do so. I'm able to review, but not to code

**Comment by waghanza** [comment]
@david-m-s @snicoll @bclozel @jhoeller @sbrannen can `jetty` be embedded in `spring-framework`

**Comment by bclozel** [comment]
I don't understand why I'm being pinged here.
Spring Framework can be deployed in any Servlet container (embedded or not); I'm not familiar with jetty-runner though.

**Comment by waghanza** [comment]
Sorry, if this be convenient for you @bclozel. As you are a very proactive member of `spring-framework`, I have ping you (but let me know if you don't want).

The fact is I try here to compare various frameworks, and as I've no `java` skills, I pinged you.

I prefer to embed any servlet runner (`jettey` or not) to facilitate development of this project, and go to the next step : deploy (in `cloud`) each framework, instead of producing results from local containers ♥️
