### ISSUE TITLE
Choose the fastest php implementation

### ISSUE THREAD

**Issue by waghanza** [the-benchmarker/web-frameworks#309]
Following https://github.com/tbrand/which_is_the_fastest/pull/249#issuecomment-397790448, it'll be great to test `php` implementation

+ [Symfony](https://symfony.com)
+ [Laravel](https://laravel.com)

with new generation servers
+ [Swoole](https://www.swoole.co.uk)
+ [PHP-PM](https://github.com/php-pm/php-pm)

`Nginx` / `php-fpm` was a default choice :stuck_out_tongue: 

@Bonfante if you are interested to see diffs between implementations, feel free to `PR` :heart: we will have to choose the more performant / usable / standard

**Comment by doanguyen** [comment]
Hi,

An update from this issue: I had a micro-benchmark between Swoole Vs Nginx+Php-fpm. Most of the framework written in PHP now is sync so I have no way other than choosing vanilla PHP to perform the benchmark. 

The benchmark workflow is like that:

Apache ab ---> Swoole
Apache ab ---> Nginx ---> PHP Application

I tried to set up Nginx as a reverse proxy on top of Swoole, but It does not work! Pain. Here is the result:

https://gist.github.com/doanguyen/4211d393a975ec361cd1f299182f9859

Conclusion:
Swoole, in fact, faster 16k > 13k fpm, but most of php library is blocking so it's too soon to have it on our stack, yet.

It seems php-pm is very good for managing php process, so I will take a look later.

**Comment by waghanza** [comment]
:tada: I'll be quite happy to see what's happening with those generation of tools

**Comment by waghanza** [comment]
@doanguyen you can also `PR` with https://github.com/php-pm/php-pm-docker

**Comment by waghanza** [comment]
@doanguyen I have tested `php_pm` here => https://github.com/waghanza/http-benchmark/blob/php_pm/php/laravel/Dockerfile

**Comment by doanguyen** [comment]
I've just made a quick test, it eats ram like twice as Chrome or even worse, workers don't seem to restart as they said.

**Comment by waghanza** [comment]
@doanguyen I've create an issue https://github.com/php-pm/php-pm-docker/issues/18 to have some helps / see what's happening

**Comment by waghanza** [comment]
@doanguyen Nop, I use it https://github.com/waghanza/http-benchmark/blob/php_pm/php/laravel/composer.json

**Comment by doanguyen** [comment]
Did you try 
`ppm start --bootstrap=laravel --app-env=prod --logging=0 --debug=0 --workers=20`
yet?

**Comment by doanguyen** [comment]
PHP-PM
```bash
$ wrk -c 10 -d 10s http://172.17.0.2:8080/user/0 -v --timeout 2s --latency
wrk 4.1.0 [epoll] Copyright (C) 2012 Will Glozer
Running 10s test @ http://172.17.0.2:8080/user/0
  2 threads and 10 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   193.17ms  284.81ms   1.20s    80.96%
    Req/Sec   209.65    130.33   670.00     68.60%
  Latency Distribution
     50%   12.97ms
     75%  339.05ms
     90%  692.05ms
     99%  978.06ms
  3675 requests in 10.03s, 1.90MB read
Requests/sec:    366.29
Transfer/sec:    193.74KB
```
with memory consumption
![](https://i.imgur.com/WeI7KYK.png)

Not much better than: nginx+php-fpm

```bash
$ wrk -c 10 -d 10s http://172.17.0.2:8080/user/0 -v --timeout 2s --latency
wrk 4.1.0 [epoll] Copyright (C) 2012 Will Glozer
Running 10s test @ http://172.17.0.2:8080/user/0
  2 threads and 10 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    71.20ms  114.21ms 632.32ms   86.77%
    Req/Sec   173.41     81.91   363.00     61.70%
  Latency Distribution
     50%   21.52ms
     75%   39.95ms
     90%  241.27ms
     99%  507.64ms
  3280 requests in 10.01s, 1.79MB read
Requests/sec:    327.73
Transfer/sec:    183.01KB
```
and memory consumption
![](https://i.imgur.com/hGaGRno.png)

**Comment by doanguyen** [comment]
I think we stick to the nginx+php-fpm since php-pm is leaked in memory, and doesn't seem to fix in short time.

**Comment by waghanza** [comment]
Souds good for me. Thanks for your work
