### ISSUE TITLE
[PHP] Add CodeIgniter4

### ISSUE THREAD

**Issue by KennyClark7** [the-benchmarker/web-frameworks#3124]
Hi @waghanza, can you add [CodeIgniter4](https://github.com/codeigniter4/CodeIgniter4)?

**Comment by waghanza** [comment]
Hi @michalsn,

Would you mind to add (or consent that we add) [CodeIgniter4](https://github.com/codeigniter4/CodeIgniter4) `here` ?

This project compare performance based on 3 routes :

+ `GET` `/`, **SHOULD** return a successful status code and an empty string
+ `GET` `/user/:id`, **SHOULD** return a successful status code and the id
+ `POST` `/user`, **SHOULD** return a successful status code and an empty string

Regards,
