### ISSUE TITLE
[R programming] please add shiny

### ISSUE THREAD

**Issue by vikram-rawat** [the-benchmarker/web-frameworks#3140]
Please add shiny web framework in the list as well. just to see where does R as a language belongs too...

**Comment by waghanza** [comment]
Hi @jcheng5,

Would you mind to add (or consent that we add) [shiny](https://github.com/rstudio/shiny) in `here` ?

This project compare performance based on 3 routes :

+ `GET` `/`, **SHOULD** return a successful status code and an empty string
+ `GET` `/user/:id`, **SHOULD** return a successful status code and the id
+ `POST` `/user`, **SHOULD** return a successful status code and an empty string

Regards,

**Comment by vikram-rawat** [comment]
Please close this ticket. Shiny doesn't work like REST APIs do. So this is impossible to do in shiny.
