### ISSUE TITLE
Remove fasthttprouter  ?

### ISSUE THREAD

**Issue by waghanza** [the-benchmarker/web-frameworks#3150]
Hi,

As @kirillDanshin mentionned, github.com/buaazp/fasthttprouter and github.com/fasthttp/router might be the same project (but only one is maintained).

@savsgio Any thoughts ?

Regards,

**Comment by savsgio** [comment]
Hi @waghanza,

Sorry I didn't see this!

fasthttp/router is the official and maintained router for fasthttp. At first, it was a fork to try to maintained the buaazp/fasthttprouter, but buazzp never answered and continued the developement.

Now fasthttp/router is a reimplementation of the original repository [julienschmidt/httprouter](https://github.com/julienschmidt/httprouter) adapted and improved to fasthttp (does not a fork).

So, maybe you could consider to remove the [buaazp/fasthttprouter](https://github.com/buaazp/fasthttprouter), as @kirillDanshin advise you.

**Comment by waghanza** [comment]
@buaazp is https://github.com/buaazp/fasthttprouter still maintained ?
