### ISSUE TITLE
I didn't test that and then it will use version related to Maven used to build the project.

### ISSUE THREAD

**Issue by waghanza** [the-benchmarker/web-frameworks#3152]
I didn't test that and then it will use version related to Maven used to build the project.

_Originally posted by @lukaszlenart in https://github.com/the-benchmarker/web-frameworks/pull/3132_

**Comment by waghanza** [comment]
I didn't understand

**Comment by lukaszlenart** [comment]
Each Maven version has its own Master pom with some plugins' versions, so if you will build the project using Maven 3.6.3 version, it has `maven-assembly-plugin` in version `2.2-beta-5`

https://github.com/apache/maven/blob/master/maven-model-builder/src/main/resources/org/apache/maven/model/pom-4.0.0.xml#L88-L89

Also see this note
https://github.com/apache/maven/blob/master/maven-model-builder/src/main/resources/org/apache/maven/model/pom-4.0.0.xml#L80-L81

So it's better to define exact version of the plugin in your pom.

**Comment by waghanza** [comment]
Thanks for clarification.

As all frameworks are built by the same `maven` version, I think we could avoid specifying version.

The goal is to ensure feature parity for each `maven` built frameworks
