### ISSUE TITLE
[ R Programming] Please add RestRserve

### ISSUE THREAD

**Issue by vikram-rawat** [the-benchmarker/web-frameworks#3188]
Could you please add RestRserve for benchmarking. 

https://github.com/rexyai/RestRserve

**Comment by waghanza** [comment]
Could you ping the author @vikram-rawat, as I have done for `shiny` ?

**Comment by vikram-rawat** [comment]
https://github.com/dselivanov is the author i guess

**Comment by dselivanov** [comment]
please go ahead, I can help review PR

**Comment by waghanza** [comment]
want to try @vikram-rawat ?

**Comment by vikram-rawat** [comment]
Yes 👍. Gimme some time

**Comment by vikram-rawat** [comment]
This is the code for 3 routes and their results.

https://github.com/vikram-rawat/benchmark_restrserve

Please try it

**Comment by waghanza** [comment]
@vikram-rawat @dselivanov does a `r` based docker image exists ?

**Comment by vikram-rawat** [comment]
Its called rocker. Use the 4.0.2 one the latest version of R

**Comment by waghanza** [comment]
Ok, I'll try using `rocker/r-ver:4.0.2`. As I understand, this only contains `r` **basics**
