### ISSUE TITLE
[Ruby] Fix pakyow

### ISSUE THREAD

**Issue by waghanza** [the-benchmarker/web-frameworks#3191]
Hi @bryanp,

As I understand `pakyow` requires now `mini_racer`

Since this **gem** requires extra dependencies on **alpine**, the build is failing.

Regards,

**Comment by bryanp** [comment]
Yes, Pakyow has required `mini_racer` since the v1.0 release a year ago. I'll dig in this week to see why the build is failing.

**Comment by bryanp** [comment]
@waghanza Can you please point me to the failure that you're seeing? I went looking and couldn't find it.

**Comment by waghanza** [comment]
Sorry for the delay @bryanp. I have not a huge bandwidth for this project this month :stuck_out_tongue: 

I thin the issue is related to `docker`

**Comment by waghanza** [comment]
Seems that `mini_racer` is **NOT** usable (compilation issue) on `alpine`, since `pakyow` rely on `0.2.15`
https://github.com/pakyow/pakyow/blob/6ec68aa0ec7352e4ada704a8fbc238c275d26d47/pakyow-assets/pakyow-assets.gemspec#L30

btw, `mini_racer` `0.3.1` is :ok_hand: on `alpine`
