### ISSUE TITLE
[Feature Request]: Use wrk binaries?

### ISSUE THREAD

**Issue by dalisoft** [the-benchmarker/web-frameworks#3196]
Hi @waghanza 

How about using binary file of **wrk** instead of building?
I made own fork @wg's **wrk** with auto-binary generating.

https://github.com/dalisoft/wrk and only last release has binary https://github.com/dalisoft/wrk/releases/tag/v4.1.1

I only changed build process as i'm need **wrk** binary without any dependencies in Linux

**Comment by waghanza** [comment]
Hi @dalisoft,

What will be the benefits ? Despite of that their is the architecture to take in count

**Comment by dalisoft** [comment]
For me it’s time saver and use binary directly without any additional steps. 
I always choose binary over built from sources, so i did think you also may choose this

**Comment by waghanza** [comment]
Ah, understood. I think, btw, it is not very important (I mean spending time) since I'll make a script to automatize everything

**Comment by dalisoft** [comment]
Yea, then it’s not important
