### ISSUE TITLE
[Javascript] Not more maintained: nanoexpress-pro

### ISSUE THREAD

**Issue by mrddter** [the-benchmarker/web-frameworks#3206]
Hi 👋 

just for note, sadly [nanoexpress-pro](https://github.com/nanoexpress/pro) is not more maintained. 
More info here:

https://github.com/nanoexpress/pro/issues/64
https://t.me/nanoexpress/18

**Comment by waghanza** [comment]
Hi @dalisoft,

We then have to remove it from `here` ;-)

Thanks for notice @mrddter.

Regards,

**Comment by dalisoft** [comment]
Hi @waghanza 

Yes, we need remove it from here as project isn't maintaining anymore.

**Comment by dalisoft** [comment]
@waghanza Can we return `nanoexpress` to benchmark?
I migrated `nanoexpress-pro` to `nanoexpress`.

As currently have some time to maintain package, configured auto security patches which reduces my time spent so i can think can maintain this repo easier.

**Comment by dalisoft** [comment]
@waghanza You can see current project at [here](https://github.com/nanoexpress/nanoexpress)
