### ISSUE TITLE
Not django-ninja

### ISSUE THREAD

**Issue by MajidHeydari** [the-benchmarker/web-frameworks#3208]
Not django-ninja rest framework benchmark

**Comment by waghanza** [comment]
Hi @vitalik,

Would you mind to add (or consent that we add) [django-ninja](https://github.com/vitalik/django-ninja) in `here` ?

This project compare performance based on 3 routes :

+ `GET` `/`, **SHOULD** return a successful status code and an empty string
+ `GET` `/user/:id`, **SHOULD** return a successful status code and the id
+ `POST` `/user`, **SHOULD** return a successful status code and an empty string

Regards,

**Comment by waghanza** [comment]
Thanks @MajidHeydari for raising this. Let's wait for explicit consent 10 days, and start to implement it :heart:

**Comment by vitalik** [comment]
@waghanza @MajidHeydari sure, will try to set it up

**Comment by vitalik** [comment]
@waghanza PR( #3228) created, please check
