### ISSUE TITLE
We Need Logo!

### ISSUE THREAD

**Issue by tbrand** [the-benchmarker/web-frameworks#323]
Now we've migrate the repo into new one.
I would like to start our branding from the logo images.
If you guys have ideas for it, please post comments below. :pray:

Thanks.

**Comment by aichholzer** [comment]
![image](https://user-images.githubusercontent.com/1402711/44074043-6a6ec75a-9fda-11e8-86ab-cebd18068dff.png)

👍

**Comment by waghanza** [comment]
@tbrand OK to use this one ?

**Comment by tbrand** [comment]
Yup. But would like to keep opening the issue.

**Comment by aichholzer** [comment]
@waghanza -I can provide a high resolution version. Where do I upload/send it to?

**Comment by waghanza** [comment]
@aichholzer You can send me by **wetransfert** (or any other service like that), or I can give you rights to you so you can upload.

**Comment by aichholzer** [comment]
Yeah, if you want me as a project contributor (as discussed in another thread), you can grant me collaborator rights and I will take care up setting the logo in place.

**Comment by waghanza** [comment]
I've sent you an invitation

I am not sure if you can upload a logo as a **member**, let me know if not 🙂

**Comment by waghanza** [comment]
i've granted you owner rights

**Comment by aichholzer** [comment]
Done. You can give me back normal rights, if you want or leave it as is. As you wish.

**Comment by waghanza** [comment]
@aichholzer I can also leave it as is ...

Viewing what badges you have on `rayo` `README` ....

@tbrand Any ideas more to enhance communication here

I intennd to create a `gfunction` in `crystal` to keep dependencies update (it will be mainly for me a way to learn `crystal`)

**Comment by tbrand** [comment]
I've never heard the gfunction but sounds good. :+1:
Why don't you create a github pages for us?

**Comment by waghanza** [comment]
`gfunction` are for **Google** what `lambda` is for **AWS**

Communication via a blog (or a github page) is on my roadmap, but I prefer communicate with the results (when they will be ready for production)

**Comment by tbrand** [comment]
Twitter?

**Comment by waghanza** [comment]
Yeah !!!

But probably after cloudification.

What do you think ?

Cloudification could tale times (probably before it could be available as christmas gift)

**Comment by waghanza** [comment]
@tbrand I think, we should create a roadmap with those ideas

**Comment by aichholzer** [comment]
I created this: https://github.com/orgs/the-benchmarker/teams/web-frameworks
Team discussions are good and can be kept all in one place.
Thoughts?

**Comment by tbrand** [comment]
OK. But still welcome candidates of new icons.
