### ISSUE TITLE
Update benchmarks

### ISSUE THREAD

**Issue by dominikzogg** [the-benchmarker/web-frameworks#3249]
Hello @waghanza, would love to see the newest scores.

**Comment by waghanza** [comment]
Me too. I can't right now. It will be made next month (somewhere around the first of September)

**Comment by laylatichy** [comment]
Hi @waghanza any news on stable connection on your end? Didn't want to open a new issue so just asking here how far we are from results update ;)

**Comment by dominikzogg** [comment]
Any news on that? Any possibility to somehow support a new run?

**Comment by laylatichy** [comment]
Bump @waghanza any news or help needed?
