### ISSUE TITLE
[Javascript] Add Natural-framework

### ISSUE THREAD

**Issue by jesusvilla** [the-benchmarker/web-frameworks#3301]
Hi,

Can you add [natural-framework](https://github.com/jesusvilla/natural/) please?

For now can you just add your router (directory naturaljs-router in the javascript folder)?
## Installation
```
$ npm i -S natural-framework
```

## Use
```js
const NaturalRouter = require('natural-framework/lib/router')
// const path = require('path')

function createRoutes (router) {
  router
    .get('/', (_, response) => {
      response.end('')
    })
    .get('/user/:id', (request, response) => {
      response.end(request.params.id)
    })
    .post('/user', (request, response) => {
      response.end('')
    })
}

async function bootstrap () {
  const router = new NaturalRouter({
    // type: 'uws', // 'uws' or 'node'
    /* ssl: {
      key: path.join(__dirname, './security/cert.key'),
      cert: path.join(__dirname, './security/cert.pem')
    } */
  })
  try {
    createRoutes(router)
    const port = await router.listen(3000)
    console.log(`Listen http://localhost:${port}`)
  } catch (error) {
    console.log('Error:', error)
  }
}

bootstrap()
```

**Comment by jesusvilla** [comment]
soon it will be called ``@natural/router``, I'm working on it, but it will be later, that's why i ask you to add it as ``naturaljs-router`` please.

**Comment by schamberg97** [comment]
Added my own framework that borrows heavily from Express & my favourite Restana, hope to bring useful PRs to your project and maybe borrow a few ideas here and there (mindful of license incompatibility, ofc) 😇

**Comment by schamberg97** [comment]
I’ll try to help out with this tomorrow, if I find time (Master’s studies until 5pm)
