### ISSUE TITLE
Jester failure

### ISSUE THREAD

**Issue by waghanza** [the-benchmarker/web-frameworks#331]
Hi @dom96,

`jester` is failing on our last run, https://travis-ci.com/the-benchmarker/web-frameworks/jobs/142574924

Could you get me a quick feedback on the error message on this line https://travis-ci.com/the-benchmarker/web-frameworks/jobs/142574924#L754 ?

Regards,

**Comment by dom96** [comment]
That's really strange. All I can say is: the dockerfile for techempower is working fine. Try checking what the differences are?

**Comment by waghanza** [comment]
The only diff I found (on `Dockerfile`) is that techempower copy all file in dir, and we only pick somes
+ server_nim_jester.nim
+ server_nim_jester.nimble

I've not enough skill to know what files are needed :stuck_out_tongue: 

The error is :

~~~nim
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
~~~

**Comment by dom96** [comment]
Yeah, that error isn't very helpful sadly. Try using techempower's dockerfile exactly?
