### ISSUE TITLE
[Python] if possible add benchmarks of oreoweb framework 

### ISSUE THREAD

**Issue by harishsg99** [the-benchmarker/web-frameworks#3326]
https://github.com/harishsg99/Oreoweb

**Comment by waghanza** [comment]
Hi @harishsg99,

Would you mind to add (or consent that we add) [Oreoweb](https://github.com/harishsg99/Oreoweb) in `here` ?

This project compare performance based on 3 routes :

+ `GET` `/`, **SHOULD** return a successful status code and an empty string
+ `GET` `/user/:id`, **SHOULD** return a successful status code and the id
+ `POST` `/user`, **SHOULD** return a successful status code and an empty string

Regards,
