### ISSUE TITLE
Introduce rosencrantz

### ISSUE THREAD

**Issue by waghanza** [the-benchmarker/web-frameworks#335]
+ Language : Nim
+ Repo : https://github.com/andreaferretti/rosencrantz
+ Author : @andreaferretti

**Comment by andreaferretti** [comment]
Let me know if you need any help for this!

**Comment by waghanza** [comment]
@andreaferretti sure, if you have time to implement a webserver folowing the rule :

+ GET '/' return status code 200 with empty body
+ GET '/user/:id' return status code 200 with the id
+ POST '/user' return status code 200 with empty body

it will be awesome :heart: 

I have to `nim` skills, but if you don't I will try to learn :stuck_out_tongue_winking_eye:

**Comment by Willyboar** [comment]
Added at #2910
