### ISSUE TITLE
Benchmarks are fairly old

### ISSUE THREAD

**Issue by rishavs** [the-benchmarker/web-frameworks#3377]
The last benchmark (according to the Readme) apparently ran on 2020-08-06.

a lot of frameworks and updates have been added since then and it would be welcome to see the latest results.

Also, what is the general frequency of running the suite? Seeing the number of updates, i think it would be great to have it run at least once a week.

**Comment by laylatichy** [comment]
yeah me, and @dominikzogg tried to get some info on closed issue #3249

hope to see results updated as well

**Comment by waghanza** [comment]
Yes, sorry for the convenience (personal issues).

I was hoping I can run again those benchmarks this month. Let me come with answers in a week or so ❤️

**Comment by rishavs** [comment]
If there is something we can do to help, do tell. And hope everything is fine with you and your loved ones in these tough times.

**Comment by waghanza** [comment]
Thanks for those kind words. I've found a temporary solution to run those benchmarks.

However, the long time purpose is to run benchmark in a standalone way (CI will compute results instead of my home computer 😄)

**Comment by schamberg97** [comment]
Hey there! Are there any updates on this?

**Comment by laylatichy** [comment]
@schamberg97 related to pull request #3381 

I think it's almost done, this morning I saw a few issues with c, cpp and java builds, 

pipeline is still going tho - https://the-benchmarker.semaphoreci.com/workflows/691a1c41-af04-41c5-9ee6-aebe0b399fa7?pipeline_id=8506666a-68ff-42ac-b99c-1af7b7451beb

so will check in 1hr ish if anything failed

**Comment by waghanza** [comment]
pipeline is OK now https://the-benchmarker.semaphoreci.com/workflows/691a1c41-af04-41c5-9ee6-aebe0b399fa7?pipeline_id=8506666a-68ff-42ac-b99c-1af7b7451beb, but refactor is needed

sometimes this week, results will be updated

**Comment by waghanza** [comment]
I have merged #3381. I'll update / merge some pending PRs, and run results today, will be available tomorrow. Keep posted.

**Comment by waghanza** [comment]
@rishavs @laylatichy @ookangzheng @dominikzogg @schamberg97 results are updated. I'll try to update on a week basis (until we can have a real-time benchmark)

**Comment by dominikzogg** [comment]
@waghanza great work, thank you!
