### ISSUE TITLE
[PHP] Add Unic Framework

### ISSUE THREAD

**Issue by rajkumardusad** [the-benchmarker/web-frameworks#3385]
Hey there can anyone add [Unic framework](https://github.com/unicframework/unic).

**Comment by waghanza** [comment]
feel free to open a `PR` @rajkumardusad 

------------
This project compare performance based on 3 routes :

+ `GET` `/`, **SHOULD** return a successful status code and an empty string
+ `GET` `/user/:id`, **SHOULD** return a successful status code and the id
+ `POST` `/user`, **SHOULD** return a successful status code and an empty string

**Comment by rajkumardusad** [comment]
Hey @waghanza i can't add this project, so please can add it or test the performance.

**Comment by waghanza** [comment]
Why close ?

**Comment by rajkumardusad** [comment]
Hey this framework is re-named as unic.
https://github.com/rajkumardusad/unic

**Comment by waghanza** [comment]
Hi @rajkumardusad,

It could be useful for me if `unic` is available in packagist repository.

Regards,

**Comment by rajkumardusad** [comment]
Ok i will try.

**Comment by rajkumardusad** [comment]
> Hi @rajkumardusad,
> 
> It could be useful for me if `unic` is available in packagist repository.
> 
> Regards,

Hey @waghanza now unic framework is available at packagist.
`$ composer create-project rajkumardusad/unic test-project`

**Comment by rajkumardusad** [comment]
Please add this framework.

**Comment by waghanza** [comment]
I have not enough bandwith at the moment, will do later ... not sure when

But, why can't you add it yourself ?

**Comment by rajkumardusad** [comment]
> I have not enough bandwith at the moment, will do later ... not sure when
> 
> But, why can't you add it yourself ?

I can't add, because i don't have pc.

**Comment by waghanza** [comment]
ah, ok @rajkumardusad. be sure someone will add it before any communications about this project

**Comment by rajkumardusad** [comment]
Thank you so much

**Comment by waghanza** [comment]
@leocavalcante @sy-records want to try ?

**Comment by sy-records** [comment]
> Hey @waghanza i can't add this project, so please can add it or test the performance.

Why can't you? Anyone can submit a PR.

**Comment by rajkumardusad** [comment]
> > Hey @waghanza i can't add this project, so please can add it or test the performance.
> 
> Why can't you? Anyone can submit a PR.

Because i don't have a pc right now, so please if anyone add this framework.
