### ISSUE TITLE
add quart

### ISSUE THREAD

**Issue by greed2411** [the-benchmarker/web-frameworks#341]
+ Language : python
+ Repo : [quart](https://gitlab.com/pgjones/quart)
+ Author : [pgjones](https://gitlab.com/pgjones)

**Comment by waghanza** [comment]
@greed2411 we will have to choose between
+ Hypercorn
+ Uvicorn
+ Daphne
to replace frontend like `gunicorn` (according to the documentation, it is not recommanded to run on **production** with `built-in` server)

**Comment by greed2411** [comment]
@waghanza just discovered this:

```
Quart can be installed via pipenv or
pip,
$ pipenv install quart
$ pip install quart

and requires Python 3.7.0 or higher.
```

over [here](https://gitlab.com/pgjones/quart). you okay with 3.7?

**Comment by waghanza** [comment]
Sure, we could use it, at least on Docker, 3.7 is not available on AWS (too early stage) and I do not think either on digital ocean, but it's ok for me
