### ISSUE TITLE
[Vapor] Compilation issue

### ISSUE THREAD

**Issue by waghanza** [the-benchmarker/web-frameworks#3442]
Hi @0xTim,

When building https://github.com/vapor/vapor with `swift build -c release` (inside a container), I have
```
Resolving https://github.com/apple/swift-nio-extras.git at 1.7.0
/usr/bin/ld.gold: fatal error: out of file descriptors and couldn't close any
clang-10: error: linker command failed with exit code 1 (use -v to see invocation)
0: error: link command failed with exit code 1 (use -v to see invocation)
```

The container definition is :
```dockerfile
FROM swift:5.3

RUN apt -y update
RUN apt -y install libssl-dev zlib1g-dev libcurl4-openssl-dev uuid-dev

WORKDIR /usr/src/app

COPY Package.swift ./
COPY Sources/ ./Sources/
```

This container use `swift` **5.3** and `clang` **10**

Regards,

**Comment by 0xTim** [comment]
Hmm that's a weird one. I've seen this a couple of times with very large projects but never Docker since it usually shares file descriptors with the host system. I'm assuming it doesn't work after a restart or closing other containers? What's the output of `ulimit -a`?

**Comment by waghanza** [comment]
>  I'm assuming it doesn't work after a restart or closing other containers?

Indeed. Either restart or cleaning docker containers show the same 

> What's the output of ulimit -a?

```
core file size          (blocks, -c) unlimited
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 3724
max locked memory       (kbytes, -l) 64
max memory size         (kbytes, -m) unlimited
open files                      (-n) 1048576
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) unlimited
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited
```

PS : The host machine is a 8 CPU / 16 Gb RAM / fedora 32

**Comment by waghanza** [comment]
I think this was related to containers and the built-in tool in use `neph`.

Now as we use `make` (everything is sequential, and not process on-hold), everything seems OK.

Next run (monday or tuesday), will update results with https://github.com/vapor/vapor results
