### ISSUE TITLE
Choosing a license

### ISSUE THREAD

**Issue by waghanza** [the-benchmarker/web-frameworks#346]
Hello,

I think we should license our work, at least to be clear about the intention / usages we think about

@tbrand @OvermindDL1 @aichholzer any thoughts ?

Regards,

**Comment by aichholzer** [comment]
To me a no-brainer; `MIT` license.

**Comment by tbrand** [comment]
Agree with @aichholzer

**Comment by waghanza** [comment]
@OvermindDL1 it could be useful not to limitate the usage to public. 

I mean it could be useful to use this project to take some business decision, so in a **private** domain :stuck_out_tongue:

**Comment by waghanza** [comment]
I've proposed #416

@aichholzer @tbrand are OK

what about @vladfaust @OvermindDL1. is a `mit` licensing OK for you ?

**Comment by tbrand** [comment]
Yup.

**Comment by vladfaust** [comment]
I haven't commited a line of code for myself, so I cannot vote on the license :) However, if you select MIT, anyone could use this project closed source and / or for business purposes without mentioning original authors.

**Comment by OvermindDL1** [comment]
>  it could be useful not to limitate the usage to public.

Public domain (one of the CC-* licenses) is not limited to the public, it is do anything with it you want for any purpose.

If worried about copyrights or anything then use Apache2, it's basically MIT but with explicit patent and copyright and such provisions (hence why it's pretty much taking over as the de-facto open source license anymore).

**Comment by waghanza** [comment]
@vladfaust sure ? The `MIT` licensing require a copyright notice ;-) 

@see https://choosealicense.com/licenses/mit

for me any license is OK except those with same license requirement 
+ MPL 2.0
+ GPL 3.0
+ AGPL 3.0
+ LGPL 3.0

I'll update the license term after any **consensus**

**Comment by vladfaust** [comment]
@waghanza yes, you're right. MIT license requires copyright and other notices to remain intact. However, it doesn't restrict the software to be open-source. I'd go with MIT in this case

**Comment by waghanza** [comment]
I hav explicit consent from @tbrand @vladfaust @aichholzer everyone OK ?

@OvermindDL1 ok ?

**Comment by waghanza** [comment]
so, here we go :tada:
