### ISSUE TITLE
[Clojure] Update luminus to 3.88

### ISSUE THREAD

**Issue by waghanza** [the-benchmarker/web-frameworks#3470]
Hi @yogthos,

In the homepage, we specify that `luminus` is is **1.0**.

Is this version correct ?

Regards,

/cc @whiplash

**Comment by mfirry** [comment]
https://github.com/the-benchmarker/web-frameworks/blob/master/clojure/luminus/project.clj#L9-L11

**Comment by whiplash** [comment]
Hmmm https://github.com/the-benchmarker/web-frameworks/blob/master/clojure/luminus/project.clj#L9-L11

**Comment by whiplash** [comment]
Also I cannot find any release here https://github.com/luminus-framework/luminus/releases nor tags with meaningful version numbers.

**Comment by waghanza** [comment]
and also could not find any viable (at least understandable for me) information on https://clojars.org

**Comment by whiplash** [comment]
Only thing might be this: https://github.com/luminus-framework/luminus/blob/master/project.clj#L1

**Comment by yogthos** [comment]
@whiplash that repo is for the website, the version for the template is tracked here https://github.com/luminus-framework/luminus-template and the latest published artifact is here https://clojars.org/luminus/lein-template

Unfortunately, I don't recall what version the template was on when it was added to the benchmarks. Would probably be the easiest if I do a PR for the latest version.

**Comment by waghanza** [comment]
@yogthos I meant in which version is the whole `luminus` framework ?

The home page say luminus is in 1.0 (which I think is incorrect). As far as I understand `luminus-template` version is the same as `luminus` version

**Comment by whiplash** [comment]
thanks @yogthos please feel free to PR what's been done.

**Comment by yogthos** [comment]
@waghanza right, the template version is the current version for the framework. The `luminus` repo is just the documentation site.

**Comment by waghanza** [comment]
ok @yogthos the version of https://clojars.org/luminus/lein-template should then be displayed on the homepage 😛

**Comment by yogthos** [comment]
It's a bit more complicated than that because the docs on the site apply to a major version number, while minor version numbers represent minor changes such as library updates. This hasn't really come up as a problem until now. :)

**Comment by waghanza** [comment]
ah understood. however to be fair (with you and your contributors), I have to communicate the right version number we are using here. then I must understand, how this version is made.

We have for example a framework driven by its module in https://github.com/spider-gazelle/action-controller/blob/947eeb2d2b45d93dba4eb80bc5302c70ccc97fca/shard.yml#L2 and some driven by an indication in a monorepo https://github.com/rails/rails/blob/cf4fa5caf39f1271d3f8c4c9774e874430ea0f68/version.rb#L6

But note that we only display `X.Y`, not the patch level (generally dependencies bump are patch levels)

**Comment by yogthos** [comment]
It would probably make sense to use template version that the project is generated against. I've added a new key to the project file so that it can be parsed out. I'll have the template inject the version going forward.
