### ISSUE TITLE
Add aiohttp

### ISSUE THREAD

**Issue by eirnym** [the-benchmarker/web-frameworks#348]
+ Language : Python
+ Repo : https://github.com/aio-libs/aiohttp/
+ Author : https://github.com/asvetlov 
+ Documentation: https://docs.aiohttp.org/

**Comment by waghanza** [comment]
@greed2411 It seems that you like `python`. Do you mind if I assign you `python ` **implementations** ?

**Comment by greed2411** [comment]
Alright. Thanks @waghanza but it needs to wait for few hours.

**Comment by waghanza** [comment]
@greed2411 sure ... not a hury ...

This organisation let me focus on ruby stuff 😎
