### ISSUE TITLE
[Scala] Lagom

### ISSUE THREAD

**Issue by fkromer** [the-benchmarker/web-frameworks#3563]
Would be great to include [Lagom](https://www.lagomframework.com/).

**Comment by waghanza** [comment]
Hi @fkromer,

Thanks for the idea. 

We want to ask for explicit consent (or 10 days without any opposition) to start implementing.

-----------

Hi @ignasi35 @octonato @marcospereira ,

Would you mind to add (or consent that we add) [lagom](https://github.com/lagom/lagom) in `here` ?

This project compare performance based on 3 routes :

+ `GET` `/`, **SHOULD** return a successful status code and an empty string
+ `GET` `/user/:id`, **SHOULD** return a successful status code and the id
+ `POST` `/user`, **SHOULD** return a successful status code and an empty string

Regards,

**Comment by octonato** [comment]
I have no objections, but it's important to understand that Lagom is not a web-framework, so I think the comparison with others may not be that interesting. 

For instance, although it's possible to call Lagom using a REST API, that's not the goal. Behind Lagom implements it's own binary typed API, on top of REST and WebSocket indeed, but there are some layers of indirection. 

Moreover, Lagom builds on top of Play that builds on top of Akka Http. So, what is the goal of such benchmarking?

**Comment by fkromer** [comment]
@octonato You are probably right. The overhead potentially added by Lagom on top of Play/Akka http should be neglect-able. I added the request when I was not aware of the fact that only REST is considered in this repo.

**Comment by waghanza** [comment]
The implementation here is indeed a kind of REST @fkromer . Comparing this with other communications protocol (RPC for exemple) is not vert fair. 

As @octonato say, `lagom` is probably better not to ne added here.

I'm then closing this issue.

Thanks btw for proposal
