### ISSUE TITLE
[C#] Microdot

### ISSUE THREAD

**Issue by fkromer** [the-benchmarker/web-frameworks#3564]
Would be great to add [Microdot](https://github.com/gigya/microdot).

**Comment by waghanza** [comment]
Hi @fkromer,

Thanks for the idea. 

We want to ask for explicit consent (or 10 days without any opposition) to start implementing.

-----------

Hi @bronsh @talweiss1982 @daniellm @yonatan-d-sap @achirlin,

Would you mind to add (or consent that we add) [microdot](https://github.com/gigya/microdot) in `here` ?

This project compare performance based on 3 routes :

+ `GET` `/`, **SHOULD** return a successful status code and an empty string
+ `GET` `/user/:id`, **SHOULD** return a successful status code and the id
+ `POST` `/user`, **SHOULD** return a successful status code and an empty string

Regards,

-----
/cc @panesofglass

**Comment by daniellm** [comment]
@waghanza No objection, but Microdot is not a web framework. It does not support GET or POST of resources such as /user/:id . Instead, it expects a very specific json-over-http RPC request format.

**Comment by waghanza** [comment]
Thanks @daniellm. Introducing `microdot` is then for this project, then @fkromer

**Comment by fkromer** [comment]
@waghanza @daniellm Did not know that it's about RESTful API endpoints only. Sorry.
