### ISSUE TITLE
Use community standard for code design

### ISSUE THREAD

**Issue by waghanza** [the-benchmarker/web-frameworks#357]
Hi,

This project target **performance comparison** at the main idea, but **learning** **COULD** be a `great` thing :heart: 

I know some languages, but I have no idea of any practices is somes, like `C#`

| Language | Standard | Tool |
| ------------- | ----------- | ------ |
| C++ | ClangFormat | [ClangFormat](https://clang.llvm.org/docs/ClangFormat.html) |
| C# | ? | ? |
| Crystal | Language design | Built-in tool |
| Nim | ? | ? |
| Java | Google's Coding style | [GoogleJavaFormat](https://github.com/google/google-java-format) |
| Python | [Community standard](http://pycodestyle.pycqa.org/) | [AutoPEP8](https://github.com/hhatto/autopep8) |
| Elixir | Built-in | `mix format` |
| GO | Built-in tool | go format |
| Node | [StandardJS](https://standardjs.com) | [ESLint](https://eslint.org) |
| PHP | [PSR1](https://www.php-fig.org/psr/psr-1), [PSR2](https://www.php-fig.org/psr/psr-2) | [PHPCsFixer](https://github.com/FriendsOfPHP/PHP-CS-Fixer)
| Ruby | Community standard | [Rufo](https://github.com/ruby-formatter/rufo)|
| Rust | Built-in | rustfmt |
| Scala | [`scalafmt`](https://scalameta.org/scalafmt/) |  [`scalafmt`](https://scalameta.org/scalafmt/) |
| Swift | [SwiftLint](https://github.com/realm/SwiftLint) | [SwiftLint](https://github.com/realm/SwiftLint) |

Any thought ?

**Comment by OvermindDL1** [comment]
Of the languages I know that are `?` above and where the formatters are often used:

* C++: [ClangFormat](https://clang.llvm.org/docs/ClangFormat.html) : (part of clang) : Standard setup is pretty well 'accepted' in the C++ world but it is entirely configurable
* Java:  [GoogleJavaFormat](https://github.com/google/google-java-format) : Gotten popular recently, it follows Google's Coding style
* Elixir:  Built-in, just run `mix format` (`mix` is Elixir's built-in build tool, can also access from in-language via `Code.format_{file|string}!(...)`), might need a `.formatter.exs` to exist to specify 'what' to format, it is not configureable at all, all it's content needs to be is just:
  ```elixir
  [
    inputs: [
      "mix.exs",
      "{config,lib,test,mix}/**/*.{ex,exs}"
    ]
  ]
  ```
* Scala:  [`scalafmt`](https://scalameta.org/scalafmt/) : It's a single line in the scala build file away to acquire it, it is decently configurable though.

I think this is a good idea though.

**Comment by waghanza** [comment]
Yeah ! ! ! :tada: 

I'll add this to the list (as a reminder for me)

**Comment by waghanza** [comment]
@dom96 @thiamsantos @kiliankoe @tanner0101 @mattzink Any ideas for missing tools ?

**Comment by OvermindDL1** [comment]
I don't think `scalafmt` is built-in, just adding it to a project dependency will acquire it, let me check...

Correct, it's not built-in, the line to add to the build file is like `addSbtPlugin("com.lucidchart" % "sbt-scalafmt" % "<version>")` or adjust for gradle or whatever build system is used (`sbt` is the scala standard build system, stands for Simple Build Tool, but scala works with any jvm build system just like sbt works on any jvm language).

**Comment by tanner0101** [comment]
If I understand this correctly, the equivalent tool in Swift would be [SwiftLint](https://github.com/realm/SwiftLint)

**Comment by waghanza** [comment]
The **main** subject `here` is to embrace some standard to keep code base as clean as possible

There is two way to do this :
* Requiring `contributors` to clean there code **before** any `PR`
* Requiring `maintainers` to clean any `PR`

I vote for the 2nd solution

However, doing this is a dead-end (because of time/investment requirements). I like the idea of clean after contribution (it let create a larger community), but manual cleaning is very hard.

I suggest using a service for this. I've identify 3 tools :
+ https://ebertapp.io/
+ https://styleci.io/
+ https://houndci.com/

My idea is to use the 3, but for different languages (all are configurable for this) in order to avoid duplicates ...

What do you think ?

**Comment by OvermindDL1** [comment]
I'd just automate source code formatting via a travis task, have it commit back if any changes were done.

**Comment by waghanza** [comment]
it could be that, but I think `CI` are not made for that

I mean, using travis to push inside github appears to me weird. I prefer considering github as a hub, where `PR` are reviewed by any human (learning is great :heart:)

**Comment by ohler55** [comment]
Personally I prefer the Mozilla style for C in the ClangFormat if forced to make a choice. In general I fall in the category of giving folks some freedom in their style as long as it is consistent. Writing code is an art and can be very personal. It's a pity to force developers into a narrow tightly controlled box.

**Comment by waghanza** [comment]
Perhaps activating  `restyled ` could be :+1: https://github.com/restyled-io/restyled.io/wiki/Available-Restylers#available-now

+ `ClangFormat` => https://github.com/restyled-io/restyled.io/wiki/Available-Restylers#clang-format 
   + `C`
   + `C++`
+ `GoogleJavaFormat` => https://github.com/restyled-io/restyled.io/wiki/Available-Restylers#google-java-format
   + `Java`
+ `Black` => https://github.com/restyled-io/restyled.io/wiki/Available-Restylers#black
   + `Python`
+ `Rubocop` => https://github.com/restyled-io/restyled.io/wiki/Available-Restylers#rubocop
    + `Ruby`
+ `RustFmt` => https://github.com/restyled-io/restyled.io/wiki/Available-Restylers#rustfmt
    + `Rust`
+ `PHPCsFixer` => https://github.com/restyled-io/restyled.io/wiki/Available-Restylers#php-cs-fixer
   + `PHP`

@OvermindDL1 @whiplash what do you think of using https://github.com/lspitzner/brittany for  `haskell` ?

**Comment by whiplash** [comment]
or https://github.com/tweag/ormolu for `Haskell`

**Comment by OvermindDL1** [comment]
I haven't tried any haskell formatter so I can't really comment on them...
