### ISSUE TITLE
[Nim] add Prologue

### ISSUE THREAD

**Issue by ITwrx** [the-benchmarker/web-frameworks#3576]
https://github.com/planety/prologue

**Comment by waghanza** [comment]
Hi @ITwrx,

Thanks for the idea. 

We want to ask for explicit consent (or 10 days without any opposition) to start implementing.

-----------

Hi @xflywind ,

Would you mind to add (or consent that we add) [prologue](https://github.com/planety/prologue) in `here` ?

This project compare performance based on 3 routes :

+ `GET` `/`, **SHOULD** return a successful status code and an empty string
+ `GET` `/user/:id`, **SHOULD** return a successful status code and the id
+ `POST` `/user`, **SHOULD** return a successful status code and an empty string

Regards,

--------
/cc @whiplash

**Comment by waghanza** [comment]
@ITwrx you can start this implementation, if you want
