### ISSUE TITLE
Fast-http-server for Crystal

### ISSUE THREAD

**Issue by proyb6** [the-benchmarker/web-frameworks#360]
I suggest we could add in this in the benchmark.

+ Language : Crystal
+ Repo : https://github.com/sdogruyol/fast-http-server
+ Author : https://github.com/sdogruyol/

**Comment by waghanza** [comment]
@proyb6 Thanks for your contribution. This project is not **static** server ?

**Comment by proyb6** [comment]
It’s serving static files, which would probably be useful for a separate categories on static benchmark.

**Comment by waghanza** [comment]
Ok. I'll close
