### ISSUE TITLE
[C++] Add µWebSockets

### ISSUE THREAD

**Issue by cybertelx** [the-benchmarker/web-frameworks#3615]
µWebSockets is a fast WebSocket server which can also serve HTTP requests.

**Comment by waghanza** [comment]
Hi @cybertelx,

Thanks for your proposal. 

However, `µWebSockets` is not a **framework** (mostly a ** library**). It is already in this list via https://github.com/jkyberneees/low-http-server for example.

I prefer, for the moment, to focus on **frameworks**

Regards,
