### ISSUE TITLE
Add nawa

### ISSUE THREAD

**Issue by waghanza** [the-benchmarker/web-frameworks#3634]
Hi @jatofg,

Would you mind to add (or consent that we add) [nawa](https://github.com/jatofg/nawa) in `here` ?

This project compare performance based on 3 routes :

+ `GET` `/`, **SHOULD** return a successful status code and an empty string
+ `GET` `/user/:id`, **SHOULD** return a successful status code and the id
+ `POST` `/user`, **SHOULD** return a successful status code and an empty string

Regards,

**Comment by jatofg** [comment]
Hi, I've looked into this, but couldn't find out how to run the benchmark. Are there instructions somewhere?

Alternatively, I could just open a PR analogous to other frameworks and leave it to you to test whether it works.

**Comment by waghanza** [comment]
Yep. Sure. The documentation is not written, yet. 
Just open a PR I will take care of the rest
