### ISSUE TITLE
Add php8 + jit

### ISSUE THREAD

**Issue by alexpts** [the-benchmarker/web-frameworks#3635]
PHP 8 is stable version and has more performance with jit

**Comment by waghanza** [comment]
Hi @alexpts,

A PR has been started in https://github.com/the-benchmarker/web-frameworks/pull/3606. Feel free to give any kind of feedback.

Please notice that PHP 8 will be used when suitable for production. I mean the idea of this project is to compare frameworks on a real life environment (I'm not sure that php 8 is widely spread, yet)

**Comment by alexpts** [comment]
We already use php8 + jit on production :).
I follow to  #3606 (need enable jit also)

**Comment by waghanza** [comment]
> We already use php8 + jit on production :).

Your feedback is appreciated then. The idea is to promote this when it will be widely used. I am not in `php` world (at least as a daily basis) but I'm sure, we can be considered as an `early adopter`. This project is **not**, yet, for this kind of usage (only me as a core dev), but will be in the future (I have plan for that).

Please follow https://github.com/the-benchmarker/web-frameworks/issues/3108 to keep in touch
