### ISSUE TITLE
Laravel / Lumen with Swoole

### ISSUE THREAD

**Issue by Kabingeran** [the-benchmarker/web-frameworks#3637]
Hi!

Please add Laravel / Lumen with Swoole to comparison
https://www.swoole.co.uk/article/laravel

**Comment by waghanza** [comment]
Hi @Kabingeran,

I had not enough bandwidth to achieve that myself, but feel free to add.

Regards,

**Comment by waghanza** [comment]
done in https://github.com/the-benchmarker/web-frameworks/pull/3850
