### ISSUE TITLE
[Rust] Add salvo

### ISSUE THREAD

**Issue by waghanza** [the-benchmarker/web-frameworks#3652]
Hi @chrislearn,

Would you mind to add (or consent that we add) [salvo](https://github.com/kenorld/salvo) in `here` ?

------------
This project compare performance based on 3 routes :

+ `GET` `/`, **SHOULD** return a successful status code and an empty string
+ `GET` `/user/:id`, **SHOULD** return a successful status code and the id
+ `POST` `/user`, **SHOULD** return a successful status code and an empty string

Regards,

**Comment by chrislearn** [comment]
https://github.com/the-benchmarker/web-frameworks/pull/3656
