### ISSUE TITLE
[Java] Add repipe

### ISSUE THREAD

**Issue by waghanza** [the-benchmarker/web-frameworks#3699]
Hi @FroMage,

Would you mind to add (or consent that we add) [redpipe](https://github.com/FroMage/redpipe) in `here` ?

This project compare performance based on 3 routes :

+ `GET` `/`, **SHOULD** return a successful status code and an empty string
+ `GET` `/user/:id`, **SHOULD** return a successful status code and the id
+ `POST` `/user`, **SHOULD** return a successful status code and an empty string

Regards,

**Comment by FroMage** [comment]
Hi, thanks, but I don't think that's a good idea: the project is unmaintained for years now.

**Comment by waghanza** [comment]
> Hi, thanks, but I don't think that's a good idea: the project is unmaintained for years now.

ok. thanks for this info ❤️
