### ISSUE TITLE
[Java] Add activej

### ISSUE THREAD

**Issue by waghanza** [the-benchmarker/web-frameworks#3700]
Hi @dvolvach @eduard-vasinskyi @valerialistratova,

Would you mind to add (or consent that we add) [activej](https://github.com/activej/activej) in `here` ?

This project compare performance based on 3 routes :

+ `GET` `/`, **SHOULD** return a successful status code and an empty string
+ `GET` `/user/:id`, **SHOULD** return a successful status code and the id
+ `POST` `/user`, **SHOULD** return a successful status code and an empty string

Regards,

**Comment by eduard-vasinskyi** [comment]
Hello, @waghanza

We would like to add ActiveJ to your benchmark. We have tried to run it locally first but faced some issues.

It says in `CONTRIBUTING.md` that we should reference ActiveJ in neph.yaml and benchmarker.cr, but there are no such files in the repository. There are also no references for other frameworks in `Makefile`.

We have created a simple App with routes that you specified. To test it, we recreated steps from logs of semaphore job:

```
bundle exec rake config
cd java/activej && make build  -f .Makefile  && cd -
FRAMEWORK=java/activej bundle exec rspec .spec
make  -f java/activej/.Makefile collect
bundle exec rake db:export
```

`rspec` has completed successfully even when the server response had an incorrect body.
We have managed to fix this by replacing `expect response.body == "0"` with `expect(response.body).to  eq("0")` etc.

When calling `collect` some requests did not match expected routes. The server received requests on `GET /` and `POST /user`, but no requests on `GET /user/:id` endpoint. Some requests were sent to endpoint `POST /` which was not specified, so it resulted in a 404 response.

What is the deal with HTTP pipelining? You have some Lua scripts that have 'pipeline' in their names but it seems like HTTP  pipelining is not used in fact (server received requests sequentially).

Maybe we did not run the benchmark correctly? Could you please provide an example of how to run a benchmark locally and compare results with other frameworks?

**Comment by waghanza** [comment]
Thanks for sharing this @eduard-vasinskyi. In deed the doc is very outdated.

I suggest that you create a branch with the code base (in the right place), I'll take care of the rest :heart:

**Comment by eduard-vasinskyi** [comment]
@waghanza 
We have forked the `web-frameworks` repo and added ActiveJ in a [separate branch](https://github.com/activej/web-frameworks/tree/java/add_activej). Can you transfer it to ` the-benchmarker/web-frameworks` or should I make a pull request into master?

**Comment by waghanza** [comment]
awesome @eduard-vasinskyi ❤️ , I see https://github.com/activej/web-frameworks/tree/java/add_activej

I'll make the `PR` (due to CI it must be an internal branch)
