### ISSUE TITLE
Check ubiquity failure (404)

### ISSUE THREAD

**Issue by waghanza** [the-benchmarker/web-frameworks#3702]

**Comment by hdqtian** [comment]
Hi~Please add ubiquity with Swoole and ubiquity with workerman to comparison,thx
https://micro-framework.readthedocs.io/en/latest/extra/async.html

**Comment by waghanza** [comment]
Not now @hdqtian. I pref to fix this before (but a pleasure to review your `PR` ❤️ )

However, `ubiquity` will be tested like that before any public communication
