### ISSUE TITLE
Failing hyperf

### ISSUE THREAD

**Issue by waghanza** [the-benchmarker/web-frameworks#3741]
Hi @limingxinleo @huangzhhui

Has `hyperf` starting command change ?

I have an issue on `php sbin/hyperf.php`
@see https://the-benchmarker.semaphoreci.com/jobs/afda975a-21ce-410f-acc5-5ff0a60db85f#L1653

Regards,

**Comment by limingxinleo** [comment]
Try again ?

`php sbin/hyperf.php` will generate scan cache, so it does not affect listening 3000
