### ISSUE TITLE
Headers in PHP-Workerman is double size the Java-ActiveJ

### ISSUE THREAD

**Issue by RicardoSette** [the-benchmarker/web-frameworks#3795]
Hi @walkor ,

Checking the response of the Workerman to the project I noticed that it is twice the size in headers of the ActiveJ framework, this is because in ActiveJ the "Server" header and the "Content-Type" header are not used. Look:

ACTIVEJ (size_header=62)
````
$ curl -v 127.0.0.1:84
* Rebuilt URL to: 127.0.0.1:84/
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 84 (#0)
> GET / HTTP/1.1
> Host: 127.0.0.1:84
> User-Agent: curl/7.54.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< Content-Length: 0
< Connection: keep-alive
< 
* Connection #0 to host 127.0.0.1 left intact

$ curl -s -w '%{size_header}' -o /dev/null 127.0.0.1:84
62
````

WORKERMAN (size_header=120)
````
$ curl -v 127.0.0.1:85
* Rebuilt URL to: 127.0.0.1:85/
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 85 (#0)
> GET / HTTP/1.1
> Host: 127.0.0.1:85
> User-Agent: curl/7.54.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< Server: workerman
< Connection: keep-alive
< Content-Type: text/html;charset=utf-8
< Content-Length: 0
< 
* Connection #0 to host 127.0.0.1 left intact

$ curl -s -w '%{size_header}' -o /dev/null 127.0.0.1:85
120
````

This may be influencing the results, so I made a change to the code so that the response reports the same ActiveJ headers, see:

````php
<?php
require_once __DIR__ . '/vendor/autoload.php';

use Workerman\Worker;

class Response extends \Workerman\Protocols\Http\Response
{
    public function __toString()
    {
        $body_len = \strlen($this->_body);
        $reason = $this->_reason ? $this->_reason : static::$_phrases[$this->_status];
        return "HTTP/{$this->_version} {$this->_status} $reason\r\nContent-Length: $body_len\r\nConnection: keep-alive\r\n\r\n{$this->_body}";
    }
}

$worker = new Worker('http://0.0.0.0:3000');
$worker->count = shell_exec('nproc') ? shell_exec('nproc') : 32;
$worker->onMessage = function ($connection, $request) {
    $path = $request->path();
    $newResponse = new Response();
    switch ($path) {
        case '/':
        case '/user':
            $connection->send($newResponse->withBody(''));
            return;
        default:
            if (0 === \strpos($path, '/user/') && isset($path[6])) {
                $connection->send($newResponse->withBody(\substr($path, 6)));
                return;
            }
            $connection->send($newResponse->withBody(''));
    }
};
Worker::runAll();
````

After this change the size_header is now the same size as ActiveJ.

I hope it helps to put Workerman fighting again in the first place :nerd_face: :muscle:

**Comment by RicardoSette** [comment]
Hi @passwalls ,

I believe it is valid for Framework Mark, where the change would be about the response of the SimpleApp::buildResponse() method, removing the headers that ActiveJ does not use.

Example:
````php
    /**
     * @param $body
     * @param int $status
     * @param string $reason
     * @return string
     */
    public static function buildResponse($body, $status = 200, $reason = 'ok')
    {
        $body_len = \strlen($body);
        return "HTTP/1.1 {$status} {$reason}\r\nContent-Length: {$body_len}\r\nConnection: keep-alive\r\n\r\n{$body}";
    }
````

**Comment by walkor** [comment]
Thank you @RicardoSette , but after some test that the performance has not improved. I think we need php8 with jit to go back to the first place.

**Comment by waghanza** [comment]
Sure @walkor, we have a `PR` for `php` **8** (https://github.com/the-benchmarker/web-frameworks/pull/3655), but unfortunately some frameworks are not ready or badly implemented.

However, @RicardoSette , I'm not sure the header must be tweaked here, except if this is a `best practices` when using `workerman`. I mean, I'm aware that this could be frustrating, showing the performance only, but :
+ the purpose is not to display only performance, but other indicators as resources used ... 
+ the idea is to take frameworks for what they are. I think the decision about which header to output is up-to the frameworks (not developers using it)

**Comment by RicardoSette** [comment]
> * the purpose is not to display only performance, but other indicators as resources used ...

but it was just what I did, I adapted according to the framework's resources to deliver only what is necessary, since the tests applied do not take into account headers, what I did is a feature of the framework, which is precisely being able to intervene in requests in the responses according to the demand.

> * the idea is to take frameworks for what they are. I think the decision about which header to output is up-to the frameworks (not developers using it)

on this point I totally disagree, the decision of which headers should be presented is a **responsibility of the developer**, for example, to OWASP the header "server" must be omitted to avoid any exposure of the technology used, as this header can be used for those who wish to carry out an attack on their platform, as it would give attackers a direction to be followed over vulnerabilities already documented/known.

Some frameworks already adopt security headers as CSP by default, but it is the developer who must decide which headers should be presented according to the business rule, and for the-benchmarker / web-frameworks the "business rule" is performance, so controlling headers to have the minimum necessary for to work is a control to be decided by the developer if the framework allows, in this case Workerman allows full control of the response and with that it must be used to reach the "business rule".

**Comment by waghanza** [comment]
> the decision of which headers should be presented is a responsibility of the developer
sure, in one hand the developer has to ensure security. in the other hand, the framework should provide a clear path to it. I'm not sure all developers set headers by hand (of course anyone could say that this a framework responsibility, but developers on, at least the framework is chosen by developers)

>  and for the-benchmarker / web-frameworks the "business rule" is performance
nop. performance is one of the indicator (as @mcollina says we need to display at least `latency` ...). the rule could be to be **production-ready**. I just want to avoid fine tuning in each framework (that could lead to a bad results interpretation)

**Comment by waghanza** [comment]
let me rephrase

+ it it is part of OWASP / security of the app
   + OK
   + if this is provided by framework
+ if it is for performance gain
   + No

what I meant is that this technique should be allowed by framework itself (not a developer tweak, but an option usage)

/cc @RicardoSette

**Comment by waghanza** [comment]
I'll close, fee free to re-open @RicardoSette if needed. I will try to align specs with best-practices / OWASP recommendations
