### ISSUE TITLE
Fix ranges for antidot

### ISSUE THREAD

**Issue by waghanza** [the-benchmarker/web-frameworks#3804]
Hi @kpicaza,

You need to use `X.Y.Z` format (with `~`) in order to guarantee that we staying at `X.Y` (if no lock file)

Like `~1.0.0` guarantee that any build contains 1.0.x

Do you confirm that their is no other standard way @sy-records @leocavalcante ?

_Originally posted by @waghanza in https://github.com/the-benchmarker/web-frameworks/pull/3791#discussion_r560155799_

**Comment by leocavalcante** [comment]
No one that I know of. There is just an alternative syntax that is using asterisk: `1.0.*` then you don't need to specify a patch and IMHO is more readable/clean than `~1.0.0` about what is going to up.
Usually, shipping the code with the dependencies lock is the standard.

**Comment by kpicaza** [comment]
@waghanza, apologies, it was a misunderstanding with another comment in the previous PR https://github.com/the-benchmarker/web-frameworks/pull/3791#pullrequestreview-570092565 I will open another PR fixing it, thanks for your great work;-D.
