### ISSUE TITLE
Usage questions and information?

### ISSUE THREAD

**Issue by KnowZero** [the-benchmarker/web-frameworks#3824]
1) Is there any reason why there is no instructions for usage?

2) Is there a point to requiring docker and other dependencies? If you are already requiring docker, why not just run everything from docker without the extra dependencies?

3) Is there any normalization to what is being tested? By that I mean how many threads the framework makes.(not wrk) Because it goes without saying that a framework that defaults to more threads would offer higher performance (at the price of more ram, ram consumption should also be included). But a test should probably check performance in multiple scenarios of running with 1, 4 or 8 threads of the server itself.

**Comment by waghanza** [comment]
> Is there any reason why there is no instructions for usage?

2 in facts :
+ my laziness
+ the instructions changes too often

I need to take time to rewrite `README`

> Is there a point to requiring docker and other dependencies? If you are already requiring docker, why not just run everything from docker without the extra dependencies?

`docker` was initially introduce to setup frameworks (not built-in tool), but indeed having a docker image to run toolbelt could be great. I plan to do it, but not at this stage.

> Is there any normalization to what is being tested? By that I mean how many threads the framework makes.(not wrk) Because it goes without saying that a framework that defaults to more threads would offer higher performance (at the price of more ram, ram consumption should also be included). But a test should probably check performance in multiple scenarios of running with 1, 4 or 8 threads of the server itself.

The scenario is very basic : 3 endpoints, but I think (and not only me) that is not very accurate. We have to about a discussion to collect ideas first.

**Comment by KnowZero** [comment]
I just think that putting everything in docker would solve both #1 and #2. As even if things change, that would be on the docker size or a config file options. But the instructions themselves would stay.

The scenario currently isn't even basic but simply manipulation of results. Lets look at the top 2 framworks.

Activej:
.with("workers", "" + Runtime.getRuntime().availableProcessors())

Workerman:
$worker->count = shell_exec('nproc') ? shell_exec('nproc') : 32;

Both of which set it to utilize the maximum amount of threads available on the processor. Where as some of the lower ones you can see are either configured to a more limited amount of workers, or have code that artificially limits the amount of requests per child to prevent memory leaks (which means once you reach that limit, the child is recycled which uses up time). Since the top ones are running native instead of using a middleman thread manager, I also figure they aren't doing proper child flushing either.

Either way, I would at the very least set docker cpu limit to 1 or 2 to get at least a more accurate result without changing all the servers.

--cpus=1 or --cpus=2

This won't account for the child flushing, but would be a simple and quick way to limit available cpus to prevent abuse of unequal amounts of workers.

**Comment by waghanza** [comment]
> I just think that putting everything in docker would solve both 1 and 2. As even if things change, that would be on the docker side or a config file options. But the instructions themselves would stay the same.

You mean, putting toolbelt in a docker ? Not planned now, I prefer having efforts on stabilizing results as for now

> As for 3, the scenario currently isn't even basic but simply manipulation of results. Lets look at the top 2 framworks.
> 
> Activej:
> .with("workers", "" + Runtime.getRuntime().availableProcessors())
> 
> Workerman:
> $worker->count = shell_exec('nproc') ? shell_exec('nproc') : 32;
> 
> Both of which set it to utilize the maximum amount of threads available on the processor. Where as some of the lower ones you can see are either configured to a more limited amount of workers, or have code that artificially limits the amount of requests per child to prevent memory leaks (which means once you reach that limit, the child is recycled which uses up time). Since the top ones are running native instead of using a middleman thread manager, I also figure they aren't doing proper child flushing either.
> 
> Either way, I would at the very least set docker cpu limit to 1 or 2 to get at least a more accurate result without changing all the servers.
> 
> --cpus=1 or --cpus=2
> 
> This won't account for the child flushing, but would be a simple and quick way to limit available cpus to prevent abuse of unequal amounts of workers.

The implementations are (should be) made by active members. One of the rule, is to be as-production ready as possible. If any frameworks is better to fulfill this setting a dynamic number of worker, and an other better by spreading on all cores, it's up to the framework.

At least, we need to test a framework for what is (and what it could be is real life), not what it could be be. It's better to avoid tuning but prefer safety, best-practices, security ... the concepts recommended when running on production.

I'm not sure limitating docker resources will add anything (resources are already limitated by hardware - and it is the same for each)

**Comment by KnowZero** [comment]
There is plenty of reason to limit docker resources, especially for cloud deployment where you pay per cpu. Knowing how well the frameworks scale from 1 cpu to more cpus is just as important.

On a side note, most frameworks have the ability to set the amount of workers. Simply they are just not being used in the setup in some, while being custom tailored for others. For example, both Activej and Workman examples use 4 workers. But the adjustment is custom code by the users that is not in the implementation guide at all. These custom implementations that max out the cpus might be okay in docker instances with set resources per instance, but might be a problem if you are just deploying them on a server and they share resources with other things like databases or other applications.

Not to mention not all frameworks include best practices in their guides to begin with, some leave it up to the user.

Which means end of the day, the benchmark has to decide best practices to insure everything is kosher, or it will suffer the same fate as other benchmarks where code is custom tailored to beat the benchmark by some active users, while other frameworks remain unmaintained and unoptimized.

If you want to have it that they do use it based on the framework and not your own set of rules, then at the very least require that every pull request provide a link to the best practice page on the framework and that this is what they are saying is okay for production.

**Comment by waghanza** [comment]
> There is plenty of reason to limit docker resources, especially for cloud deployment where you pay per cpu. 

I hadn't not done this myself, and then I can not find any against argument. However, this is not the scope of this project. The idea here is to compare frameworks characteristics at their maximum usability. Adding more limit that hardware ones, will not have any gain for this project

> Which means end of the day, the benchmark has to decide best practices

Yes. This is upto the framework to decide its best-practices, and if their is not the underlying language.

> code is custom tailored to beat the benchmark by some active users, while other frameworks remain unmaintained and unoptimized.

Yes. This is upto the author (or the remaining community) to maintain it. We could not ask to this project maintainers.

> If you want to have it that they do use it based on the framework and not your own set of rules, then at the very least require that every pull request provide a link to the best practice page on the framework and that this is what they are saying is okay for production.

We already provide a link to the framework website. If their is no best-practice, we take those of underlying language
