### ISSUE TITLE
Good point. For some reasons in my tests `quarkus.http.port=3000` wasn't being picked up from the conf file. Not sure why.

### ISSUE THREAD

**Issue by waghanza** [the-benchmarker/web-frameworks#3828]
Good point. For some reasons in my tests `quarkus.http.port=3000` wasn't being picked up from the conf file. Not sure why.

_Originally posted by @whiplash in https://github.com/the-benchmarker/web-frameworks/pull/3813#discussion_r562908175_

**Comment by whiplash** [comment]
Fixed in https://github.com/the-benchmarker/web-frameworks/pull/3813/commits/65d989534f453971bc9d47015feb64b70068200d
