### ISSUE TITLE
Replace requitements.txt by pipfile ?

### ISSUE THREAD

**Issue by waghanza** [the-benchmarker/web-frameworks#384]
Hi,

On `python`'s world, dependencies are managed with **requirements.txt**

It might be intersting to use [`Pipfile`](https://pipenv.readthedocs.io)

Regards,

**Comment by greed2411** [comment]
@waghanza if im not wrong, `Pipfile` is for `pipenv` right? `pipenv` is more of `npm`/`yarn` for python and replacing what `virtualenv` does. Since we use docker which is better than `virutalenv` , you still want to proceed?

**Comment by waghanza** [comment]
@greed2411 in fact, I never tried `Pipfile`. I wanted to open this issue to have some **feedbacks** about that, and implement it here (if accurate). 

Behind, we use https://www.dependencies.io to get in-sync with versions, and its recommended to switch to `Pipfile` (also because `Pipfile` have more **features**)

**Comment by doanguyen** [comment]
I'm with @greed2411, pip itself is just right for me, Pipfile is just over killed.

**Comment by waghanza** [comment]
But it has some extended features no ?

**Comment by doanguyen** [comment]
Yes, it is. But consider the fact that the Pipfile project has not yet reached version 1.0, nothing sure at this moment even at the front page of the project state. For me, the selling point of Pipfile over requirements.txt is that it creates fully specified environments which means every dependency is fixed. so yes it's great. But for a benchmark project, I don't see any pros of using Pipfile here.

**Comment by waghanza** [comment]
Ok. Convinced.

Let's close, and re-opend after the `1.0`

**Comment by waghanza** [comment]
@dependabot Which python package manager is supported ?
+ requirements.txt
+ setup.cfg
+ MANIFEST.in
+ Pipfile
+ Poetry
