### ISSUE TITLE
PHP-FPM tuning

### ISSUE THREAD

**Issue by RicardoSette** [the-benchmarker/web-frameworks#3889]
Hi @waghanza ,

The default php-fmp settings in 7.4-fpm-alpine define the process manager as "dynamic" (pm = dynamic) and a maximum of 5 processes (pm.max_children = 5).

As wrk runs with 8 Threads and starts with a concurrency of 64 per thread, we could have 512 processes available in PHP-FPM to best performance.

See if applying the changes below in PHP-FPM, in the Dockerfile file, results in improvement in frameworks that run with PHP-FPM:

FROM
https://github.com/the-benchmarker/web-frameworks/blob/691861a58857a4ea3e075a812567f7bacee57d2c/php/Dockerfile#L52-L55

TO
```dockerfile

  RUN sed -i 's/\(listen =\).*/\1 \/var\/run\/php-fpm.sock/g' /usr/local/etc/php-fpm.d/www.conf
  RUN sed -i 's/\;\(listen\.owner.*\).*/\1/g' /usr/local/etc/php-fpm.d/www.conf
  RUN sed -i 's/\;\(listen\.group.*\).*/\1/g' /usr/local/etc/php-fpm.d/www.conf
  RUN sed -i 's/\;\(listen\.mode.*\).*/\1/g' /usr/local/etc/php-fpm.d/www.conf
  RUN sed -i 's/\(pm =\).*/\1 static/g' /usr/local/etc/php-fpm.d/www.conf
  RUN sed -i 's/\(pm\.max_children =\).*/\1 512/g' /usr/local/etc/php-fpm.d/www.conf
```

**Comment by waghanza** [comment]
Hi @RicardoSette,

Feel free to configure `php-fpm` for the maximum performance, knowing 3 facts :
+ having a **production-grade** setup is more important (safety is more important than raw performance)
+ we only have to override settings required by the framework. I mean, when on cloud,  rather use `php-fpm` default config (`dist` one)
+ dynamic setting is better (using `nproc` to override settings, for example)

/cc @leocavalcante @sy-records

**Comment by RicardoSette** [comment]
Hi @waghanza ,

This could be the responsibility of each framework publication, where in the {{#before_build}} configuration you would define the type of process and the number of children of php-fpm to be used.

In this article https://haydenjames.io/php-fpm-tuning-using-pm-static-max-performance/ the recommendation is PHP-FPM in static mode.

Another approach is to default to Dockerfile having
pm.max_children with 64 and some {{#pm_config}} configuration for each one to be able to change on demand, since the number of children to be defined depends on the memory consumption the PHP process of that framework consumes, I have already seen frameworks consuming 3mb and another 25mb in simple examples of "hello world".

Today the default is with 5 processes, and in production this is completely unviable/unreal to support high requests.

**Comment by waghanza** [comment]
> This could be the responsibility of each framework publication, where in the {{#before_build}} configuration you would define the type of process and the number of children of php-fpm to be used.

I think this complicates framework addition

> 
> In this article https://haydenjames.io/php-fpm-tuning-using-pm-static-max-performance/ the recommendation is PHP-FPM in static mode.

Thanks I'll read

> Today the default is with 5 processes, and in production this is completely unviable/unreal to support high requests.

Is there a convention / rule / consensus in php community to define those number, or at least an indication like in https://docs.gunicorn.org/en/latest/settings.html?highlight=workers#workers

**Comment by RicardoSette** [comment]
> Is there a convention / rule / consensus in php community to define those number, or at least an indication like in

for pm.max_children the main rule for the calculation is about RAM, see below:

https://www.php.net/manual/en/install.fpm.configuration.php
> pm.max_children
> This option sets the limit on the number of simultaneous requests that will be served. Equivalent to the ApacheMaxClients directive

https://2bits.com/articles/tuning-the-apache-maxclients-parameter.html
> A simple calculation for MaxClients on a system that does only Drupal would be:
> 
> (Total Memory - Operating System Memory - MySQL memory) / Size Per Apache process.

https://www.kinamo.be/en/support/faq/determining-the-correct-number-of-child-processes-for-php-fpm-on-nginx
> The exact settings are based on the memory available to your cloud server

https://support.cpanel.net/hc/en-us/articles/360036533754-PHP-FPM-Performance-Tuning-Basics
> Max Children = (Total Ram - (Used Ram + Buffer)) / (Memory per PHP process)

On a server with 16GB of RAM where each PHP process would spend 15MB, the number of children would be + -1,000

Being conservative, at least 512 children would present a greater reality to the tests

**Comment by RicardoSette** [comment]
@waghanza  you can test the PHP-FPM tuning in a single project, for example Siler, and check the difference in the score.

What do you think @leocavalcante ? what would be your children's suggestion for PHP-FPM to run Siler on a server with 16GB of RAM with a maximum CPU request?

I continue to recommend the settings below with 512 children, as they are low considering Siler, which consumes only 2.5MB per process, see again:

````Dockerfile
  RUN sed -i 's/\(listen =\).*/\1 \/var\/run\/php-fpm.sock/g' /usr/local/etc/php-fpm.d/www.conf
  RUN sed -i 's/\;\(listen\.owner.*\).*/\1/g' /usr/local/etc/php-fpm.d/www.conf
  RUN sed -i 's/\;\(listen\.group.*\).*/\1/g' /usr/local/etc/php-fpm.d/www.conf
  RUN sed -i 's/\;\(listen\.mode.*\).*/\1/g' /usr/local/etc/php-fpm.d/www.conf
  RUN sed -i 's/\(pm =\).*/\1 static/g' /usr/local/etc/php-fpm.d/www.conf
  RUN sed -i 's/\(pm\.max_children =\).*/\1 512/g' /usr/local/etc/php-fpm.d/www.conf
````

**Comment by leocavalcante** [comment]
Yeah, the problem is that is is not an exact science, it turns down to the subjectivity of what your processes will be doing. **But**, yeah, there are the generally speaking conventions, I'm particulary used too:
- 2x cores  for min spare servers and start servers
- 4x cores for max spare servers
- Total **available** RAM / process memory for max children (as well)

Tuning a real word scenario you will get some tips like:
- `WARNING: [pool www] seems busy (you may need to increase pm.start_servers, or pm.min/max_spare_servers), spawning X children, there are Y idle, and Z total children`
- `WARNING: [pool www] server reached pm.max_children setting (N), consider raising it`

Also, don't forgetting that in the case of PHP-FPM the Nginx tuning is also important.

**Comment by waghanza** [comment]
could you make a `PR` for this @leocavalcante ? 

having something like `  RUN sed -i "s/\(pm\.max_children =\).*/\1 `nproc`/g" /usr/local/etc/php-fpm.d/www.conf
` in `php/Dockerfile` would help
 
⚠️ Not the double quotes for bash evaluation (not very clean but will can clean it)

ℹ️  Having only one **Dockerfile** will let all `php-fpm` based frameworks use this 😛

**Comment by RicardoSette** [comment]
In https://github.com/TechEmpower/FrameworkBenchmarks/blob/caf55d6583e5c61cc33e42c7d3968213b3276b68/frameworks/PHP/php/php.dockerfile#L15 the configuration as nproc decides between 1024 or 512 children, it could be a way to decide

Example:
````Dockerfile
RUN if [ $(nproc) = 2 ]; then sed -i "s|pm.max_children = 1024|pm.max_children = 512|g" /usr/local/etc/php-fpm.d/www.conf ; fi;

````

I believe that less than 512 children(max_children) would not be the reality of production for an environment with a lot of overload and requests/sec

**Comment by waghanza** [comment]
Feel free to create any `PR` for that @RicardoSette ❤️ 

Glad to review / merge ....
