### ISSUE TITLE
[PHP] Sunrise is failing with roadrunner

### ISSUE THREAD

**Issue by waghanza** [the-benchmarker/web-frameworks#3922]
Hi @fenric,

I've updated CI (I notice it was useless) and then it appear that `sunrise` is failing with `roadrunner`

https://github.com/the-benchmarker/web-frameworks/runs/1845194145?check_suite_focus=true#step:7:10

Regards,

**Comment by fenric** [comment]
Hi! I think I understand why it happened. The problem isn't with the router, but with the test... I'm cooking a fix.

**Comment by fenric** [comment]
@waghanza #3928
