### ISSUE TITLE
[PHP] One is failing with php-fpm

### ISSUE THREAD

**Issue by waghanza** [the-benchmarker/web-frameworks#3923]
Hi @Yurunsoft,

I've updated CI (I notice it was useless) and then it appear that `one` is failing when using `php-fpm`
https://github.com/the-benchmarker/web-frameworks/runs/1845194027?check_suite_focus=true#step:7:10

Regards,

**Comment by sy-records** [comment]
@Yurunsoft is not the author of `one`
@lizhichao is the author of `one`

**Comment by lizhichao** [comment]
This one is strange.  It may be that `composer` failed to execute

**Comment by waghanza** [comment]
> @Yurunsoft is not the author of `one`
> @lizhichao is the author of `one`

sorry

**Comment by RicardoSette** [comment]
> This one is strange. It may be that `composer` failed to execute

This would be possible @waghanza, because in local tests here I was successful, see:

POST in request OK
> $ curl -X POST -i 127.0.0.1:87/user
> HTTP/1.1 200 OK
> Server: nginx
> Date: Sun, 07 Feb 2021 12:59:05 GMT
> Content-Type: text/html; charset=UTF-8
> Transfer-Encoding: chunked
> Connection: keep-alive
> X-Powered-By: PHP/7.4.4

GEY /user/0 OK

> $ curl -X GET -i 127.0.0.1:87/user/0
> HTTP/1.1 200 OK
> Server: nginx
> Date: Sun, 07 Feb 2021 12:58:56 GMT
> Content-Type: text/html; charset=UTF-8
> Transfer-Encoding: chunked
> Connection: keep-alive
> X-Powered-By: PHP/7.4.4
> 
> 0

GET /user OK
> $ curl -X GET -i 127.0.0.1:87
> HTTP/1.1 200 OK
> Server: nginx
> Date: Sun, 07 Feb 2021 12:58:39 GMT
> Content-Type: text/html; charset=UTF-8
> Transfer-Encoding: chunked
> Connection: keep-alive
> X-Powered-By: PHP/7.4.4
> 
> 

A feature that we don't have Content-Length in the header, but that shouldn't create the problem.

**Comment by waghanza** [comment]
weird, my local tests are OK

will investigate ... this is probably due to CI

**Comment by waghanza** [comment]
seem to be a bug on CI, should be fixed by https://github.com/the-benchmarker/web-frameworks/pull/3927
