### ISSUE TITLE
Remove hanami

### ISSUE THREAD

**Issue by waghanza** [the-benchmarker/web-frameworks#3953]
Hi @jodosha,

I need to remove `hanami` from here -> since not compatible ruby 3 (and the it blocks https://github.com/the-benchmarker/web-frameworks/pull/3681).

I hope `hanami` 2 will be out soon, and I will re-add it here.

Regards,

PS : I won't do any public communication, so I think this will not affect negatively `hanami`

**Comment by jodosha** [comment]
@waghanza I understand. Fine by me.

Is there any chance that we can add Hanami::API? It's compatible with Ruby 3. Thanks.

**Comment by waghanza** [comment]
Already in `here` @jodosha 

@see https://github.com/the-benchmarker/web-frameworks#results
