### ISSUE TITLE
Update http4s

### ISSUE THREAD

**Issue by waghanza** [the-benchmarker/web-frameworks#404]
Hi @mfirry,

We are using `0.0.1-SNAPSHOT` for [http4s](http://http4s.org).

Do you mind opening a `PR` to use `0.18` ?

Regards,

**Comment by mfirry** [comment]
Hi @waghanza,
actually you're using `0.18.17` as you can see from the very first line of the `build.sbt` file.
I know it might look weird but `sbt` lets you define variables and use them later in the build file (for example `"org.http4s" %% "http4s-dsl" % Http4sVersion`.

So you're good to go, I think.

**Comment by waghanza** [comment]
Ah ok, I was on the wrong version number 🤣

**Comment by waghanza** [comment]
But there is still #401 if you want

**Comment by waghanza** [comment]
And the version referenced
https://github.com/the-benchmarker/web-frameworks/blob/master/FRAMEWORKS.yml#L159
is wrong
