### ISSUE TITLE
update python 

### ISSUE THREAD

**Issue by MajidHeydari** [the-benchmarker/web-frameworks#4042]
django-ninja and falcon are update

**Comment by waghanza** [comment]
what do you mean @MajidHeydari 

`falcon` is still in **2.0**
https://github.com/the-benchmarker/web-frameworks/blob/8d5199bdabe64a93bb8a1fc4045ec9c93ce11a20/python/falcon/requirements.txt#L1

and `django-ninja` in **0.11**
https://github.com/the-benchmarker/web-frameworks/blob/8d5199bdabe64a93bb8a1fc4045ec9c93ce11a20/python/django-ninja/requirements.txt#L1

**Comment by MajidHeydari** [comment]
pip install falcon==3.0.0b1
django-ninja ==0.11.0

**Comment by waghanza** [comment]
the PR is in review for `django-ninja`, should be merged now

for `falcon` we do not use `beta`, a `PR` will be opened by renovatebot when released
