### ISSUE TITLE
Update kitura

### ISSUE THREAD

**Issue by waghanza** [the-benchmarker/web-frameworks#405]
Hi @kiliankoe,

Our [kitura](http://kitura.io) implementation is still using `2.2`.

Would you mind helping us using `2.5` ?

Regards,

**Comment by kiliankoe** [comment]
Hi, I'm very sorry for not getting back to you on these two issues earlier. I am currently employed by Apple however and am not able to work on open source at this point in time. Thanks so much for updating both projects 😊

**Comment by waghanza** [comment]
Hi @kiliankoe,

Congratulation for your new position. 

It is a pleasure for me to update those **frameworks** (as it make me learn `swift` :stuck_out_tongue: ).

Regards,
