### ISSUE TITLE
Implementation of web frameworks

### ISSUE THREAD

**Issue by proyb6** [the-benchmarker/web-frameworks#411]
In my reading on Crystal web frameworks in your benchmark repo, are those running single or multiple process? From the script, Spider-Gazella seems to launch more than one process and how do I see if other Crystal framework if they are really ran more than one process?

I assume both Laravel and Vapor are multi-process and multi-threaded that lead to higher throughputs.

Perhaps it's useful to indicate in the result charts if it's utilizing 1-core..n-cores, multithreaded or etc.

I’m curious in raw header across the frameworks which would likely affected the results as well.

**Comment by waghanza** [comment]
@proyb6 at my end, I know `spider-gazelle` that is using `clustering`. all **frameworks** implementation are by the `author`. when we reach **production level**, we have to ducument all details of that

**Comment by waghanza** [comment]
@proyb6 `onyx` (new comer) also use clustering (forking approach)
