### ISSUE TITLE
Creating a PR template

### ISSUE THREAD

**Issue by waghanza** [the-benchmarker/web-frameworks#415]
Hi,

While we are `growing` as a **community**, `contributions` (`PR`) are :heart: but it could be **heavy** (in term of maintenance) to validate each parts (and more because we are multi-languages).

It could be useful to create a **pull request** template that help us maintaining / validating contributions.

I mean, in the first time, listing some configuration required to keep the code base consistent (using code standard, using CI ...)

What do you think @tbrand @OvermindDL1 @aichholzer ?

Regards,

**Comment by tbrand** [comment]
That sounds good. :+1:
I would like to see the template.

**Comment by waghanza** [comment]
A simple template listing task to do -> in order to keep code base consistent

I'll propose this soon :stuck_out_tongue_winking_eye:
