### ISSUE TITLE
Activej benchmark uses async, but not Jersey/Spring...

### ISSUE THREAD

**Issue by sixro** [the-benchmarker/web-frameworks#4203]
Hi @waghanza , very interesting project.
Looking inside the code, it seems to me that while for Activej you explicitely configure an async approach, it doesn't happen for Jersey/Spring. Probably you won't reach anyway the performance of Activej, but the sync approach is for sure the worst to compare with.
Regards

**Comment by waghanza** [comment]
Hi @sixro,

Thanks for your feedback, and great to here you find this project interesting.

As of me, I'm more a ruby developer, than a `java` one :-) I could for my own sake check all implementations here.

The main idea is to reflect what is maimly used in **production**.

If you have some proposal / critics about any implementation, feel free to say so, we will do our best ❤️  to solve any issue

Regards,
