### ISSUE TITLE
PHP images don't use OPCache

### ISSUE THREAD

**Issue by 1ma** [the-benchmarker/web-frameworks#422]
OPCache is an extension that saves PHP from recompiling the same files into bytecode for each request. It is commonly enabled in production environments and it usually has a significant impact on overall performance.

Reference: https://medium.com/appstract/make-your-laravel-app-fly-with-php-opcache-9948db2a5f93

**Comment by waghanza** [comment]
Hi @1ma,

Thanks for reminder. We will surely use opcode cache when we will be on production.

**Comment by waghanza** [comment]
We can use **opcode** cache on `docker`, but will it add more performance ?

Feel free to open a `PR`, if you want to see

**Comment by 1ma** [comment]
I bet it would. Anyway, I'll check it out and submit a PR.
