### ISSUE TITLE
[Java] Update spring

### ISSUE THREAD

**Issue by waghanza** [the-benchmarker/web-frameworks#4335]
Hi,

`spring` use **2.4**. Version **2.5** is out 
https://github.com/spring-projects/spring-boot/releases/tag/v2.5.0

We need to see why `renovate` does not spot this update
https://github.com/the-benchmarker/web-frameworks/blob/97b9cd02e2ad8179f0043fb8e44e5a684372c805/java/spring/pom.xml#L9

**Comment by whiplash** [comment]
For more details:
- [spring-boot-starter-parent](https://search.maven.org/artifact/org.springframework.boot/spring-boot-starter-parent) latest is 2.5.0
- [spring-boot-starter-webflux](https://search.maven.org/artifact/org.springframework.boot/spring-boot-starter-webflux/2.5.0/jar) latest is 2.5.0
- [spring-boot-maven-plugin](https://github.com/the-benchmarker/web-frameworks/issues/4335) latest is 2.5.0

**Comment by whiplash** [comment]
Plus I think `[1.0,2.0)` means ` 1.0 <= x < 2.0`

**Comment by whiplash** [comment]
Try `<version>[2.4,2.6)</version>`

**Comment by waghanza** [comment]
<version>[2.5,2.6)</version> will work to. The idea is to check why `renovate` fails :-)
