### ISSUE TITLE
CodeIgniter4 is failing

### ISSUE THREAD

**Issue by waghanza** [the-benchmarker/web-frameworks#4402]
Hi,

`codeigniter4` is failing in https://the-benchmarker.semaphoreci.com/jobs/21790820-d57f-4457-834e-2f93bdddef91

any idea @michalsn ?

Regards,

**Comment by michalsn** [comment]
@waghanza Fixed in #4406

**Comment by waghanza** [comment]
Thanks for all your awesome work, I'll take a look this week, and work to update results
