### ISSUE TITLE
Missing java / activej in results

### ISSUE THREAD

**Issue by eduard-vasinskyi** [the-benchmarker/web-frameworks#4405]
It seems like after the recent run (2021-06-03), ActiveJ, as well as some other frameworks, are missing from [the test results page](https://web-frameworks-benchmark.netlify.app/result)

**Comment by waghanza** [comment]
Hi @eduard-vasinskyi,

I've seen ... that some frameworks are missing (not only `activej`). I'll fix this for the next update (this week).

Thanks for reminder ❤️
