### ISSUE TITLE
Mars is failing

### ISSUE THREAD

**Issue by waghanza** [the-benchmarker/web-frameworks#4410]
Any idea @roblillack ?

https://the-benchmarker.semaphoreci.com/jobs/5e1c33b8-3d1e-4f42-aae0-52e5daf65627#L344

Generated dockerfile is 
```dockerfile
FROM golang:1.16-alpine

ENV CGO_ENABLED=0
ENV GOOS=linux
ENV GOARCH=amd64

WORKDIR /go/src/app
COPY . ./


  RUN go mod download
  RUN go generate main.go

RUN go get

RUN go build -a -ldflags '-extldflags "-static"' -o /go/bin/app ./

FROM alpine
COPY --from=0 /go/bin/app /go/bin/app
COPY --from=0 /go/src/app/routes.conf /go/bin/routes.conf
CMD cd /go/bin && ./app
```

**Comment by roblillack** [comment]
There have been some changes to the way Go checks module files. Can you change the Dockerfile, so that it contains `RUN go get github.com/roblillack/mars/cmd/mars-gen` before the `go generate` call?
