### ISSUE TITLE
Mofuw is failing

### ISSUE THREAD

**Issue by waghanza** [the-benchmarker/web-frameworks#443]
Hi @2vg,

`mofuw` is failing
https://travis-ci.com/the-benchmarker/web-frameworks/jobs/152443921

A quick-fix consist of use `0.19` version of **nim** (on `Dockerfile`) instead of using the `latest`
#442

What do you recommend ?

Regards,

**Comment by 2vg** [comment]
try CI agarai.
Please let me know if there is still a problem.

**Comment by waghanza** [comment]
yep, I've restarted, it's ok now
https://travis-ci.com/the-benchmarker/web-frameworks/jobs/152443921

I think I'll have to **pin** version on `Dockerfile` to avoid this (and display more info)
https://github.com/the-benchmarker/web-frameworks/issues/440
