### ISSUE TITLE
Spring is not available on Benchmark-Results

### ISSUE THREAD

**Issue by msinha251** [the-benchmarker/web-frameworks#4437]
Hi Team,

I was trying to compare springboot and go-fiber but unable to find springboot on benchmark result.

Though I can see spring under java folder but still didn't find it on result page.

Am I missing something here ?

**Comment by waghanza** [comment]
Hi,

Thanks for your interest in this project. I (and some others)'ve also noticed that some frameworks are not updated.

I'll investigate as soon as I can.

Regards,
