### ISSUE TITLE
Add Spring(+Java)

### ISSUE THREAD

**Issue by mcauto** [the-benchmarker/web-frameworks#446]
+ Language : Java
+ Repo : https://github.com/spring-projects/spring-framework
+ Author : spring-projects
Spring Framework is the populest web framework in Korea.

**Comment by waghanza** [comment]
@greenlaw110 interested in contributing (comparing with `act`) ?

**Comment by david-m-s** [comment]
https://github.com/the-benchmarker/web-frameworks/pull/1418

**Comment by waghanza** [comment]
@david-m-s spring and spring-boot are the same ?

**Comment by david-m-s** [comment]
I just searched for someone that had put it in a concise way. From https://www.baeldung.com/spring-vs-spring-boot:

"Spring Boot is basically an extension of the Spring framework which eliminated the boilerplate configurations required for setting up a Spring application.

It takes an opinionated view of the Spring platform which paved the way for a faster and more efficient development eco-system."

I'd say for the sake of benchmarking they are the same.

**Comment by waghanza** [comment]
ok understood, `spring-boot` is then `spring` but with a more efficient eco-system

I think, then, it could be intersting to have both here :
+ To see the performance gap of the `-boot` part
+ To see the differences between each codebase

But, it will be good to add this response into a documentation

**Comment by waghanza** [comment]
@david-m-s do you want to add an implementation of `spring` (classical) `here` ? I think it could be good to display result for the same implementation for `spring-boot` and `spring`
