### ISSUE TITLE
Gotham

### ISSUE THREAD

**Issue by derpmarine168** [the-benchmarker/web-frameworks#447]
+ Language : Rust
+ Repo : <https://github.com/gotham-rs/gotham>
+ Website : <https://gotham.rs/>

**Comment by waghanza** [comment]
@fafhrd91 @botika interested in contributing on this ?

**Comment by fafhrd91** [comment]
I am not. I think Gotham is dead

**Comment by waghanza** [comment]
@fafhrd91 I don't think so, the last commit, in **master**, is 13 days old

**Comment by derpmarine168** [comment]
Possibly <https://gotham.rs/blog#a-call-for-maintainers>. However, it's not *dead*.

**Comment by derpmarine168** [comment]
what i mean is:
> In recent months, development activity in Gotham has decreased
> [...] 
> major reasons that we’ve been less active 
> [...]
>The second of these points is sufficiently demanding that we don’t have enough time to maintain Gotham as a serious contender in the Rust web framework arena.
> [...]
> We’ll continue accepting security fixes and releasing patch versions if necessary
> [...]
> Feature contributions are still welcome, but may be delayed 
> [...]
> it’s up to the next maintainer(s) 

aka, it's still being maintained, but not very actively, and there are few (or no) maintainers that are dedicating large aounts of time to it.

also, i'd be happy to help contribute to this benchmark.

**Comment by waghanza** [comment]
@derpmarine168 feel free to do so :heart: any **contribution** is valuable

**Comment by whitfin** [comment]
I can confirm that it's most definitely not dead; there's a 0.3 release in the works Coming Soon (TM). There's a new batch of maintainers; myself, @nyarly and @colinbankier - as well as input from various community members and the original authors. 

I'm personally happy with any benchmarks added; feel free to ping me on the PR and I'll run over it just to make sure that everything is optimal. It might be worth waiting off for the 0.3 release just to avoid having to change it though; there are a couple of API changes in 0.3.

**Comment by whitfin** [comment]
Hi all, I have filed a quick benchmark in https://github.com/the-benchmarker/web-frameworks/pull/533. Haven't been able to verify, so can someone please vet the changes and let me know?

**Comment by waghanza** [comment]
@whitfin `rust` version could be aligned, unless for `rocket` :stuck_out_tongue_winking_eye: 

`rocket` compiles only on **nightly** (for _now_)

**Comment by whitfin** [comment]
@waghanza yep, got that. I guess somebody updated to 1.30 just after I forked earlier today :p

**Comment by waghanza** [comment]
@whiplash me :stuck_out_tongue:
exactly it's not me, I use a service http://www.dependencies.io to keep up-to-date :tada:
