### ISSUE TITLE
[Java] Update micronaut to v3

### ISSUE THREAD

**Issue by waghanza** [the-benchmarker/web-frameworks#4579]

**Comment by waghanza** [comment]
@whiplash a try ?

**Comment by whiplash** [comment]
There is nothing to touch (or almost) as far as I can read [here](https://docs.micronaut.io/latest/guide/#upgrading).
We might _just_ need to change the version of the micronaut plugin in the `build.gradle`.
Something like 
```
-    id("io.micronaut.application") version "1.2.0"
+    id("io.micronaut.application") version "2.0.3"
```

**Comment by waghanza** [comment]
`id("io.micronaut.application") version "2.0.3"` leads to micronaut v3 ?

**Comment by whiplash** [comment]
Yes. If you read [here](https://docs.micronaut.io/latest/guide/#upgrading) (look for "Build Plugin Update") it just says that.
