### ISSUE TITLE
Is node.js koa  not use cluster mode ?

### ISSUE THREAD

**Issue by Jamlee** [the-benchmarker/web-frameworks#4738]
![image](https://user-images.githubusercontent.com/5196641/137292253-ce45f67b-fc77-4baf-8b96-ba6927eb8e3f.png)

node.js is slow than php ? i think that is not possible.

i run the koa from this repo,  koa is single process.

![image](https://user-images.githubusercontent.com/5196641/137292532-2597e958-1c68-41ce-8cbb-b05baed4f0c5.png)

it is not fair for node.js. because koa is not runing under cluster mode.

**Comment by Jamlee** [comment]
https://github.com/the-benchmarker/web-frameworks/issues/2201   is slove my problem. node image start app by pm.

**Comment by waghanza** [comment]
feel free to ask any question (I can have mis-configured something somehow)
