### ISSUE TITLE
Crystal not leveraging the 8 cores

### ISSUE THREAD

**Issue by drujensen** [the-benchmarker/web-frameworks#483]
Crystal doesn't have threads so its not leveraging the 8 cores. 

For Amber you can enable `port_reuse` in the settings:
```
  # Port Reuse: Amber supports clustering mode which allows to spin
  # multiple app instances per core. This setting allows to bind the different
  # instances to the same port. Default this setting to true if the number or process
  # is greater than 1.
  #
  # > Read more about Linux PORT REUSE https://lwn.net/Articles/542629/
  #
  settings.port_reuse = true
  #
  #
  # Process Count: This will enable Amber to be used in cluster mode,
  # spinning an instance for each number of process specified here.
  # Rule of thumb, always leave at least 1 core available for system processes/resources.
  #
  settings.process_count = 7
```

**Comment by drujensen** [comment]
@waghanza Did the benchmarks get worse for Amber after changing the number of processes?  Is there some logs that I can find out what's going on?

**Comment by waghanza** [comment]
@drujensen here I have results on my 4 cores

|  | Average | 50th percentile | 90th percentile | 99th percentile | 99.9th percentile | Standard deviation |
|------------|----------------:|----------------:|----------------:|----------------:|----------------:|----------------:|
| **master** | 23.63 ms | 23.84 ms | 29.86 ms | 31.38 ms | 235.06 ms | 5656.33 |
| 8de479f4815a044157ddf3ac15cd2b17da70f060 (optimization) | 23.37 ms | 24.04 ms | 29.04 ms | 29.68 ms | 232.26 ms | 5438.67 |
| cbe94adc84b5f28e4bbf3e4ce979660a76a4bb7e (before optimization) | 23.28 ms | 22.83 ms | 29.52 ms | 30.42 ms | 175.41 ms | 5593.33 |

according to those metrics the global performance decrease then, but we can not take any assumption on them;  results are computed on local docke. i'm working on runing each **framework** on `droplet` in my branch https://github.com/waghanza/http-benchmark/tree/cloudify, after I've finished we could take any conclusion

I'm quite sure run on `droplets` will change this **benchmark** completely. for example, `laravel` is consider faster than `amber` which, I think, is impossible

I'm sure `amber` will climb :heart:
