### ISSUE TITLE
Re-enable phoenix

### ISSUE THREAD

**Issue by waghanza** [the-benchmarker/web-frameworks#495]

**Comment by OvermindDL1** [comment]
Phoenix builds on plug, and thus if it had build issues probably elixir or plug was upgraded without upgrading the other as well.

**Comment by waghanza** [comment]
@c0b do you plan to release `elixir` `1.7.4` on **docker store** ?

**Comment by waghanza** [comment]
@OvermindDL1 `elixir` `1.7.4` is not so old :stuck_out_tongue: 
https://github.com/elixir-lang/elixir/tree/v1.7.4

it's about 5 hours now

**Comment by OvermindDL1** [comment]
Lol, my system just stays up to date so I never noticed when it appeared...  ^.^;

**Comment by Sgiath** [comment]
This was closed by #2234
