### ISSUE TITLE
Please add oxidy framework

### ISSUE THREAD

**Issue by krishnaTORQUE** [the-benchmarker/web-frameworks#5086]
New Rust Framework **oxidy**, please add it. In my test it beat actix in terms of Req/Sec & Response Time.
If I have to make PR about it, then please let me know.
Disclaimer: I am the author

**Comment by waghanza** [comment]
Hi @krishnaTORQUE,

Glad to see any PR ❤️ 

I can not make all implementation myself, but always available to review.

------------
The implementation should follow 

-------


+ `GET` `/`, **SHOULD** return a successful status code and an empty string
+ `GET` `/user/:id`, **SHOULD** return a successful status code and the id
+ `POST` `/user`, **SHOULD** return a successful status code and an empty string

Regards,

**Comment by krishnaTORQUE** [comment]
> Hi @krishnaTORQUE,
> 
> Glad to see any PR heart
> 
> I can not make all implementation myself, but always available to review.
> 
> The implementation should follow
> 
>     * `GET` `/`, **SHOULD** return a successful status code and an empty string
> 
>     * `GET` `/user/:id`, **SHOULD** return a successful status code and the id
> 
>     * `POST` `/user`, **SHOULD** return a successful status code and an empty string
> 
> 
> Regards,

Great I will do that. Thank you so much.
I will make PR & then I will comment here.

**Comment by krishnaTORQUE** [comment]
Hi
Can you please tell me how can I test the benchmark in my local system before push ?

**Comment by waghanza** [comment]
Usually, I do 
```
docker rm $(docker ps -a -q) -f ; cd ~/workspace/benchmark/web && bundle exec rake config && export DATABASE_URL=postgresql://postgres@localhost/benchmark && dropdb -U postgres benchmark  && createdb -U postgres benchmark && psql -U postgres -d benchmark < dump.sql&& export FRAMEWORK=rust/oxidy && bundle install && cd ${FRAMEWORK} && make -f .Makefile build && cd ../.. && sleep 2 && bundle exec rspec .spec
```
but this is intend to work on my system (`macos`) with a bunch of depencencies.

Feel free to push, there is CI, and I'll look at the code before merge

Do not forget to listen to port `3000`

**Comment by krishnaTORQUE** [comment]
Thank you so much
I have created the PR here : https://github.com/the-benchmarker/web-frameworks/pull/5088

**Comment by waghanza** [comment]
Seen @krishnaTORQUE, and reviewed

**Comment by krishnaTORQUE** [comment]
Hi @waghanza 
I have updated the PR

**Comment by krishnaTORQUE** [comment]
Thank you so much

**Comment by waghanza** [comment]
Ah forget to ask ... May I notify you on each update (minor) ? @krishnaTORQUE

**Comment by krishnaTORQUE** [comment]
Sure
