### ISSUE TITLE
[Go] Add aurora

### ISSUE THREAD

**Issue by waghanza** [the-benchmarker/web-frameworks#5168]
Hi @aurora-go,

Would you mind to add (or consent that we add) [aurora](https://github.com/aurora-go/aurora) in `here` ?

This project compare performance based on 3 routes :

+ `GET` `/`, **SHOULD** return a successful status code and an empty string
+ `GET` `/user/:id`, **SHOULD** return a successful status code and the id
+ `POST` `/user`, **SHOULD** return a successful status code and an empty string

Regards,

**Comment by aurora-go** [comment]
of course

**Comment by waghanza** [comment]
I follow https://github.com/smallnest/go-web-framework-benchmark project 😛 

I'll appreciate any PR about this ❤️

**Comment by aurora-go** [comment]
I have packed V0.2.4 according to your requirements. The details of the interface are in the APP folder, which is not clear
