### ISSUE TITLE
Update to Go 1.18

### ISSUE THREAD

**Issue by wildfiremedia** [the-benchmarker/web-frameworks#5229]
It's a good time to update for a benchmark.

Framework results page:
Beside updating, I have notice most of the URL link from each framework are invalid, no longer existed or incorrect URL address and remove when it's no long relevant.

Adding more framework:
Adonis.js (Javascript)
https://github.com/adonisjs/core

Perfect (Swift)
https://github.com/PerfectlySoft/Perfect

**Comment by wildfiremedia** [comment]
My suggestion that it shouldn't stop us from upgrade to Go 1.18 when gramework failed and Go beta was available for some time.

**Comment by waghanza** [comment]
Yeah, I plan to do a modification for this
