### ISSUE TITLE
[Ruby] Add hanami 2.x

### ISSUE THREAD

**Issue by waghanza** [the-benchmarker/web-frameworks#5234]
Hi @jodosha,

Do you mind add `hanami` 2.x in here ?

Even if hanami is in alpha state, I think we can add it.

Regards,

PS : I'll maintain it personnaly

**Comment by jodosha** [comment]
@waghanza Nice, and thanks for the ping.
Any recommendation as starting point?

**Comment by waghanza** [comment]
The idea is to implement a simple app having ony 3 endpoints (api mode)

+ `GET` `/`, **SHOULD** return a successful status code and an empty string
+ `GET` `/user/:id`, **SHOULD** return a successful status code and the id
+ `POST` `/user`, **SHOULD** return a successful status code and an empty string
