### ISSUE TITLE
Add HyperExpress

### ISSUE THREAD

**Issue by kartikk221** [the-benchmarker/web-frameworks#5319]
Hello,

I maintain the [HyperExpress](https://github.com/kartikk221/hyper-express) webserver and was wondering If it could be included in the benchmarks as I have been requested by a few peers of mine.

Do I need to make a PR request for this myself?

Thanks!

**Comment by waghanza** [comment]
HI @kartikk221,

Sure, a PR is welcome ❤️ 

This project compare performance based on 3 routes :

+ `GET` `/`, **SHOULD** return a successful status code and an empty string
+ `GET` `/user/:id`, **SHOULD** return a successful status code and the id
+ `POST` `/user`, **SHOULD** return a successful status code and an empty string

(For the moment, the idea is to show more indicators as this project grow, resources consumption for example)

Regards,

**Comment by kartikk221** [comment]
Great! I have just created #5321 PR to add support for HyperExpress.
