### ISSUE TITLE
Remove gramework

### ISSUE THREAD

**Issue by waghanza** [the-benchmarker/web-frameworks#5372]
Hi,

Since `gramework` is not  compatible with last go version (and then prevent some other framework updates), I'll have to remove it in a while

cc @toby3d @YamiOdymel @kirillDanshin @System-Glitch @appleboy 

------

Please vote and I'll act as the result 👍🏻  to keep and 👎🏻  to remove

-----

I think a reasonable amount of time is required (~10 days)

**Comment by System-Glitch** [comment]
Isn't it possible to force a specific go version for a specific framework in the `config.yaml`?

**Comment by System-Glitch** [comment]
The go version is easily visible in the results anyway so this shouldn't be misleading. It's better than not having results for one or more frameworks at all in my opinion.
