### ISSUE TITLE
The containers doesn't provide same conditions

### ISSUE THREAD

**Issue by kolbma** [the-benchmarker/web-frameworks#5426]
There are used different systems with different system libs, compilation settings, enabled features, memory allocators, used cpu instruction sets, ...
Also compilers in different versions and all this stuff has an impact on performance of the systems.
So one web framework is running in a faster, more optimized system than another and the bench results doesn't recognize this.
There should be used a sys bench or at least a standard webserver static files request/io result with equal configuration in the different docker containers to calculate a factor for alignment before comparing. Or maybe use the same image for all containers if this is possible with the dependencies.

**Comment by waghanza** [comment]
Hi @kolbma,

Could you point some differences we have ? Obviously, we do not use the same image for all frameworks, but the more important is what is used in **real life** (mimic community practices).

This subject is very abstract for me.

Could you open a PR is some deeeper context ?

Regards,

**Comment by RafaelKr** [comment]
I just found this Issue and also made some own comparisons and just wanted to add them here as a reference. There are definitely differences especially between used docker images.

![image](https://github.com/the-benchmarker/web-frameworks/assets/14234815/6b0f9ab3-bbb4-4185-a01e-04a59f2b1c9a)

Interestingly, for the actix variations I built, alpine was slower than debian.
For the `removed-headers` version I patched `actix-http-3.4.0` which doesn't return `content-type` and `date` headers.

Here are the full metrics:
[data.min.json](https://github.com/the-benchmarker/web-frameworks/files/13221217/data.min.json)

**Comment by waghanza** [comment]
The docker image will be changed (not because of this but in order to use slim variant as much as possible, and get rid of alpine ...).

However, I can understand that the figures are different, but the most important is to compare how much for example, can outperform any other rust framework, I mean the percentage more of rps.

I mean that numbers could vary depending on architecture... But rates should remain.

Btwn, thanks for your ideas
