### ISSUE TITLE
[Javascript] Bun

### ISSUE THREAD

**Issue by jamesli2021** [the-benchmarker/web-frameworks#5464]
Bun is a fast all-in-one JavaScript runtime

URL
https://bun.sh/

You could use http.js code from tutorial on the site.

**Comment by jkyberneees** [comment]
Hi @waghanza, supporting Bun as a JavaScript runtime would be great! 
Do we have any mechanisms to support new runtimes? I would like to list: https://github.com/BackendStack21/0http-bun as well as other frameworks from https://github.com/apvarun/awesome-bun

Any suggestions? 
Thanks in advance

**Comment by waghanza** [comment]
Hi @jkyberneees,

Unfortunately, no mechanism is provided (for now). I'm working on https://github.com/the-benchmarker/web-frameworks/pull/3958, but will be more a v2 (requires also a new / adapted UI).

Regards,
