### ISSUE TITLE
X-axis needs unit of measurement label on chart

### ISSUE THREAD

**Issue by hamitron** [the-benchmarker/web-frameworks#55]
https://raw.githubusercontent.com/tbrand/which_is_the_fastest/master/imgs/result.png

The X axis has numbers, but no unit of measurement.

Ruby on Rails is ~208 what?

**Comment by kiliankoe** [comment]
Those benchmark numbers are taken from one specific laptop anyways, so they're not really all that representative on other machines. Their relation to each other says more here than absolute values imho.
Nevertheless you're right about it being easier to tell the orders of magnitude one is faster or slower or another by knowing the units as well.

**Comment by tbrand** [comment]
@hamitron 
The unit is **sec**. I just drop the label at here. Will fix it. Thanks for the report.
https://github.com/tbrand/which_is_the_fastest/commit/9bec2a862951263707277bc5d93d2f1939bc61f5#diff-251cd489ffb425c194df01f80fe58dbd

@kiliankoe Agree but I just drop it at this time.
