### ISSUE TITLE
[Go] Add flamego

### ISSUE THREAD

**Issue by waghanza** [the-benchmarker/web-frameworks#5503]
Hi @unknwon,

Would you mind to add (or consent that we add) [flamego](https://github.com/flamego/flamego) in `here` ?

This project compare performance based on 3 routes :

+ `GET` `/`, **SHOULD** return a successful status code and an empty string
+ `GET` `/user/:id`, **SHOULD** return a successful status code and the id
+ `POST` `/user`, **SHOULD** return a successful status code and an empty string

Regards,

**Comment by unknwon** [comment]
Here you go: https://github.com/the-benchmarker/web-frameworks/pull/5505
