### ISSUE TITLE
Different results than official

### ISSUE THREAD

**Issue by davtoro** [the-benchmarker/web-frameworks#5520]
I've compared only two frameworks but your results are really different to my results. 
In your case difference is around 15% between fasthttp and actix
In my case it's 250% difference, 373k/s vs 1 mil/s

This is Go and fasthttp
```
"CMD : wrk -H 'Connection: keep-alive' --connections 256 --threads 48 --duration 15 --timeout 1 --script /root/web-frameworks/pipeline.lua http://172.17.0.2:3000/"
"================"
"OUT : Running 15s test @ http://172.17.0.2:3000/\n" +
"  48 threads and 256 connections\n" +
"  Thread Stats   Avg      Stdev     Max   +/- Stdev\n" +
"    Latency     1.11ms    1.47ms  30.11ms   86.21%\n" +
"    Req/Sec     7.81k     1.21k   33.70k    94.05%\n" +
"  5639885 requests in 15.10s, 500.21MB read\n" +
"Requests/sec: 373498.41\n" +
"Transfer/sec:     33.13MB\n"
```

This is Rust and actix:
```
"CMD : wrk -H 'Connection: keep-alive' --connections 256 --threads 48 --duration 15 --timeout 1 --script /root/web-frameworks/pipeline.lua http://172.17.0.2:3000/"
"================"
"OUT : Running 15s test @ http://172.17.0.2:3000/\n" +
"  48 threads and 256 connections\n" +
"  Thread Stats   Avg      Stdev     Max   +/- Stdev\n" +
"    Latency   345.07us  624.24us  24.03ms   94.54%\n" +
"    Req/Sec    20.91k     4.20k   50.34k    79.38%\n" +
"  15174068 requests in 15.10s, 1.06GB read\n" +
"Requests/sec: 1004966.40\n" +
"Transfer/sec:     71.88MB\n"
```

**Comment by waghanza** [comment]
Hi @davtoro,

Thanks for your interest on this project. 

I can understand the difference in figures we have each other, it depends on a bunch of factors
- hardware in use
- orchestration engine
- ...

But mainly, the global idea is that this project is not ready for **production**, I mean we are testing a local loopback network (and the quality of network is one of the most important key here).

It is planned to test with a real connection, I'll create an accurate roadmap

Regards,

PS : Feel free to re-open if any questions
