### ISSUE TITLE
Introduce jenet

### ISSUE THREAD

**Issue by waghanza** [the-benchmarker/web-frameworks#553]
+ Language : pony
+ Repo : https://github.com/Theodus/jennet
+ Author : @Theodus

**Comment by waghanza** [comment]
Hi @Theodus,

Would you mind to add (or consent that we add) [jennet](https://github.com/Theodus/jennet) in `here` ?

This project compare performance based on 3 routes :

+ `GET` `/`, **SHOULD** return a successful status code and an empty string
+ `GET` `/user/:id`, **SHOULD** return a successful status code and the id
+ `POST` `/user`, **SHOULD** return a successful status code and an empty string

Regards,

**Comment by Theodus** [comment]
Hello @waghanza. jennet has not been actively maintained for some time and is not in working condition. You are free to add it if you wish, but I would not recommend that you do so at this time.

**Comment by waghanza** [comment]
Ok. Thanks for your honesty, I prefer then close this issue.

Feel free to re-open if `jennet` turn maintained

:heart:
