### ISSUE TITLE
Remove or not remove responder

### ISSUE THREAD

**Issue by waghanza** [the-benchmarker/web-frameworks#5797]
Hi @ahopkins @taoufik07,

I create this issue to not forget to remove `responder` (PR will be create on 06 of November).

Except of course if I'm wrong :-)

This follows https://github.com/the-benchmarker/web-frameworks/issues/5769#issuecomment-1296207458

**Comment by ahopkins** [comment]
Yeah, that seems okay. If the project is revived it can be added back.
