### ISSUE TITLE
Requests that take too long or time out should be ignored.

### ISSUE THREAD

**Issue by JoelEllis** [the-benchmarker/web-frameworks#588]
Currently some frameworks have a standard deviation of more than 750000ms, this is probably inaccurate and requests exceding a minute should be ignored, as they would be by a browser.

**Comment by proyb6** [comment]
I don’t see anything more than a minute?

**Comment by derpmarine168** [comment]
Look at the standard deviation on symfony and laravell. It excedes 10 mins on symfony.

**Comment by OvermindDL1** [comment]
> Look at the standard deviation on symfony and laravell. It excedes 10 mins on symfony.

You should set a timeout on the test (15 seconds?) and report anything that takes longer as an error.

**Comment by waghanza** [comment]
@derpmarine168 Yep, the standard deviation is huge, but this is a side-effect of using `docker` -> after running on **digitalocean** this metric will decrease drastically

@OvermindDL1 yeah ! ! ! after running on `cloud`, I will take figures more seriously (now their are not useful, just showing the way information is displayed)
