### ISSUE TITLE
[JavaScript] Add Astro

### ISSUE THREAD

**Issue by RoadRoller01** [the-benchmarker/web-frameworks#6029]
Astro [website](https://astro.build/)

**Comment by RoadRoller01** [comment]
Hi @RoadRoller01,

Feel free to open a PR then ❤️

We (mostly me) could take care of any implementation in here.

If you want to make a PR, you should implement `Astro` (in `javascript` folder) with the following :

- GET /, SHOULD return a successful status code and an empty string
- GET /user/:id, SHOULD return a successful status code and the id
- POST /user, SHOULD return a successful status code and an empty string

Regards,

@waghanza you were late by two steps

**Comment by waghanza** [comment]
You answered your own issue @RoadRoller01 😛  anyway thanks for your interest in this project

As you say, feel free to open a PR, I'll review it 

Btw, to include it here you will ne explicit approval from any core contributor (cc @FredKSchott @matthewp @natemoo-re) or wait for 10 days if no answer (and no opposition to include `astro` here)

Regards,

**Comment by JetLi2K** [comment]
How about rebuiling benchmark results chart with Astro and add to showcase instead? It's exactly what Astro is designed for, start with 0KB of JavaScript.
https://astro.build/showcase/

**Comment by waghanza** [comment]
Not sure it is the same subject @RoadRoller01. The website charts are built on https://github.com/the-benchmarker/website but @SuspiciousLookingOwl is working on it, feel free to join forces ❤️ 

But maybe benchmarking api with astro is an other topic

**Comment by RoadRoller01** [comment]
aaa i think i will close this issue, i lost the interest to astro.
