### ISSUE TITLE
Foxify is faling on route 2

### ISSUE THREAD

**Issue by waghanza** [the-benchmarker/web-frameworks#604]
Hi @ardalanamini,

`foxify` return a **404** on https://github.com/the-benchmarker/web-frameworks/blob/master/node/foxify/app.js#L13
@see https://travis-ci.com/the-benchmarker/web-frameworks/jobs/157156855

Regards,

**Comment by ardalanamini** [comment]
@waghanza what is the request url for this test?

**Comment by waghanza** [comment]
@ardalanamini `/user/0` on test suite, using `0` as URL param

**Comment by waghanza** [comment]
@ardalanamini  unfortunately, this is not working
I am on :
+ node  `10.12.0`
+ npm `6.4.1`
+ foxify `0.10.8`

it return **404** on `/user/0` using `.get("/user/:id", (req, res) => res.send(req.params.id))`
