### ISSUE TITLE
Passing CI, but fail to get results

### ISSUE THREAD

**Issue by waghanza** [the-benchmarker/web-frameworks#617]
Hi,

Actually, test phase test each endpoint once.

Some frameworks passes this step

Actually, following frameworks pass tests, but results could not be computed

+ https://github.com/encode/starlette
+ https://github.com/kennethreitz/responder

I suggest having a more strict CI, testing each endpoint several time (5 for example), to avoid having this case in the future.

@OvermindDL1 How many runs is accurate to avoid false-positive CI like this ?

Regards,

**Comment by waghanza** [comment]
@tomchristie @kennethreitz I think this is related to `ulimit`, no ?

**Comment by OvermindDL1** [comment]
That all depends on the CI, if something like Travis then you will never ever have reliable and fully reproducible results as other services starting and stopping will add all kinds of noise into the test.  If just 'testing' if it works, well I don't think you can setup a lot of connections on travis (nor would you want to) so if using travis then you'd want to test with a lower connection count.

What is the URL to specific tests that are failing?
