### ISSUE TITLE
Add GC_MARKERS to all Crystal web frameworks

### ISSUE THREAD

**Issue by proyb6** [the-benchmarker/web-frameworks#618]
Let try adding this to all Crystal Dockerfile and I like to see if there is any improvement to throughput or latency.
 
```
ENV GC_MARKERS 1
```

https://github.com/ivmai/bdwgc/blob/master/doc/README.environment

This option is particular useful for heavy computation too that I could shave off a few seconds with no noticeable changes in memory usage.

**Comment by waghanza** [comment]
@proyb6 Yo can do this :stuck_out_tongue: but I think we could avoid this.

Why ?

Because, `docker` is just here for a **developper preview** (of results) -> it will be soon on cloud :+1:

**Comment by proyb6** [comment]
Ah, I remember, will close this then. Thanks!
