### ISSUE TITLE
Introduce restana

### ISSUE THREAD

**Issue by waghanza** [the-benchmarker/web-frameworks#621]
+ Language : javascript
+ Repo : https://github.com/jkyberneees/ana
+ Author : @jkyberneees

**Comment by waghanza** [comment]
Thanks for follow-up. We are comparing frameworks based on a simple implementation

* GET '/' return status code 200 with empty body
* GET '/user/:id' return status code 200 with the id
* POST '/user' return status code 200 with empty body

If you wish to participate, it be :heart:

**Comment by waghanza** [comment]
@jkyberneees Due to results update, there is a merge conflit. Could you give me write access to your repo, so I can fix this by hand ?

**Comment by waghanza** [comment]
@jkyberneees I've updated results :tada: https://github.com/the-benchmarker/web-frameworks#full-table

Their are still not **production-ready**, I might be disappointed :stuck_out_tongue:

**Comment by jkyberneees** [comment]
Thanks @waghanza, really happy to see restana is performing really well on your tests and creates a good precedent for nodejs.
