### ISSUE TITLE
Add suave

### ISSUE THREAD

**Issue by waghanza** [the-benchmarker/web-frameworks#629]
+ Language : F#
+ Repo : https://github.com/SuaveIO/suave
+ Author : @ademar

**Comment by waghanza** [comment]
Hi @ademar

Would you mind to add (or consent that we add) [suave](https://github.com/SuaveIO/suave) in `here` ?

This project compare performance based on 3 routes :

+ `GET` `/`, **SHOULD** return a successful status code and an empt²y string
+ `GET` `/user/:id`, **SHOULD** return a successful status code and the id
+ `POST` `/user`, **SHOULD** return a successful status code and an empty string

Regards,

**Comment by ademar** [comment]
Sure, no problem at all; I'll give it a try as soon as I can.
