### ISSUE TITLE
Why use `debug = true` for Rust framework

### ISSUE THREAD

**Issue by chrislearn** [the-benchmarker/web-frameworks#6332]
I notice all Rust web framework's profile open `debug=true`. This may have performance issue.

```rust
[profile.release]
opt-level = 3
debug = true
debug-assertions = false
overflow-checks = false
lto = true
panic = "abort"
incremental = false
codegen-units = 1
rpath = false
strip = false
```

**Comment by waghanza** [comment]
good catch, it should not ... at least it is not something what is done on **production** 

the idea was to have the same compiler options to have a "fair" comparison. could you remove this one ?
