### ISSUE TITLE
Add Yii2

### ISSUE THREAD

**Issue by skills-up** [the-benchmarker/web-frameworks#634]
Language: PHP 7.x

**Comment by waghanza** [comment]
Thanks @skills-up, I am curious to see how https://github.com/yiisoft/yii2 could perform.

@qiangxue interested to add `yii2` in this benchmark ?

**Comment by skills-up** [comment]
I think it will help a lot of new comers who often get confused between
Laravel (often cited as the best) and Yii2 (often cited as the fastest).

Regards,
Gaurav

**Comment by waghanza** [comment]
or `symfony` <- also cited as the best ;-)

**Comment by skills-up** [comment]
Yup, but symphony is the base over which Laravel is built. While fastest
ones also include slim and phalcon.

Regards,
Gaurav

**Comment by waghanza** [comment]
:stuck_out_tongue: sure, do not have the time to add frameworks <- I'm working on new version of this tool producing **production-ready** results (on `cloud` instead of on `docker`)

I'll be glad to merge any contribution :heart:

**Comment by waghanza** [comment]
Hi @qiangxue @samdark,

Would you mind to add (or consent that we add) [yii2](https://github.com/yiisoft/yii2) in `here` ?

This project compare performance based on 3 routes :

+ `GET` `/`, **SHOULD** return a successful status code and an empt²y string
+ `GET` `/user/:id`, **SHOULD** return a successful status code and the id
+ `POST` `/user`, **SHOULD** return a successful status code and an empty string

Regards,

**Comment by samdark** [comment]
@waghanza sure, go ahead. I'd like to review the pull request since there are settings that change performance dramatically.

**Comment by waghanza** [comment]
@skills-up If you want to `PR`, I'll be happy to review

**Comment by skills-up** [comment]
@waghanza I don't find myself qualified enough for this, specialty when @samdark is participating already.

**Comment by waghanza** [comment]
@skills-up not matter if you are qualified or not, just try (if you want) we can collaborate on any `PR`

**Comment by samdark** [comment]
I am not making pull request but will review one if asked. So @skills-up feel free to do it.

**Comment by gekh** [comment]
> I am not making pull request but will review one if asked. So @skills-up feel free to do it.

Hi there.

 I've created a simple basic Yii2 template with controllers to meet requirements. 

@samdark  you're welcome to update it :)

Pull Request: https://github.com/the-benchmarker/web-frameworks/pull/2240

**Comment by RicardoSette** [comment]
@qiangxue , @samdark and @xialeistudio I created Yii2 + Swoole using the yii2-swoole-extension

https://github.com/RicardoSette/web-frameworks/tree/yii2-swoole/php/yii-swoole

See if there would be anything to change in the project.
