### ISSUE TITLE
Enable HTTP pipeling

### ISSUE THREAD

**Issue by waghanza** [the-benchmarker/web-frameworks#637]
Hi @tomchristie,

I've seen your message on **tfb** list, I didn't know that `HTTP pipelining` is not enabled by default on modern browsers.

I suggest therefore to remove this feature from the benchmark (and optionally have an option that could force to use it).

@OvermindDL1 What do you think ?

Regards,

**Comment by tomchristie** [comment]
> and optionally have an option that could force to use it

Not quite sure what you mean here - would that option be controlled by server implementations, or would it be two different sets of environments with results for each?

**Comment by tomchristie** [comment]
> and in a second time, having an option that enable it (using command line argument, env var or else)

I'd argue for turning it off, and not allowing it as an option, otherwise server implementations are still incentivised to turn it on and optimize for it. (Even though in the vast majority of real world cases clients connecting to the servers won't support it.)

To argue against myself for a moment: The one thing that I *do* think is in its favour is that having pipelining enabled in one test case does at least help filter out poorly implemented server implementations. (Servers ought to be able to deal with pipelined requests robustly, even though they are no longer generally used)

**Comment by OvermindDL1** [comment]
Disabling HTTP pipelining is fine, it is indeed not used by modern browsers, and adding in the TCP setup time for each connection would be consistent with the test (and fine since each are being run on the same machine with the same kernel anyway).

>  To argue against myself for a moment: The one thing that I do think is in its favour is that having pipelining enabled in one test case does at least help filter out poorly implemented server implementations. (Servers ought to be able to deal with pipelined requests robustly, even though they are no longer generally used)

This is true, but then again this is not really a conformance test.

**Comment by waghanza** [comment]
@OvermindDL1 if we target `browser` (compare performance to choose the **framework** we need to create an app that will talk directly to `browser`), I'm OK with disabling `http pipelining`

@tomchristie I think if we want to make a fair comparison in the use case the app is not directly in relation with customer we **SHOULD** leave this option. I mean if the comparison is made for a **back** app (not talking to a `browser`, but `axios` / `frisbee` or else) `http pipeling` **COULD** be an intersting option

**Comment by tomchristie** [comment]
Either have it on (because it demonstrates robustness, and is a sometimes interesting case) or have it off (because it doesn't represent the common case).

Having it be togglable wouldn't resolve the issue, but just adds extra configuration.

**Comment by OvermindDL1** [comment]
Browser is the most common use-case, although with API's that's not usually the browser and HTTP Pipelining can be valuable there...

Maybe it makes sense to do both as different sets of test?

**Comment by waghanza** [comment]
ok, I will disable the **keep-alive** header :stuck_out_tongue:

**Comment by tomchristie** [comment]
You want the keep-alive header, you just don't want pipelined requests.
(I think it's been configured in the wrk lua script if I remember correctly?)

**Comment by waghanza** [comment]
@tomchristie I thought the header was a semi-first step to http pipeling
https://github.com/the-benchmarker/web-frameworks/blob/master/tools/src/client.cr#L44

**Comment by tomchristie** [comment]
All browsers and many clients will use keep-alive connections.
They won't use pipelining tho.

Looks like it's the `-s #{PIPELINE_GET}` / `-s #{PIPELINE_POST}` sections you'd want to drop.

You'll likely see far lower plaintext throughput in the top cases, but it'll be a more realistic representation.

**Comment by waghanza** [comment]
`#{PIPELINE_GET}` and `#{PIPELINE_POST}` are just formatters (in mean collect metrics using the same unit -> `ms`)

I have set **keep-alive**, but I have not set further. How pipeling is set then ?

**Comment by tomchristie** [comment]
@waghanza *Sorry I assumed this was an issue on TFB. I see that's not the case now.*

> I mean that wrk is configured with http pipelining by default, as your comment we SHOULD remove this

I don't think that's correct. I believe it's turned off by default, so you're *already* doing the right thing here.

It looks like you need to use `table.concat` to turn it on. (Which you don't want to do)

**Comment by waghanza** [comment]
Ok, thanks for explaination
