### ISSUE TITLE
Django: Too much difference b/w results of 2023-05-28, 2023-05-08

### ISSUE THREAD

**Issue by zaidiqbal** [the-benchmarker/web-frameworks#6410]
Hi, first of all thanks for these insights, it really helps to see the performance of different web frameworks.

I have been checking the results of 2023-05-28 which is latest by now, django is shown to have 2021 requests/second while if I check the results of 2023-05-08 django is shown to have 8680 requests/second. 

Why so much difference?
Is this by some mistake?

I was focusing on 2023-05-28 all the time but got surprised while I was reading from this site, as it mentioned the results of 2023-05-08:
https://www.pangea.ai/resources/web/

**Comment by waghanza** [comment]
Hi @zaidiqbal,

I understand this could be frustrating, and after digging into code changes (https://github.com/the-benchmarker/web-frameworks/compare/388b40c...d81c4f1) I have spotted that `gevent` make the difference (and imho artificially increase results).

Not sure that `gevent` is recommended / usable with python 3.11. I'm not using `python` on a daily basis, perhaps then @ahopkins ha a better view / opinion about recommendations when using this language in production.

Saying that the link you provided is interesting , however the methodology could vary a lot, and results in this kind of exercise could change a lot.
