### ISSUE TITLE
django: asgi vs wsgi?

### ISSUE THREAD

**Issue by zaidiqbal** [the-benchmarker/web-frameworks#6411]
Hi, Can you guys also include the different of asgi vs wsgi, to see how better asgi performs in context of requests/seconds?

thanks

**Comment by waghanza** [comment]
Hello @zaidiqbal,

Very good idea. This is implemented, but results are not shown yet.

For example, `django` could run with `daphne`, `uwsgi`, `gunicorn` ....

There is 3 things missing for that :
1. Having a UI able to show this (actually result on `python` show only with one engine, `gunicorn` or `uvicorn` mos of the time
2. The results takes 15hours to run
   - It's too long, and it could be multiplied by (a lot) with multiple engines
   - It runs on my workstation -> no real network
3. Code base (in ruby) should be changed

-----------

I can take 2 and 3, but it requires to have someone either make UI evolution (@SuspiciousLookingOwl) or make an other UI
