### ISSUE TITLE
Add JS/TS frameworks to the benchmark

### ISSUE THREAD

**Issue by waghanza** [the-benchmarker/web-frameworks#6419]
Hi @jim-king-2000,

Thanks for you suggestion in https://github.com/the-benchmarker/website/issues/40

You can add add any framework running on `bun` or another `deno` ... here.

------

This project compare performance based on 3 routes (for now) :

+ GET /, SHOULD return a successful status code and an empty string
+ GET /user/:id, SHOULD return a successful status code and the id
+ POST /user, SHOULD return a successful status code and an empty string

------

Regards,

**Comment by jim-king-2000** [comment]
Hi @waghanza , do you mean that I could send the pull request to this repo to add js(bun/deno/node) framework test myself?

**Comment by waghanza** [comment]
Exactly, you can inspire you from `opine` a deno based framework in javascript folder

**Comment by jim-king-2000** [comment]
OK. I'll take a try.

**Comment by jim-king-2000** [comment]
#6422 is my first pull request for adding elysia(bun).

**Comment by jim-king-2000** [comment]
I see the latest benchmark result. However, it is weird that `elysia` is defeated by `koa`. According to <https://github.com/SaltyAom/bun-http-framework-benchmark>, `elysia` is much better than `koa`. Is there anything wrong here?

**Comment by waghanza** [comment]
I understand, but to have this answer, I mean based on fact, we rather compare :
- methodology
- tools
- infrastructure used
- ....

I mean here, I choose wrk not bombardier (cause of C underlying, techempower using it, some feedbacks ...), infra is a Xeon (like most of VMs on the market), network is a loopback (as for now, I mean not a real network ....)

**Comment by jim-king-2000** [comment]
I think the infra is OK. But I don't know which benchmark result I should trust.

**Comment by waghanza** [comment]
Not agree with you, this benchmark is done on a Xeon, the other with an i7, the RAM is DDR3 here, DDR5 their, os is different ... 

But anyway, the idea is to take a look at SPOF and everything, just to be sur ewe can trust. The first step is to have a real infra (I mean real kubernetes / vms / baremetal -> I'll take care of this one)

**Comment by jim-king-2000** [comment]
> this benchmark is done on a Xeon, the other with an i7, the RAM is DDR3 here, DDR5 their, os is different ...

I remind that `bun.sh` uses `io_uring` which is only available on Linux kernel version 5.1+. May I know the Linux kernel version of this test environment?

> The first step is to have a real infra (I mean real kubernetes / vms / baremetal -> I'll take care of this one)

So, you will migrate the test environment to a real infra? Use real network (Ethernet, 1Gbps)? And anything else relevant to the real infra?

**Comment by jim-king-2000** [comment]
By the way we are using `hyper-express` now. It is of top ten in all benchmarks (here, <https://github.com/SaltyAom/bun-http-framework-benchmark> and <https://github.com/denosaurs/bench>). I'm just wondering whether we should change it in the future.

**Comment by waghanza** [comment]
The full specs is in https://github.com/the-benchmarker/web-frameworks/blob/295070e219b797c76778736e7cf4b25b4d8758db/data.json#L90469

**Comment by jim-king-2000** [comment]
Got it. Hope the CPU could be upgraded to a little bit stronger one. And thanks for this great benchmark website.

**Comment by waghanza** [comment]
I have not enough money for ...

I'll try to make some partnership with some cloud providers to avoid using my private workstation

**Comment by jim-king-2000** [comment]
We have an old laptop(i5-8259U, 16GB DDR4 RAM) which is used as our sandbox and is a little bit stronger then this one. We could run the benchmark on it if only we could know how to run it (automatically, I mean, send the result to the website directly).
