### ISSUE TITLE
Unify Docker image environment for run

### ISSUE THREAD

**Issue by cyrusmsk** [the-benchmarker/web-frameworks#6478]
Some languages are run on Debian bullseye, Rust is on Debian-slim, Crystal is on Alpine which is even Musl based.
Shouldn't all langs use the same docker image for run to be comparable?

To build executable it is possible to use anything, but running should be on the same platform.

**Comment by waghanza** [comment]
Hi @cyrusmsk,

The idea behind that is to use the slimest image per language and to stick to some _best practices_ corresponding to this language.

I'm not convinced that using the same dist is a game changer, but we can try to.

Debian-slim seems to be a good candidate, but not sure all language have this docker image variant.

However, if you find a "universal dist" for all languages, let's try, I can give a try.
