### ISSUE TITLE
[Meta] Schedule Run & misc. suggestions 

### ISSUE THREAD

**Issue by ShreyasJejurkar** [the-benchmarker/web-frameworks#6587]
Hi everyone, I just have one suggestion can we schedule the run once per month and can we show the date of the next run on the home page so that people can target the changes and merge before that date? And also it would be a good user experience overall! 

Another question: I did not find it on-site, but is there any way we can compare the results between the 'runs'? 

One another thing, we should introduce filters for `Micro` and `Full-Stack` frameworks for easiness so that people can compare actual business-ready frameworks instead of just getting carried away by micro which are not fully functional as Full-Stack ones!

**Comment by waghanza** [comment]
Hi @ShreyasJejurkar,

Thanks for the ideas.

- Run once per month and display the next run on home page

Actually, we are not so stable enough. I try to run result once per week (publication on monday)

- I did not find it on-site, but is there any way we can compare the results between the 'runs'?

We do not have. You can do it manually, but we do not have this yet.

- We should introduce filters for Micro and Full-Stack frameworks for easiness

Feel free to open a PR, but might be a lot of categories of frameworks, not only `micro` and `full-stack`

**Comment by ShreyasJejurkar** [comment]
> Actually, we are not so stable enough. I try to run result once per week (publication on monday)

Ohh ok ok, no worries! BTW on every Monday the 'runs' happens is it? 

> We do not have. You can do it manually, but we do not have this yet

Ok, no worries! Maybe we can add this to the backlog if it's maintained for future consideration! 

> Feel free to open a PR, but might be a lot of categories of frameworks, not only micro and full-stack

Sure thing, I will get familiar with the FE codebase and will proceed with this! I can understand there might be a lot of categories, but I guess as of now on a high level, we can categorize the FWs. OR maybe we can categorize popular/recommended/most-used/official FW in each language so that people won't get confused with some hobby projects looking at their perf numbers. 😅😅

**Comment by waghanza** [comment]
> every Monday the 'runs' happens is it?

Yes

> Sure thing, I will get familiar with the FE codebase and will proceed with this!

FE ?

> OR maybe we can categorize popular/recommended/most-used/official 

I may prefer to use factual indicators, I mean indicator related to itself (category ...), the other will be added later (trend, star on github or else, community ...)

**Comment by ShreyasJejurkar** [comment]
> Yes

Ok ok. I will wait for next Monday to see the PGO effects! 😅

> FE ?

Front-end

> I may prefer to use factual indicators, I mean indicator related to itself (category ...), the other will be added later (trend, star on github or else, community ...)

Ok, Ok,!
