### ISSUE TITLE
Introduce OAT++

### ISSUE THREAD

**Issue by waghanza** [the-benchmarker/web-frameworks#659]
+ Language : C++
+ Repo : https://github.com/oatpp/oatpp
+ Author : @lganzzzo
+ Website : https://oatpp.io/

**Comment by waghanza** [comment]
Hi @lganzzzo,

Would you mind to add (or consent that we add) [oatpp](https://github.com/oatpp/oatpp) in `here` ?

This project compare performance based on 3 routes :

+ `GET` `/`, **SHOULD** return a successful status code and an empty string
+ `GET` `/user/:id`, **SHOULD** return a successful status code and the id
+ `POST` `/user`, **SHOULD** return a successful status code and an empty string

Regards,

/cc @mfirry

**Comment by lganzzzo** [comment]
Hello @waghanza ,

Thank you for invitation!

Once I prepare test project I'll send you a PR.

Regards,
Leonid

**Comment by lganzzzo** [comment]
Hello @waghanza ,

Sorry for being inactive lately.
But be sure that this task is in my pool.
I will get back to it.

Regards,
Leonid

**Comment by KaungZawHtet** [comment]
@lganzzzo any progress in involvement ?

**Comment by lganzzzo** [comment]
Hey @KaungZawHtet ,

At the moment no progress so far.
Please feel free to contribute if you have time and/or inspiration - I'll provide all the necessary assistance and help.

Regards,
Leonid

**Comment by cyrusmsk** [comment]
This issue could be closed
