### ISSUE TITLE
[D] Frameworks issues

### ISSUE THREAD

**Issue by cyrusmsk** [the-benchmarker/web-frameworks#6609]
Hi @waghanza 

I've tried to run servers handy and serverino locally with the command:
`wrk -H 'Connection: keep-alive' -d 5s -c 512 --timeout 8 -t 8 http://127.0.0.1:3000`

They showed some values of requests, and still servers continue to work without any errors.
But I didn't use Dockers. Just run servers and wrk locally.
Can you get the error logs from your run or give any recommendations to test them locally?

**Comment by waghanza** [comment]
I'll investigate I have
```
wrk -H 'Connection: keep-alive' -d 5s -c 512 --timeout 8 -t 8 http://172.17.0.2:3000
Running 5s test @ http://172.17.0.2:3000
  8 threads and 512 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     0.00us    0.00us   0.00us    -nan%
    Req/Sec     0.00      0.00     0.00      -nan%
  0 requests in 5.06s, 0.00B read
Requests/sec:      0.00
Transfer/sec:       0.00B
```

Maybe `Worker running as root. Is this intended? Set user/group from config to run worker as unprivileged user.`, I think we have to change the user on dockerfile

**Comment by cyrusmsk** [comment]
Is it the picture for both Serverino and Handy?
Do you mean set user inside dockerfile?

**Comment by cyrusmsk** [comment]
Btw I've tried to run it in the docker locally. And it is working for me for both handy and serverino.
I used just simple Dockerfile. Build it and run with 
`docker run -d -p 3000:3000 image_name`

**Comment by waghanza** [comment]
With `handy` the following command
```
wrk -H 'Connection: keep-alive' --connections 64 --threads 8 --duration 15 --timeout 1 --script /home/waghanza/workspace/benchmark/web/pipeline.lua http://172.17.0.2:3000
```

leads to

```
Running 15s test @ http://172.17.0.2:3000
  8 threads and 64 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    27.59ms   42.32ms 489.95ms   86.06%
    Req/Sec   222.25    384.21     2.18k    90.00%
  24702 requests in 15.07s, 458.34KB read
  Socket errors: connect 0, read 24702, write 0, timeout 0
Requests/sec:   1638.88
Transfer/sec:     30.41KB
```

**Comment by cyrusmsk** [comment]
It looks almost the same that I got locally on my laptop

**Comment by waghanza** [comment]
I have 
```d
★ [000008] [l] 2023-08-14 16:09 [connectionhandler.d:0315] Socket error on read. Resource temporarily unavailable
```
when running `servernio` on my laptop through `docker`

**Comment by waghanza** [comment]
Not sure I understand https://github.com/trikko/serverino/blob/e425ffcb2090bd7fd6f9d1db7c230a5dbc7035e5/source/serverino/connectionhandler.d#L315 @trikko and why a GET request could produce this

cc @cyrusmsk

**Comment by cyrusmsk** [comment]
Hi. Did you change something in the run? Because now serverino is working.. but it is strange..

**Comment by waghanza** [comment]
Yes, strange.

I've only update the version

**Comment by cyrusmsk** [comment]
Will close for now.
Maybe we can delete archttp - it looks abandoned and not working currently.

**Comment by waghanza** [comment]
Is archttp abandoned @zoujiaqing ?
