### ISSUE TITLE
Benchmark Results Force Reload

### ISSUE THREAD

**Issue by Ethosa** [the-benchmarker/web-frameworks#6636]
It's possible to force reload benchmark results after adding a new web framework?

**Comment by cyrusmsk** [comment]
No.
Usually new results are made public on Monday.

**Comment by waghanza** [comment]
I am not able to produce results this week, the next version will be out next Monday @Ethosa

**Comment by Ethosa** [comment]
@waghanza when you publish bench results? 🙂

**Comment by waghanza** [comment]
Tomorrow, I have messuped this one, I need to recompute all results (~20h)
