### ISSUE TITLE
Production readiness marks

### ISSUE THREAD

**Issue by yutkin** [the-benchmarker/web-frameworks#667]
It would be nice if web-frameworks be marked somehow like "production ready" or it is just a "research project". This information is very helpful when you choosing a web-framework for a new project.

**Comment by waghanza** [comment]
@yutkin I'm working on making it **production-ready**

Feel free to follow for this https://github.com/the-benchmarker/web-frameworks/pull/632 :heart: 

I close this issue, fell free to re-open
