### ISSUE TITLE
[D] Remove archttp?

### ISSUE THREAD

**Issue by waghanza** [the-benchmarker/web-frameworks#6740]
@zoujiaqing Is `archttp` still maintained ?

cc @cyrusmsk

**Comment by cyrusmsk** [comment]
@waghanza I will ask in community if someone wants to continue the maintaining.

**Comment by waghanza** [comment]
any news @cyrusmsk ?

**Comment by cyrusmsk** [comment]
Unfortunately no. So I suppose you can delete it from the comparison for now

**Comment by waghanza** [comment]
I'd remove it for the next release @zoujiaqing
