### ISSUE TITLE
Provide specs

### ISSUE THREAD

**Issue by drujensen** [the-benchmarker/web-frameworks#68]
Can you provide specs for your benchmarks?

- version of each language and framework
- operating system specs
- machine specs - memory, cpu, etc
- all flags used to compile the application
- how each application was launched

**Comment by tbrand** [comment]
Thanks for the suggestion, I have a plan to add such specs. But some of them will be omitted since this benchmark is OSS. I want to keep the maintenance cost lower.

**Comment by waghanza** [comment]
@drujensen perhaps you could have a good idea to debate about how to launch application #123 (**docker** could be a solution)
