### ISSUE TITLE
Add Uvicorn

### ISSUE THREAD

**Issue by btegs** [the-benchmarker/web-frameworks#680]
+ Language : Python 3
+ Repo : https://github.com/encode/uvicorn
+ Author : @tomchristie

**Comment by waghanza** [comment]
@btegs `uvicorn` is **not** a framework.

There is `quart` for example where `uvicorn` is used.

For me using non-framework implementation is out-of-scope here, because if we consider this, why not using raw `crystal` or raw (any language) ?
