### ISSUE TITLE
README.md Display Error

### ISSUE THREAD

**Issue by jowabels** [the-benchmarker/web-frameworks#682]
I am not sure if I missed something, but there is no available content from the README in this repository.

![image](https://user-images.githubusercontent.com/14179376/49439197-5b92cf00-f7fb-11e8-86b9-5c2e36d43450.png)

**Comment by waghanza** [comment]
I'm on it ;-)

There was an error on updating results this morning

**Comment by waghanza** [comment]
@jowabels I've fixed this, I'll update results soon :heart:

**Comment by waghanza** [comment]
@jowabels I've update results https://github.com/the-benchmarker/web-frameworks#full-table
