### ISSUE TITLE
[Java] Include Spring WebFlux in Benchmark

### ISSUE THREAD

**Issue by dmartinsid** [the-benchmarker/web-frameworks#6885]
Spring WebFlux offers significant scalability advantages over Spring MVC. WebFlux leverages a reactive model, whereas MVC relies on a Thread Per Request model.

I am opening this issue to propose the inclusion of Spring WebFlux in the benchmark as it represents a valuable addition to our performance evaluation.

I plan to submit a pull request with this contribution shortly.

**Comment by waghanza** [comment]
Hi @dmartinsid ,

Thanks for the suggestion. It will be great.

Please note that results will be updated on monday

**Comment by dmartinsid** [comment]
Implemented in https://github.com/the-benchmarker/web-frameworks/pull/6920
