### ISSUE TITLE
Parallelism

### ISSUE THREAD

**Issue by drujensen** [the-benchmarker/web-frameworks#69]
Some of these languages provide parallelism and others don't.  

For Crystal, if you have a multicore system, you need to run multiple processes (1 per core) with reuse port enabled to take advantage of them.

**Comment by tbrand** [comment]
I think the parallelism is a language level feature.
Reusing port and running multiple processes on it is a OS level feature.

If crystal supports the parallelism in language level, I will tune each framework.

**Comment by OvermindDL1** [comment]
> For Crystal, if you have a multicore system, you need to run multiple processes (1 per core) with reuse port enabled to take advantage of them.

Wait what why?  Does crystal really not have threading?!  o.O

**Comment by drujensen** [comment]
Not yet. It's planned for 1.0 but for now, you can use reuse port flag.

**Comment by AlexWayfer** [comment]
I'll try to make Puma use all CPU cores for Ruby frameworks.

**Comment by OvermindDL1** [comment]
@AlexWayfer Ping me when a PR is submitted and I'll run the tests.  :-)

**Comment by waghanza** [comment]
as in #239 @OvermindDL1 noticed `SO_REUSEPORT` **SHOULD** be used

**Comment by waghanza** [comment]
@drujensen @tbrand Parallelism has been introduced in `crystal` 
https://crystal-lang.org/2019/09/06/parallelism-in-crystal.html

It will be a pleasure to enable this feature in `here`

**Comment by OvermindDL1** [comment]
Ooo nice!  That was one *huge* feature that crystal was lacking!
