### ISSUE TITLE
Include gccgo in benchmarks for go frameworks?

### ISSUE THREAD

**Issue by Puffton** [the-benchmarker/web-frameworks#698]
Hi, first of all, awesome work on compiling this list of benchmarks! :D

It would be cool to see how compiling with gccgo (with gcc's optimization flags) affects the performance of the go web frameworks, since it's a completely different compiler backend. But perhaps it would be too verbose to list all go frameworks twice?

_The Go 1.10 runtime has now been fully merged into the GCC development sources, and concurrent garbage collection is expected to be fully supported in GCC 8._

_The gccgo compiler supports all GCC options that are language independent, notably the -O and -g options._

_On x86 GNU/Linux systems the gccgo compiler is able to use a small discontiguous stack for goroutines. This permits programs to run many more goroutines, since each goroutine can use a relatively small stack. Doing this requires using the gold linker version 2.22 or later._

**Comment by waghanza** [comment]
Hi,

@Puffton Thanks for this idea, but I think this is more specific than want we are trying to achieve here. 

It could be awesome to benchmark `go` **frameworks** on the different optimisations, but it's the goal here.

The goal here is more generalist : one implementation per framework.

This could be done, but in an other repository (could be in this group then) and I will be happy to help :heart:
