### ISSUE TITLE
uWebSockets (javascript framework) is not included in the latest release [2024-01-23 (19a4d71)]

### ISSUE THREAD

**Issue by jvlad** [the-benchmarker/web-frameworks#7175]
... however, it was a part of the previous one:  
<img width="1173" alt="Screenshot 2024-01-26 at 9 28 18 PM" src="https://github.com/the-benchmarker/web-frameworks/assets/12549265/ea3143fb-17f7-4f63-929d-dff2d4de78e4">

Now, it's not shown:  
<img width="1176" alt="Screenshot 2024-01-26 at 9 28 43 PM" src="https://github.com/the-benchmarker/web-frameworks/assets/12549265/fb91f577-1723-42d7-bc92-7d7a5a3a3c1f">

@waghanza Is it a bug?

**Comment by waghanza** [comment]
I think so, let's see what's happen on monday

need to refactor cde base to make sure this will be prevented
