### ISSUE TITLE
hono is only tested using node, should be tested using bun

### ISSUE THREAD

**Issue by bompus** [the-benchmarker/web-frameworks#7219]
hono is native to bun, with an adapter to support node. It looks like your current implementation is only using the node engine with the node server adapter.

If tested using bun, without the node adapter, it should rank between stricjs and elysia, based on my own testing.

**Comment by waghanza** [comment]
you are right @bompus , `hono` should be tested at least on
+ `node`
+ `bun`
+ `deno`

before, this is already possible, but the UI should first be adapted for that (planned but I don't have any ETA)

**Comment by bompus** [comment]
@waghanza I wonder if it's possible without a UI update, to just label them with suffixes like hono (node), hono (bun), hono (deno). It makes the list longer, but wouldn't require a UI update to add an engine column/filter.

**Comment by waghanza** [comment]
Sure @bompus, it could be easily done

Feel free to open a PR, I will follow 😉

**Comment by bompus** [comment]
Thank you for tackling this!

I saw the latest results, and they don't line up with my own experience and tests. On Bun, hono and elysia should be right up there with stricjs, very close to it in terms of performance. However, both hono-bun and elysia are way down on the list, and I'm not sure why.

I compared the configs, cluster, app files between stricjs, hono-bun, and elysia, and they all look correct to me, but the performance just doesn't line up with what I see when I run bun cluster.ts on my own VM.

Perhaps this should be a new issue, but it's so recent I figure we could discuss here, just in case something was missed somewhere, or perhaps the results parser is parsing something incorrectly?

**Comment by waghanza** [comment]
I am not sure why both frameworks should be close, but indeed stricjs seems far away

https://web-frameworks-benchmark.netlify.app/result?f=hono-bun,stricjs,elysia

Worth to investigate

A PR could be open with debug enabled to understand why this diff. Also there is the idea of timeout. The actual sieging command is removing all requests with a timeout greater than 1 sec.

Maybe we should try to get wrk raw output (stress tool direct output, without any calculation)

**Comment by waghanza** [comment]
Also be aware that network in use is a loopback, not a real connection
