### ISSUE TITLE
Add robyn python framework

### ISSUE THREAD

**Issue by jackcvr** [the-benchmarker/web-frameworks#7368]
https://github.com/sparckles/Robyn

**Comment by waghanza** [comment]
Hi @jackcvr,

Thanks for suggestion. Feel free to open a PR and add it, I'll follow if you have some issue's

**Comment by waghanza** [comment]
Hi @sansyrox,

In this project we compare raw performance (and other indicators will come) between several frameworks. Do you consent (or at least do not oppose to) include `robyn` in this list ?

Regards,

PS : Even if it is opensource, I prefer ask before 😛

**Comment by sansyrox** [comment]
Hey @waghanza 👋 

I would be happy to see the benchmarks 😄 Thanks for asking. I have just added one suggestion on the PR for the maximum throughput
