### ISSUE TITLE
[Gleam] Add mist

### ISSUE THREAD

**Issue by whiplash** [the-benchmarker/web-frameworks#7386]
I'd be great to have [Gleam](https://gleam.run/) and [mist](https://github.com/rawhat/mist) /cc @rawhat

**Comment by waghanza** [comment]
Sure @Bakugo90,

The requirement is to have a simple implementation in a folder `gleam/mist` that reply to 3 routes :

+ “/“ and GET request - empty response
+ “/user” and POST - empty response
+ “/user/{id}” GET request - id in response

The `gleam` language is not yet present, so you might need to create a `Dockerfile` as well as a `config.yaml` file. Let's create a PR with this implementation, with your permission I'll add some dockerfiles ...

**Comment by Bakugo90** [comment]
Thanks @waghanza,
I just gained more understanding through your explanation. 

> with your permission I'll add some dockerfiles ...

No problem for this, you can go ahead !

**Comment by whiplash** [comment]
@Bakugo90 do you have any experience using Gleam?

**Comment by Bakugo90** [comment]
@whiplash,
> Do you have any experience of using Gleam?

No, this is my first time hearing about it. As a newbie to open source, I'm eager to learn the things necessary to solve these issues.

**Comment by whiplash** [comment]
hey @rawhat would you have some time for this?

**Comment by rawhat** [comment]
Probably not to do all the scaffolding and everything.  The app itself seems simple enough, though.

**Comment by whiplash** [comment]
Thanks @rawhat could you contribute with "just" the code? O part of it? We'll work on the scaffolding and complete what's missing. It's fine if you don't have time, we thank you anyways. Keep up with the good work!

**Comment by whiplash** [comment]
@rawhat have a look at https://github.com/the-benchmarker/web-frameworks/pull/8016 in your own good time

**Comment by whiplash** [comment]
So this is done!
