### ISSUE TITLE
Add Muneem

### ISSUE THREAD

**Issue by amitguptagwl** [the-benchmarker/web-frameworks#748]
+ Language : node
+ Repo : https://github.com/node-muneem/muneem/
+ Author : Amit Kumar Gupta @amitguptagwl

Let me know if I should add more detail. Or if I need to explain its usage.

**Comment by waghanza** [comment]
@amitguptagwl If you have time to create a `PR` (the implementation is very simple), it will be gladly appreciated

**Comment by amitguptagwl** [comment]
Yeah sure. I'll update you.

> Suggestion: We should remove very old git history as I can see the project size has been grown to 100mb approx.

**Comment by amitguptagwl** [comment]
I'm facing issues installing shard locally. Seems some issue with the latest build of crystal. Will you mind if I submit PR without following these steps;
```
~~~
export FRAMEWORK=<MY_FRAMEWORK>
shards install
shards build --release
bin/neph ${FRAMEWORK}
crystal spec
~~~
```

**Comment by waghanza** [comment]
sure, but I could also help install `crystal`

@see https://crystal-lang.org/docs/installation/

**Comment by amitguptagwl** [comment]
yes that I've tried and raised an issue on their repo https://github.com/crystal-lang/crystal/issues/7265
