### ISSUE TITLE
add warp(rust)

### ISSUE THREAD

**Issue by adals** [the-benchmarker/web-frameworks#751]
https://github.com/seanmonstar/warp

**Comment by waghanza** [comment]
It will be awesome to have an `PR` :heart:

**Comment by waghanza** [comment]
Hi @seanmonstar,

Would you mind to add (or consent that we add) [warp](https://github.com/seanmonstar/warp) in `here` ?

This project compare performance based on 3 routes :

+ `GET` `/`, **SHOULD** return a successful status code and an empt²y string
+ `GET` `/user/:id`, **SHOULD** return a successful status code and the id
+ `POST` `/user`, **SHOULD** return a successful status code and an empty string

Regards,
