### ISSUE TITLE
Add CodeBehind Framework

### ISSUE THREAD

**Issue by elanatframework** [the-benchmarker/web-frameworks#7515]
Please compare [CodeBehind](https://github.com/elanatframework/Code_behind) framework with other back-end frameworks.

CodeBehind is a new framework based on ASP.NET Core published by [Elanat](https://elanat.net).

![ASP.NET Core web frameworks list](https://github.com/the-benchmarker/web-frameworks/assets/111444759/4a6de8a8-41fb-4784-abb2-7de82da16648)

According to the latest tests of the Elanat team, the CodeBehind framework is up to 40% faster than the default ASP.NET Core frameworks (ASP.NET Core MVC and Razor Pages).
[Performance test, ASP.NET Core MVC and Razor Pages vs CodeBehind Framework in version 2.2](https://github.com/elanatframework/Code_behind/blob/elanat_framework/doc/performance_test_asp_dot_net_core_mvc_and_razor_pages_vs_code_behind_framework_version_2.2.md)

GitHub link:
https://github.com/elanatframework/Code_behind

**Comment by waghanza** [comment]
Hi @elanatframework ,

Thanks for the suggestion.

I can not add any framework myself, but I can surely make a review for any PR.

Regards,
