### ISSUE TITLE
About elysiajs，gin benchmark

### ISSUE THREAD

**Issue by ByteByteBrew** [the-benchmarker/web-frameworks#7524]
Environment: Window11 local
elysia: bun .\cluster.ts
0http-bun: bun .\cluster.ts
gin: go build && .\main.exe

The performance of the three frameworks in wsl using wrk stress testing is quite different. Is it caused by the test problem?

elysia:
<img width="958" alt="elysia" src="https://github.com/the-benchmarker/web-frameworks/assets/37368500/1c2a596f-8801-445f-85e8-696b7b29698d">

0http-bun:
<img width="958" alt="ohttp-bun" src="https://github.com/the-benchmarker/web-frameworks/assets/37368500/e57ef582-8fbd-4642-95f5-2c8951236dc1">

gin:
<img width="958" alt="gin" src="https://github.com/the-benchmarker/web-frameworks/assets/37368500/a20c1e56-7abb-4e0b-8ac0-836c108dd1be">

**Comment by waghanza** [comment]
Hi @ByteByteBrew ,

Thanks for those indicators, but I do not understand which problem are you refering to.

Regards,

**Comment by waghanza** [comment]
Ah, I see.  Those 2 projects are completely differents, we can not compare both.

We are not using same hardware / same versions ... The idea here is more to show how frameworks could perform, but keeping a consistency beetween then.

Of course, the implementations are not perfect, and if you find an issue, feel free to PR ❤️
