### ISSUE TITLE
ditsmod-bun does not use cluster mode

### ISSUE THREAD

**Issue by KostyaTretyak** [the-benchmarker/web-frameworks#7990]
So, ditsmod on Node.js is many times faster than ditsmod on Bun:
![Screenshot from 2024-11-27 17-07-56](https://github.com/user-attachments/assets/18825276-c1cb-44ca-bc4d-854c8782a9a6)

This is because ditsmod on Bun actually runs on a single core, without using cluster mode. Which, in turn, is caused by these changes in the latest release:

https://github.com/the-benchmarker/web-frameworks/pull/7966/commits/e0cb95acac5df3bc10601d52e499158f199d0a7d#diff-2860b74bd1fe8de8980f88f5898296185daf185d083a7ca1457df03452c466ee

I wonder why you made this edit? Are you not using `pm2` when you run apps on Bun?

**Comment by waghanza** [comment]
As I understand `pm2` is recommended for `node`  (i.e : to run all CPUs).

Not sure this tool is recommended for others, feel free to propose any change. The idea is to take advantage of all computer power, but `pm2` has hard-defined `node` dependencies, maube it is not the recommanded tool

**Comment by KostyaTretyak** [comment]
Fixed in https://github.com/the-benchmarker/web-frameworks/pull/7993
