### ISSUE TITLE
[Rust] Axum Vs Actix does not do the same thing?

### ISSUE THREAD

**Issue by wyatt-herkamp** [the-benchmarker/web-frameworks#8024]
So in the [Axum](https://github.com/the-benchmarker/web-frameworks/blob/master/rust/axum/src/main.rs) code you
First extract the `:id` and it gets converted into an u8. Then call .to_string()?

But in the [Actix](https://github.com/the-benchmarker/web-frameworks/blob/master/rust/actix/src/main.rs) the id is kept as a string.  

Just as an initial test to make sure it mattered. 
```rust
use axum::extract::Path;
use axum::routing::{get, post};
use axum::Router;

#[tokio::main]
async fn main() {
    let router: Router = Router::new()
        .route("/", get(|| async {}))
        .route("/user", post(|| async {}))
        .route("/user/:id", get(|Path(id): Path<String>| async move { id }));

    let listener = tokio::net::TcpListener::bind("0.0.0.0:5000").await.unwrap();
    axum::serve(listener, router.into_make_service())
        .await
        .unwrap();
}
```
 
The left is old code the one on the right is the new code. 
![image](https://github.com/user-attachments/assets/58e32abe-b00b-4ba4-9806-2e4f03eb50ba)

I did have to use port 5000 I have port 3000 in use for something else. 

Also note router is a builder pattern so no need to have all that code yall have

**Comment by waghanza** [comment]
Thanks for catching this :tada:


Feel free to open a PR, I try to update results each monday
