### ISSUE TITLE
Cache docker containers

### ISSUE THREAD

**Issue by waghanza** [the-benchmarker/web-frameworks#851]
Hi,

**CI** build take a huge amount of time. 

This could be reduced by caching containers, solution found in https://github.com/travis-ci/travis-ci/issues/5358#issuecomment-248915326

I'm not sure this will increase a lot build time, since the cache is store on a remote `S3`.

We have to time this.

Regards,

**Comment by OvermindDL1** [comment]
I cache my build container on an S3 server (not amazon's but my own) for various projects and it is *significantly* useful.  I just have a task that rebuilds it whenever related source code changes in the related git repos.

**Comment by waghanza** [comment]
Cache **MUST NOT** be done, on dependabot branches
