### ISSUE TITLE
Running on a public cloud ?

### ISSUE THREAD

**Issue by waghanza** [the-benchmarker/web-frameworks#92]
Hi,

I found this project very useful, at least an element of my technical choices.

I think that running all tests on one public cloud

+ AWS
+ DigitalOcean
+ ...

Could help / lead in technical choices ?

What do you think about that ?

Regards,

**Comment by tbrand** [comment]
That's good idea but there are some issues for it.
- This project includes a Objective-C project that can be compiled only in Mac(?).
- It costs some. :money: (According to previous discussion, we decided not to run this on CI. https://github.com/tbrand/which_is_the_fastest/issues/27)

As a founder of this project, I want(have) to take all results of this benchmark.
But you can fork this and choice some language as targets.

Following tips might help you.

```bash
# Choice ruby, crystal and go as targets
make benchmarker ruby crystal go

# Running benchmark
bin/benchmarker ruby crystal go

# If you want to record the results onto README.md
bin/benchmarker ruby crystal go --record
```

Thanks!

**Comment by waghanza** [comment]
Hi @tbrand,

You underline multiples arguments  here.

+ Some codes are compiled on **Mac OS X*, since `Objective C`
   + Travis could compile that ;-)
+ It cost some :money:
   + Perhaps a good solution could be to create a blog to share the results as a community (I'd happy to support cost, hosting platform ... and some hosting services **COULD** be free for OSS)

**Comment by OvermindDL1** [comment]
I'm *NOT* a fan of performing benchmarks on a cloud/shared anything as then you will get inconsistent results (well you would get inconsistent results on a mac desktop too)  An 'empty' dedicated server is what should be used (see my other issue with some results from that among other tests, which really should be built in to this too for statistical testing).  https://github.com/tbrand/which_is_the_fastest/issues/101

**Comment by waghanza** [comment]
@OvermindDL1 I understand you concern, I'm not a **fan** either. For me running, running on **shared** environments **COULD** break result consistency.

However, `cloud` **IS NOT** `shared`. Of course, technically an *hypervisor* is used
* XEN
* KVM
* Hyper V
* ...

However, running on `cloud` mean isolation (all instances has their own CPU / memory), at least `cloud providers` I have tested
* AWS
* DigitalOcean

**Comment by OvermindDL1** [comment]
I know cloud is not shared, but cloud does not always imply a 'set' instance of cpu/memory.  Those can be migrated in surprising ways and though you may keep a set amount of cpu and memory there can be sudden and surprising latencies that will not occur on a dedicated system.

**Comment by waghanza** [comment]
I understand. However :

* a majority of (enterprise) application adopt cloud 
   * why running elsewhere ? 
   * is our goal to be closest to **production-ready** application usage ?
* bar-metal / full isolation are expensive
   * could bar-metal automatizable ?

**Comment by OvermindDL1** [comment]
> is our goal to be closest to production-ready application usage ?

This is expressely *not* the goal of this repository.  ;-)

>> We want to know the response time (routing time), not a usability.

And the latency randomness and other issues that cloud would induce would just induce random noise into the benchmarks, which is *NOT* what you want in a benchmark.

> bar-metal / full isolation are expensive

Not even remotely?  I have a 16 core with 16gigs ram dedicated server that I test on here, see:  https://github.com/tbrand/which_is_the_fastest/issues/101

**Comment by waghanza** [comment]
> This is expressely not the goal of this repository. ;-)
So what is the main goal ?

@OvermindDL1 I do not understand your last point

**Comment by OvermindDL1** [comment]
> So what is the main goal ?

Pure speed testing with as few other variables as possible.

> @OvermindDL1 I do not understand your last point

I.E. I can perform dedicated server tests with ease.  It's a build server I own and it's trivial to suspend the CI for a period as I run tests, as I did in that post.  In the post I show the statistical output of the tests and if run on a cloud or shared system then these would vary far more wildly that a statistical system could show but would otherwise corrupt the output of the current setup (as tbrand is currently doing by running it on a desktop, why do you think his results wildly differ from mine).

**Comment by waghanza** [comment]
> Pure speed testing with as few other variables as possible.
yes, but it will be accurate to use a particular usage, **production** usage.
actually, `django` run on `gunicorn` (no built-in server) but `flask` use buit-in one.
none of enterprise project, using `flask`, run on **built-in**

@OvermindDL1 I understand that you have different result than @tbrand, not the same hardware ... so why not running on a _standard_ (and usable by others) hosting, aka cloud ?

**Comment by OvermindDL1** [comment]
Because free server, and a lot more powerful than what most cloud things offer especially taking into account the prices...  ^.^;

_/me is still amazed at how slow crystal was on the tests here, wonder if related to them not running in production mode, should test again (ping me on that one issue if anyone wants the statistical tests to be re-run!)..._

**Comment by waghanza** [comment]
:trollface: free ? it is amazing, it don't known about **free** hardware

anyway, my *presonal* purpose **IS** to test raw-performance in each frameworks, but in the closest way as **enterprise** does use those frameworks

**Comment by OvermindDL1** [comment]
> :trollface: free ? it is amazing, it don't known about free hardware

It's quite common!  Once it's paid for you get free unlimited use of it!  Excepting cost of electricity (and maybe internet if it's not shared out to something else, which mine is).  ;-)

> IS to test raw-performance in each frameworks,

Ah so you *definitely* don't want weird latencies popping up!

**Comment by waghanza** [comment]
> It's quite common! Once it's paid for you get free unlimited use of it! Excepting cost of electricity (and maybe internet if it's not shared out to something else, which mine is). ;-)
Sure, it not **free** but the major cost part is initial ;-)

> Ah so you definitely don't want weird latencies popping up!
I don't understand

**Comment by OvermindDL1** [comment]
> I don't understand

If you are wanting to test raw throughput without uncontrollable internet and system conditions interfering, then you want as stable a test-bed as possible.  :-)

**Comment by waghanza** [comment]
ah, ok
you say that the internet connection stability could case result inconsistency

**Comment by OvermindDL1** [comment]
> you say that the internet connection stability could case result inconsistency

That is one possible conditions, hence why you'd prefer to test between 2 machines on a dedicated local wired network (which I also have, though this repo's built-for single server right now, which is not entirely reliable either since you should never test from the same system that the server is running on), with no other processes running on them, dedicated hardware with no chance of migration or anything else of the sort, etc...

Running it under any other conditions (like on a desktop machine) introduces in changes that be be quite significant (like the latest update that puts Phoenix faster than Plug, which would never *ever* happen as Phoenix is just 'more' plugs on top of Plug).

**Comment by waghanza** [comment]
interesting point of view
you must do a lot of automation, to provide a clean and isolated environment to run each framework, thus

even in cloud we can run on a dedicated connection (or as closest as a local one)

**Comment by OvermindDL1** [comment]
> you must do a lot of automation

Ungodly huge amounts.  CI build systems for everything from C++ to Elixir and more (Rust recently growing).  Server deployment automation.  Etc...  I have no clue how I've even reached this point but even just me personal non-work stuff is massive...  >.>

**Comment by waghanza** [comment]
I see that it is a point to run on **cloud**, though, at least to decrease _your_ time automating everything

**Comment by OvermindDL1** [comment]
> I see that it is a point to run on cloud, though, at least to decrease your time automating everything

Except that would cause me 'more' work, as well as *substantially* more cost.  ^.^;
