### ISSUE TITLE
Introduce NestJS

### ISSUE THREAD

**Issue by waghanza** [the-benchmarker/web-frameworks#954]
+ Language : javascript
+ Repo : https://github.com/nestjs/nest
+ Author : @kamilmysliwiec

**Comment by kalicki** [comment]
NestJS uses by default ExpressJS

**Comment by waghanza** [comment]
Welcome back @kalicki. Yes NestJS use ExpressJS (and can use Fastify), but probably TypeScript adds some perfs / usefull usage 👌

**Comment by kalicki** [comment]
NestJS with ExpressJS is 10~40ms slower compared to ExpressJS with pure JS

**Comment by waghanza** [comment]
OK. Let add nest to see this diff 😊.

I have no intention to say that you're wrong, just want to show performance. Moreovever this figures could change depending on version used

**Comment by kamilmysliwiec** [comment]
It's probably worth adding both examples (Nest with Express and Nest with Fastify)

**Comment by waghanza** [comment]
@kamilmysliwiec sure both will be awesome 

Could you link your stackoverflow answer here ?

**Comment by kalicki** [comment]
Now yes, it makes sense to compare NestJS with Express vs. Fastify.

**Comment by kalicki** [comment]
> @kamilmysliwiec sure both will be awesome
> 
> Could you link your stackoverflow answer here ?

Check: https://stackoverflow.com/questions/47733390/nestjs-vs-plain-express-performance/48226084#48226084

**Comment by waghanza** [comment]
Glad we are on the same line @kalicki

**Comment by waghanza** [comment]
Hi @kamilmysliwiec,

Would you mind to add (or consent that we add) [nestjs](https://github.com/nestjs/nest) in `here` ?

This project compare performance based on 3 routes :

+ `GET` `/`, **SHOULD** return a successful status code and an empty string
+ `GET` `/user/:id`, **SHOULD** return a successful status code and the id
+ `POST` `/user`, **SHOULD** return a successful status code and an empty string

Regards,

**Comment by zieglar** [comment]
please check this PR [#2571](https://github.com/the-benchmarker/web-frameworks/pull/2571)
