### ISSUE TITLE
Introduce Coast for Clojure

### ISSUE THREAD

**Issue by elamje** [the-benchmarker/web-frameworks#970]
+ Language : Clojure
+ Repo : [Coast on GitHub](https://github.com/coast-framework/coast)
+ Author : [Sean Walker](https://github.com/swlkr)
+ Details : This framework is relatively new and Clojure is in dire need of a Django/Rails type of framework for newbies to join the Clojure web community. This project is the best swing I've found on. This would be a huge win to get some publicity and performance details on here.

**Comment by waghanza** [comment]
Hi @swlkr,

Would you mind to add (or consent that we add) [coast](https://github.com/coast-framework/coast) in `here` ?

This project compare performance based on 3 routes :

+ `GET` `/`, **SHOULD** return a successful status code and an empty string
+ `GET` `/user/:id`, **SHOULD** return a successful status code and the id
+ `POST` `/user`, **SHOULD** return a successful status code and an empty string

Regards,
