### ISSUE TITLE
Introduce negroni

### ISSUE THREAD

**Issue by waghanza** [the-benchmarker/web-frameworks#987]
+ Language : go
+ Repo : https://github.com/urfave/negroni
+ Author : @urfave

**Comment by waghanza** [comment]
Hi @codegangsta,

Would you mind to add (or consent that we add) [negroni](https://github.com/urfave/negroni) in `here` ?

This project compare performance based on 3 routes :

+ `GET` `/`, **SHOULD** return a successful status code and an empty string
+ `GET` `/user/:id`, **SHOULD** return a successful status code and the id
+ `POST` `/user`, **SHOULD** return a successful status code and an empty string

Regards,

**Comment by jszwedko** [comment]
:+1: I don't know that Negroni really fits the traditional idea of a web framework, but I'm fine with it being added here if it is useful to others.

**Comment by waghanza** [comment]
You're right @jszwedko, `negroni` is more a middleware than a framework.

The behind (what called here) framework is `net/http` or `gorilla/mux`

I close this issue since is a misunderstanding
